#!/bin/csh
#	Program:	makeprmlst
#	Author:		Tom Yang 
#	Date:		06-Oct-94
# 	Use:		Create a prm file and a subject list file from an image.

set BINPATH = $HOME/src/makeprmlst
if ($#argv != 3) then
	echo " usage: makeprmlst imgfile prmfile lstfile"
	echo "  e.g.: makeprmlst p2450ho1.img test.prm test.sub"
	exit
endif

set imgfile	= $1
set prmfile	= $2
set lstfile	= $3

# Check if the input image file exists.
if (!(-e ${imgfile})) then
	echo "Error: the input image file ${imgfile} does not exist."
	exit
endif

${BINPATH}/makeprmlst.bin ${imgfile} ${prmfile} ${lstfile} 
