#!/bin/csh
#
#		Program:	savelog
#		Author:		Tom Yang
#		Date:		15-Sep-93
#		Usage:		Generate the identifications of a program
#				and save the identifications in a log file.

set argc = $#argv
if ($argc != 1) then
	echo " Usage:  savelog logfile" 
	echo "  e.g.:  savelog sxrweld.log"
	exit
endif

set logfile	= $1

if (-d RCS) then
	set rcs_exist	= 1
else
	set rcs_exist	= 0
endif

if (-e ${logfile}) then
	/usr/bin/rm -f ${logfile}
endif

if (${rcs_exist} == 1) then
	if (-e RCS/${logfile},v) then
		co -l ${logfile}
		/usr/bin/rm -f ${logfile}
	endif
endif

ident sxrweld.bin | sed -e "s/Id//g" > ${logfile}

if (${rcs_exist} == 1) then
	echo . | ci -f ${logfile}
	co ${logfile}
endif
