#!/bin/csh

if (! -e ${NPG_DIR}/IMAGE_UTILS.h) then
	echo Missing IMAGE_UTILS.h
	exit 1
endif
if (! -e ${NPG_DIR}/color_tables) then
	echo Missing color_tables
	exit 1
endif
if (! -e ${NPG_DIR}/vidi.xrdb) then
	echo Missing vidi.xrdb
	exit 1
endif

set files = `ls -d * | grep "\/" | cut -f1 -d/ | egrep -v lib | egrep -v RCS | egrep -v Dev `
foreach i ($files)
	cd $i
	if (! -e Makefile) then
		co -l Makefile
		echo "---------- Edit and save Makefile: $i"
		echo "cd ~/idl/npg/$i; vi Makefile"
		set data=`line`

		co Makefile
		make checkout
		make
		make release
		make cleanall
		/usr/bin/rm -f Makefile
		echo "---------- Build complete: $i"
	else
		echo "---------- Makefile exists: $i"
	endif
	cd ..
	set data=`line`
end
