#!/bin/csh

pwd
set version = `uname -r`
set version = `echo $version | cut -f1 -d.`
if ($version != "5") then
	echo "Warning: this script was written for Solaris"
endif
#
echo "ucl_matrix"
cd ucl_matrix
make -f Makefile_solaris clean
make -f Makefile_solaris
cd ..
pwd
echo "done"
#
echo "mod"
cd mod
make -f Makefile_solaris
cd ..
#
echo "idl/mod"
cd idl/mod
make -f Makefile_solaris
cd ../..
#
echo "hrplus"
cd hrplus
install
cd ..
#
echo "src"
cd src
NCmaxval.compile
mlempetv7.solaris
mappettrans.solaris
cd ..
