#!/bin/csh
#	Module:	metproc
#	Date:	12-May-92
#	Author:	Tom Videen
#	Use:	Create an HDR file allowing display and analysis of a PET image
#			as a metabolic image.
#			Requires a PET image, a blood curve (.DTA), and a calibration file (.PIE)

if ($#argv != 1) then
	echo "Usage: metproc <subject_id>"
	exit
endif
./metproc.bin $1
