;;; Variables for Image I/O
COMMON IMAGE_UTILS, MATRIX_REV6, MATRIX_REV7, INTERFILE, PETT6, ANALYZE, $
	ANALYZE_TYPE, PETT6_TYPE, ana, dsp

MATRIX_REV6	= 1
MATRIX_REV7	= 2
INTERFILE	= 3
PETT6		= 4
ANALYZE		= 5

ANALYZE_TYPE = 501
PETT6_TYPE   = 502

ana = {ANALYZEHDR}
dsp = [{VDISPLAY},{VDISPLAY},{VDISPLAY}]
