#!/bin/csh
#	Module:	ge2img
#	Date:	Aug 2003
#	Author:	Tom Videen
#	Use:	Convert GEMS PET Export image files to ECAT Matrix 7 format

set BINPATH = /home/npggw/tom/src/ge2img

if ($#argv < 2 || $#argv > 4) then
	echo "Usage:  ge2img GE_name ECAT_name order [debug]"
	echo " e.g.:  ge2img mayo.GE coss_mayo.v 1"
	echo "  or,   ge2img wisc.pet coss_wisc.v"
	echo " "
	echo "Note: GEMS Export files may have any extension (.ie, .GE)"
	exit
endif

set in = $1
if (! -e $in) then
	echo "$in does not exist"
	exit (1)
endif

set img = $2
if (-e $img) echo "Warning: $img will be replaced."

set order = 0
if ($#argv >= 3) set order = $3

set debug = 0
if ($4 == "debug") set debug = 1

${BINPATH}/ge2img.bin $in $img $order $debug `date` `whoami`

