#!/bin/csh
if ($#argv != 1) then
	echo rung cutoff
	exit
endif
set DIR = /data/petsun21/Test
#gauss $DIR/line2d.v $DIR/line2d_g${1}.v 0.${1}
../peakseek $DIR/line2d_g${1}.v line2d_g${1}_5cm.fit
echo line2d_g${1}_5cm.fit
