#!/bin/csh
# Compute CMRfdg for specified interval, f1-f2:

set f1 = 46
set f2 = 51

# Common parameters

set N = 0
set DIR = /data/wjp/data1/np15/p5356
set model = 0
set dta  = p5356fdg1.dta
set pie  = 4.3621
set gluc = 4.1100
set cbv  = 3.94
set k21  = 2.26167
set k2   = 0.25946
set k3   = 0.23194
set k4   = 0.01042
set lc   = 1.
set uMol_per_mg = 5.55
set k1 = `echo "$cbv * $k21 / 100" | bc -l`

sumimgframes $DIR/p5356fdg1.v p5356fdg$N.v $f1 $f2
set start = `imghdr p5356fdg$N.v | grep Start | cut -f4 -d' '`
set t1 = `echo "$start - 111.433" | bc -l`
set dur = `imghdr p5356fdg$N.v | grep length | cut -f4 -d' '`
echo "5356 $N" >! lst$N
imgmean prm0 lst$N -t 3to23
set cnts = `cat lst$N | cut -f3`
#set k1 = 0.08911
#set cnts = 8280
fdgcalc $cnts $dta $k1 $k2 $k3 $k4 $gluc $t1 $dur $pie

