#!/bin/csh
#	Name:	hdrinfo
#	Date:	Jan-96
#	Author:	Tom Videen
#	Intent:	Read info from hdr file

set BINPATH = /home/npggw/tom/src/hdrinfo
if ($#argv != 1) then
	echo " usage: hdrinfo filename"
	echo "  i.e.: methdr p2000ho1"
	echo "  or    methdr p2000ho1.hdr"
	exit 1
endif

set headersource = $1
set headerroot = `echo ${headersource} | awk -F. '{print $1}'`
set headerfile = ${headersource}

set headerfile	= ${headerroot}.hdr
if (!(-r ${headerfile})) then
	set headerfile	= ${headerroot}.HDR
	if (!(-r ${headerfile})) then
		echo " Error: Header file (${headersource}) does not exist."
		exit
	endif
endif

${BINPATH}/hdrinfo.bin ${headerfile}
