#!/usr/local/bin/perl
# Author:	Tom Videen
# Date:		Oct 2004
# Purpose:	Rename .dcm files in order starting with 00001.dcm
# -----------------------------------------------------
if ($#ARGV != 1) {
	print STDERR "Usage: dcm_renumber <first> <last>\n";
	print STDERR " e.g.: dcm_renumber 129 256\n";
	exit(0);
}

$first = $ARGV[0];
$last = $ARGV[1];
if ($first > $last) {
	print STDERR "Usage: dcm_renumber <first> <last>\n";
	print STDERR " e.g.: dcm_renumber 129 256\n";
	exit(0);
}

foreach $fileno ($first..$last) {
	$new = $new + 1;
	if ($new < 10 ) {
		$prefix = "0000";
	} elsif ($new < 100) {
		$prefix = "000";
	} elsif ($new < 1000) {
		$prefix = "00";
	} elsif ($new < 10000) {
		$prefix = "0";
	}
	$newname = $prefix . $new . ".dcm";
	if ($fileno < 10 ) {
		$prefix = "0000";
	} elsif ($fileno < 100) {
		$prefix = "000";
	} elsif ($fileno < 1000) {
		$prefix = "00";
	} elsif ($fileno < 10000) {
		$prefix = "0";
	} 
	$oldname = $prefix . $fileno . ".dcm";
	`mv $oldname $newname`;
}
exit(0);

