#!/bin/csh
#	Name:	dcmren_000000
#	Date:	Apr 2005
#	Author:	Tom Videen
#	Use:	Rename DICOM images from 000001 to 00001.dcm

if ($#argv != 2) then
	echo "Usage:  dcmren_000000 first last"
	echo " e.g.,  dcmren_000000 2 30"
	exit 1
endif

set first = $1
set last  = $2
set n = $first

while ($n <= $last)
	if ($n < 10 ) then
    	set prefix = "0000"
	else if ($n < 100) then
    	set prefix = "000"
	else if ($n < 1000) then
    	set prefix = "00"
	else if ($n < 10000) then
    	set prefix = "0"
	else 
    	set prefix = ""
	endif
	set old = "0$prefix$n"
	set new = "$prefix$n.dcm"
	mv $old $new
	chmod 664 $new
	@ n++
end
