#!/bin/csh

./Align_Oxygen p5259 1to27
./Align_Oxygen p5272 1to29
./Align_Oxygen p5285 1to29
./Align_Oxygen p5286 1to28
./Align_Oxygen p5290 1to29
./Align_Oxygen p5296 1to28
./Align_Oxygen p5356 1to33

