#!/bin/csh

foreach i (`cat recons`)
cd /data/jsp/primate/focus_220/${i}
if (-d FDOPA/) then
cd FDOPA
rm core
rm gin
echo ${i}_FD_occipital.dat >>! gin
echo ${i}_FD_left_striatum.dat >>! gin
echo ${i}_FD_right_striatum.dat >>! gin

rm jobtac
rm ${i}_FD.tac
echo "/home/usr/joanne/TEMP/JOELP/gentac.tsk <gin >${i}_FD.tac" >>! jobtac
csh jobtac

rm dvr.in
echo 24 94 >>! dvr.in
echo ${i}_FD.tac >>! dvr.in

rm jobdvr
rm dvr.out
echo "/home/usr/joanne/sun24/joelp/dvreiv.tsk <dvr.in >&dvr.out" >>! jobdvr
csh jobdvr

echo ${i} >>! /data/jsp/primate/focus_220/fdopa-bp.txt
cat *.BP >>! /data/jsp/primate/focus_220/fdopa-bp.txt
endif
end
