      SUBROUTINE IMGROTO(FOVMM,MMPPIX,NSLICE,IMAG,MASK,PARAM,ERR)
C     FINDS OPTIMAL TRANSLATION/ROTATION TO ACHIEVE SYMMETRY ABOUT x=0
      REAL*4 FOVMM(3),MMPPIX(3)
      PARAMETER (NPIX=10112)
      INTEGER*2 IMAG(NPIX,NSLICE)
      INTEGER*2 MASK(NPIX,NSLICE)
      REAL*4 PARAM(6)
      PARAMETER (NTERM=6)
      REAL*4 TARAM(NTERM),CURVA(NTERM)
      REAL*4 DARAM(NTERM)/1.8,1.8,2.1,3*0.06981317/
      INTEGER*4 JOFJJ(3)/1,5,6/		! PARAM indices for x=0 symmetery
      REAL*4 COEF(0:2),ARRAY(3,3)
      PARAMETER (NI=7)
      PARAMETER (NPTS=2*NI+1)
      REAL*4 X(-NI:NI),Y(-NI:NI)
      REAL*4 REPORT(-NI:NI,6)
      INTEGER*4 LISTLU/6/
      LOGICAL*4 LITER
      DATA JAXIS/1/
      DATA DEL/8./			! sampling mesh (mm) in virtual image
      DEGPERAD=45./ATAN(1.)
      DO 11 I=1,6
   11 PARAM(I)=0.
      WRITE(LISTLU,101)
  101 FORMAT(6X,'dXmm',6X,'dYmm',6X,'dZmm',5X,'dXrot',5X,'dYrot'
     &,5X,'dZrot','  rmsERROR')
      CALL IMGROTE(FOVMM,MMPPIX,NSLICE,IMAG,MASK,PARAM,DEL,JAXIS,E1)
      WRITE(LISTLU,102)
     &(PARAM(J),J=1,3),(PARAM(J)*DEGPERAD,J=4,6),SQRT(E1)
      NITER=5
   83 LITER=.FALSE.
      DO 81 JJ=1,3
      J=JOFJJ(JJ)
      TARAM(J)=PARAM(J)
      DO 84 I=-NI,NI
      PARAM(J)=TARAM(J)+DARAM(J)*FLOAT(I)/FLOAT(NI)
      CALL IMGROTE(FOVMM,MMPPIX,NSLICE,IMAG,MASK,PARAM,DEL,JAXIS,E1)
C      WRITE(LISTLU,102)
C     &(PARAM(JT),JT=1,3),(PARAM(JT)*DEGPERAD,JT=4,6),SQRT(E1)
      X(I)=FLOAT(I)/FLOAT(NI)
      Y(I)=E1
   84 REPORT(I,J)=E1
      CALL POLFIT(X,Y,NPTS,COEF,ARRAY,3,CHISQR)
      T=.5*COEF(1)/COEF(2)
      IF(COEF(2).LT.0..OR.ABS(T).GT..5)THEN
        write(*,"(' T ',F10.6)")T
        T=SIGN(.5,COEF(1))
        NITER=NITER+1
        write(*,"(' T ',F10.6)")T
      ENDIF
      LITER=LITER.OR.ABS(T).GT.0.01
      CURVA(J)=COEF(2)
   81 PARAM(J)=TARAM(J)-DARAM(J)*T
      CALL IMGROTE(FOVMM,MMPPIX,NSLICE,IMAG,MASK,PARAM,DEL,JAXIS,E1)
      WRITE(LISTLU,102)
     &(PARAM(J),J=1,3),(PARAM(J)*DEGPERAD,J=4,6),SQRT(E1)
  102 FORMAT(7F10.4,F8.4)
      NITER=NITER-1
      IF(LITER.AND.NITER.GT.0)GOTO 83
      WRITE(LISTLU,"(' RMS REPORT')")
      WRITE(LISTLU,102)(DARAM(J),J=1,3),(DARAM(J)*DEGPERAD,J=4,6)
      WRITE(LISTLU,"(6F10.0)")(CURVA(J)/DARAM(J)**2,J=1,3),
     &                        (CURVA(J)/(DARAM(J)*DEGPERAD)**2,J=4,6)
      DO 88 I=-NI,NI
   88 WRITE(LISTLU,"(6F10.4)")(SQRT(REPORT(I,J)),J=1,6)
      WRITE(LISTLU,102)
     &(PARAM(J),J=1,3),(PARAM(J)*DEGPERAD,J=4,6),SQRT(E1)
      ERR=E1
      RETURN
      END
