.TH CLIPANALYZE 1 "13-Feb-95" "Neuro PET Group"

.SH NAME

clipanalyze - sets global min in ANALYZE hdr = 0

.SH SYNOPSIS

clipanalyze <ANALYZE root>

.SH DESCRIPTION

clipanalyze is useful for forcing the global minimum in an Analyze image
to 0, thus avoiding a "feature" in the AIR package which automatically
scales 16-bit data to unsigned integers.  The processing is usually not
what you wish unless the negative values are zeroed first.

Note that clipanalyze does not change the values in the image,
but only in the hdr file.  This is sufficient for AIR and preserves
the data for other programs.

.SH EXAMPLE

clipanalyze p2000ho1

.SH RELATED PROGRAMS

analyze, img2analyze(1), alignpettopet16

.SH AUTHOR

Tom O. Videen
