#!/bin/csh
imgmean ho1.prm ho1.lst
imgmean ho2.prm ho2.lst
imgmean ho3.prm ho3.lst
imgmean ho4.prm ho4.lst
imgmean ho5.prm ho5.lst
imgmean ho6.prm ho6.lst
imgmean oo1.prm oo1.lst
imgmean oo2.prm oo2.lst
imgmean oo3.prm oo3.lst
imgmean oo4.prm oo4.lst
