#!/bin/csh
circle p5017ho1.v 20cm_with_5cm.v

gauss3d 20cm_with_5cm.v 20cm_with_5cm_gauss5mm.img  0.9
gauss3d 20cm_with_5cm.v 20cm_with_5cm_gauss10mm.img 0.45
gauss3d 20cm_with_5cm.v 20cm_with_5cm_gauss15mm.img 0.29

