#!/bin/csh
#
# Process a blood curve file (dta) to create a file of metabolic
# conversion factors (hdr) using defaults values in a modified version
# of metproc.  RCD file (rcd) is a log of processing.
#
# Tom Videen  26-Apr-93
#
set argc = $#argv
if ($argc != 1) then
	echo "Usage: fastproc <scan_id>"
	echo " i.e., fastproc p1000ho1"
	exit
endif

set hdrname = $1.hdr
set dtaname = $1.dta
set rcdname = $1.rcd

if (!(-e ${dtaname})) then
	echo "${dtaname} does not exist"
	exit
endif

if (!(-e fastflow.dat)) then
	echo "fastflow.dat does not exist"
	exit
endif

fastproc.bin ${hdrname} ${dtaname} ${rcdname}
