#!/bin/csh
#   Name:   fit_triangle_1n
#   Date:   Jan-96
#   Author: Tom Videen
#   Use:    Fit lines 3 branches of a triangle in one plane and 
#			3 branches of 1 fiducial N in another plane
#			to derive 5 points of intersection in 3-D space.
 
setenv LM_LICENSE_FILE /usr/local/pkg/idl/license.dat
setenv IDL_DEVICE X
setenv IDL_DIR /usr/local/pkg/idl
setenv IDL_PATH +/usr/local/lib/idl:+/usr/local/pkg/idl/lib:+/usr/local/npg/idl
setenv IDL_STARTUP /usr/local/npg/idl/FIT_TRIANGLE_1N
/usr/bin/X11/xrdb -load $IDL_DIR/Idl
$IDL_DIR/bin/idl
