function make_genhdr

;;sets up structures for 7904 reconstructed image header
;;corrections made to excess
;; Apr. 19 1996



TYPINT=FIX(0)
TYPLON=LONG(0)
TYPFLT=FLOAT(0)






;;***************************************************************************/
;;/*
;;SUITE HEADER
;;*/
;;#define SU_ID 0			/*SUITE ID*/
;;#define SU_UNIQ 4		/*MAKE UNIQUE FLAG*/
;;#define SU_DISKID 6		/*DISK ID*/
;;#define SU_PRODID 7		/*PRODUCT ID*/
;;#define SU_VERSCRE 20		/*GENESIS VERSION OF RECORD*/
;;#define SU_VERSCUR 22		/*GENESIS VERSION OF RECORD*/
;;#define SU_CHECKSUM 24		/*SUITE RECORD CHECKSUM*/
;;#define SU_HDR_LEN 114






SUITEDATA = bytarr(2418)


;TOOLSDATA=BYTARR(2048);


EXAMDATATYPE={                                                       $
EX_SUID:	BYTARR(4),$;		/*SUITE ID FOR THIS EXAM*/
EX_UNIQ:	TYPINT,$;		/*THE MAKE-UNIQUE FLAG*/
EX_DISKID:	TYPINT,$;		/*DISK ID FOR THIS EXAM*/
EX_NO:		TYPINT,$;		/*EXAM NUMBER*/
EX_HOSPNAME:	BYTARR(34),$;		/*HOSPITAL NAME*/
EX_DETECT:	TYPINT,$;		/*DETECTOR TYPE*/
EX_NUMCELLS:	TYPLON,$;		/*NUMBER OF CELLS IN DET*/
EX_ZEROCELL:	TYPLON,$;	/*CELL NUMBER AT THETA*/
EX_CELLSPACE:	TYPLON,$;		/*CELL SPACING*/
EX_SRCTODET:	TYPFLT,$;		/*DISTANCE FROM SOURCE TO DETECTOR*/
EX_SRCTOISO:	TYPFLT,$;		/*DISTANCE FROM SOURCE TO ISO*/
EX_TUBETYP:	TYPINT,$;		/*TUBE TYPE*/
EX_DASTYP:	TYPINT,$;		/*DAS TYPE*/
EX_NUM_DCNK:	TYPINT,$;		/*NUMBER OF DECON KERNALS*/
EX_DCN_LEN:	TYPINT,$;		/*NUMBER OF ELEMENTS IN A DECON KERNAL*/
EX_DCN_DENSITY:	TYPINT,$;	/*DECON KERNAL DENSITY*/
EX_DCN_STEPSIZE:TYPINT,$;	/*DECON KERNAL STEPSIZE*/
EX_DCN_SHIFTCNT:TYPINT,$;	/*DECON KERNAL SHIFT COUNT*/
EX_MAGSTRENGTH:	TYPLON,$;	/*MAGNET STRENGTH (IN GAUSS)*/
EX_PATID:	BYTARR(13),$;		/*PATIENT ID FOR THIS EXAM*/
EX_PATNAME:	BYTARR(25),$;		/*PATIENT NAME*/
EX_PATAGE:	TYPINT,$;		/*PATIENT AGE (YEARS, MONTHS OR DAYS)*/
EX_PATIAN:	TYPINT,$;		/*PATIENT AGE NOTATION*/
EX_PATSEX:	TYPINT,$;		/*PATIENT SEX*/
EX_PATWEIGHT:	TYPFLT,$;	/*PATIENT WEIGHT*/
EX_TRAUMA:	TYPINT,$;		/*TRAUMA FLAG*/
EX_HIST:	BYTARR(61),$;		/*PATIENT HISTORY*/
EX_REQNUM:	BYTARR(13),$;		/*REQUISITION NUMBER*/
EX_DATETIME:	TYPLON,$;		/*EXAM DATE/TIME STAMP*/
EX_REFPHY:	BYTARR(33),$;		/*REFERRING PHYSICIAN*/
EX_DIAGRAD:	BYTARR(33),$;		/*DIAGNOSTICIAN/RADIOLOGIST*/
EX_OP:		TYPLON,$;		/*OPERATOR*/
EX_DESC:	BYTARR(23),$;		/*EXAM DESCRIPTION*/
EX_TYP:		BYTARR(3),$;		/*EXAM TYPE*/
EX_FORMAT:	TYPINT,$;		/*EXAM FORMAT*/
EX_FIRSTAXTIME:	LONARR(2),$;		/*START TIME(SECS) FIRST AXIAL IN EXAM*/
EX_SYSID:	BYTARR(10),$;		/*CREATOR SUITE AND HOST*/
EX_LASTMOD:	TYPLON,$;		/*DATE/TIME OF LAST CHANGE*/ 
EX_PROTOCOLFLAG:TYPINT,$;		/*NON-ZERO INDICATES PROTOCOL EXAM*/
EX_ALLOC_KEY:	BYTARR(14),$;		/*PROCESS THAT ALLOCATED THIS RECORD*/
EX_DELTA_CNT:	TYPLON,$;		/*INDICATES # OF UPDATES TO HEADER*/
EX_VERSCRE:	TYPINT,$;		/*GENESIS VERSION - CREATED*/
EX_VERSCUR:	TYPINT,$;		/*GENESIS VERSION - NOW*/
EX_CHECKSUM:	TYPLON,$;		/*EXAM RECORD CHECKSUM*/
EX_COMPLETE:	TYPLON,$;		/*EXAM COMPLETE FLAG*/
EX_SERIESCT:	TYPLON,$;		/*LAST SERIES NUMBER USED*/
EX_NUMARCH:	TYPLON,$;		/*NUMBER OF SERIES ARCHIVED*/
EX_NUMSERIES:	TYPLON,$;		/*NUMBER OF SERIES EXISTING*/
EX_SERIES:	BYTARR(8),$;		/*SERIES KEYS FOR THIS EXAM*/
EX_NUMUNSER:	TYPLON,$;		/*NUMBER OF UNSTORED SERIES*/
EX_UNSERIES:	BYTARR(8),$;		/*UNSTORED SERIES KEYS FOR THIS EXAM*/
EX_TOARCHCNT:	TYPLON,$;		/*NUMBER OF UNARCHIVED SERIES*/
EX_TOARCHIVE:	BYTARR(8),$;		/*UNARCHIVED SERIES KEYS FOR THIS EXAM*/
EX_PROSPCNT:	TYPLON,$;		/*NUMBER OF PROSPECTIVE/SCOUT SERIES*/
EX_PROSP:	BYTARR(8),$;		/*PROSP./SCOUT SERIES KEYS THIS EXAM*/
EX_MODELNUM:	TYPLON,$;		/*LAST MODEL NUMBER USED*/
EX_MODELCNT:	TYPLON,$;		/*NUMBER OF THREED MODELS*/
EX_MODELS:	BYTARR(8),$;		/*THREED MODEL KEYS FOR EXAM*/
EX_STAT:	TYPINT,$;		/*PATIENT STATUS*/
EX_UNIQUE_SYS_ID:BYTARR(16),$;		/* UNIQUE SYSTEM ID */
EX_SERVICE_ID:	BYTARR(16),$;	/* UNIQUE SERVICE ID */
EX_MOBILE_LOC:	BYTARR(20),$;	/* MOBILE LOCATION LOCATION len ??? */
excess:		BYTARR(534)$;  					:::::::::was 524
}

SERIESDATATYPE={ 							$
SE_SUID: 	BYTARR(4),$;		/*SUITE ID FOR THIS IMAGE*/
SE_UNIQ:	TYPINT,$;		/*THE MAKE-UNIQUE FLAG*/
SE_DISKID:	TYPINT,$;		/*DISK ID FOR THIS SERIES*/
SE_EXNO:	TYPINT,$;		/*EXAM NUMBER*/
SE_NO:		TYPINT,$;		/*SERIES NUMBER*/
SE_DATETIME:	TYPLON,$;		/*ALLOCATION SERIES DATA/TIME STAMP*/
SE_ACTUAL_DT:	TYPLON,$;		/*ACTUAL SERIES DATA/TIME STAMP*/
SE_DESC:	BYTARR(30),$;		/*SERIES DESCRIPTION*/
SE_PR_SYSID:	BYTARR(9),$;		/*PRIMARY RECEIVER SUITE AND HOST*/
SE_PANSYSID:	BYTARR(9),$;		/*ARCHIVER SUITE AND HOST*/
SE_TYP:		TYPINT,$;		/*SERIES TYPE*/
SE_SOURCE:	TYPINT,$;		/*SERIES FROM WHICH PRESCRIBED*/
SE_PLANE:	TYPINT,$;		/*MOST-LIKE PLANE (FOR L/S)*/
SE_SCAN_TYPE:	TYPINT,$;		/*SCOUT OR AXIAL (FOR CT)*/
SE_POSITION:	TYPLON,$;		/*PATIENT POSITION*/
SE_ENTRY:	TYPLON,$;		/*PATIENT ENTRY*/
SE_ANREF:	TYPLON,$;		/*ANATOMICAL REFERENCE*/
SE_LMHOR:	TYPLON,$;		/*HORIZONTAL LANDMARK*/
SE_PRTCL:	BYTARR(26),$;		/*SCAN PROTOCOL NAME*/
SE_CONTRAST:	TYPINT,$;		/*IF > 0 IMAGE USED CONTRAST(L/S)*/
SE_START_RAS:	BYTARR(2),$;		/*RAS LETTER FOR FIRST SCAN LOCATION (L/S)*/
SE_START_LOC:	TYPFLT,$;		/*FIRST SCAN LOCATION (L/S)*/
SE_END_RAS:	BYTARR(2),$;		/*RAS LETTER FOR LAST SCAN LOCATION (L/S)*/
SE_END_LOC:	TYPFLT,$;		/*LAST SCAN LOCATION (L/S)*/
SE_PSEQ:	TYPINT,$;		/*LAST PULSE SEQUENCE USED (L/S)*/
SE_SORTORDER:	TYPINT,$;		/*IMAGE SORT ORDER (L/S)*/
SE_LNDMRKCNT:	TYPLON,$;		/*LANDMARK COUNTER*/
SE_NACQ:	TYPINT,$;		/*NUMBER OF ACQUISITIONS*/
SE_XBASEST:	TYPINT,$;		/*STARTING NUMBER FOR BASELINES*/
SE_XBASEEND:	TYPINT,$;		/*ENDING NUMBER FOR BASELINES*/
SE_XENHST:	TYPINT,$;		/*STARTING NUMBER FOR ENHANCED SCANS*/
SE_XENHEND:	TYPINT,$;		/*ENDING NUMBER FOR ENHANCED SCANS*/
SE_LASTMOD:	TYPLON,$;		/*DATE/TIME OF LAST CHANGE*/
SE_ALLOC_KEY:	BYTARR(14),$;		/*PROCESS THAT ALLOCATED THIS RECORD*/
SE_DELTA_CNT:	TYPLON,$;		/*INDICATES NUMBER OF UPDATES TO HEADER*/
SE_VERSCRE:	TYPINT,$;		/*GENESIS VERSION - CREATED*/
SE_VERSCUR:	TYPINT,$;		/*GENESIS VERSION - NOW*/
SE_PDS_A:	TYPLON,$;		/*PIXELDATA SIZE - AS STORED*/
SE_PDS_C:	TYPLON,$;		/*PIXELDATA SIZE - COMPRESSED*/
SE_PDS_U:	TYPLON,$;		/*PIXELDATA SIZE - UNCOMPRESSED*/
SE_CHECKSUM:	TYPLON,$;		/*SERIES RECORD CHECKSUM*/
SE_COMPLETE:	TYPLON,$;		/*SERIES COMPLETE FLAG*/
SE_NUMARCH:	TYPLON,$;		/*NUMBER OF IMAGES ARCHIVED*/
SE_IMAGECT:	TYPLON,$;		/*LAST IMAGE NUMBER USED*/
SE_NUMIMAGES:	TYPLON,$;		/*NUMBER OF IMAGES EXISTING*/
SE_IMAGES:	BYTARR(8),$;		/*IMAGE KEYS FOR THIS SERIES*/
SE_NUMUNIMG:	TYPLON,$;		/*NUMBER OF UNSTORED IMAGES*/
SE_UNIMAGES:	BYTARR(8),$;		/*UNSTORED IMAGE KEYS FOR THIS SERIES*/
SE_TOARCHCNT:	TYPLON,$;		/*NUMBER OF UNARCHIVED IMAGES*/
SE_TOARCHIVE:	BYTARR(8),$;		/*UNARCHIVED IMAGE KEYS FOR THIS SERIES*/
SE_ECHO1_ALPHA:	TYPFLT,$;		/*ECHO 1 ALPHA VALUE*/
SE_ECHO1_BETA:	TYPFLT,$;		/*ECHO 1 BETA VALUE*/
SE_ECHO1_WINDOW:TYPINT,$;		/*ECHO 1 WINDOW VALUE*/
SE_ECHO1_LEVEL:	TYPINT,$;		/*ECHO 1 LEVEL VALUE*/
SE_ECHO2_ALPHA:	TYPFLT,$;		/*ECHO 2 ALPHA VALUE*/
SE_ECHO2_BETA:	TYPFLT,$;		/*ECHO 2 BETA VALUE*/
SE_ECHO2_WINDOW:TYPINT,$;		/*ECHO 2 WINDOW VALUE*/
SE_ECHO2_LEVEL:	TYPINT,$;		/*ECHO 2 LEVEL VALUE*/
SE_ECHO3_ALPHA:	TYPFLT,$;		/*ECHO 3 ALPHA VALUE*/
SE_ECHO3_BETA:	TYPFLT,$;		/*ECHO 3 BETA VALUE*/
SE_ECHO3_WINDOW:TYPINT,$;		/*ECHO 3 WINDOW VALUE*/
SE_ECHO3_LEVEL:	TYPINT,$;		/*ECHO 3 LEVEL VALUE*/
SE_ECHO4_ALPHA:	TYPFLT,$;		/*ECHO 4 ALPHA VALUE*/
SE_ECHO4_BETA:	TYPFLT,$;		/*ECHO 4 BETA VALUE*/
SE_ECHO4_WINDOW:TYPINT,$;		/*ECHO 4 WINDOW VALUE*/
SE_ECHO4_LEVEL:	TYPINT,$;		/*ECHO 4 LEVEL VALUE*/
SE_ECHO5_ALPHA:	TYPFLT,$;		/*ECHO 5 ALPHA VALUE*/
SE_ECHO5_BETA:	TYPFLT,$;		/*ECHO 5 BETA VALUE*/
SE_ECHO5_WINDOW:TYPINT,$;		/*ECHO 5 WINDOW VALUE*/
SE_ECHO5_LEVEL:	TYPINT,$;		/*ECHO 5 LEVEL VALUE*/
SE_ECHO6_ALPHA:	TYPFLT,$;		/*ECHO 6 ALPHA VALUE*/
SE_ECHO6_BETA:	TYPFLT,$;		/*ECHO 6 BETA VALUE*/
SE_ECHO6_WINDOW:TYPINT,$;		/*ECHO 6 WINDOW VALUE*/
SE_ECHO6_LEVEL:	TYPINT,$;		/*ECHO 6 LEVEL VALUE*/
SE_ECHO7_ALPHA:	TYPFLT,$;		/*ECHO 7 ALPHA VALUE*/
SE_ECHO7_BETA:	TYPFLT,$;		/*ECHO 7 BETA VALUE*/
SE_ECHO7_WINDOW:TYPINT,$;		/*ECHO 7 WINDOW VALUE*/
SE_ECHO7_LEVEL:	TYPINT,$;		/*ECHO 7 LEVEL VALUE*/
SE_ECHO8_ALPHA:	TYPFLT,$;		/*ECHO 8 ALPHA VALUE*/
SE_ECHO8_BETA:	TYPFLT,$;		/*ECHO 8 BETA VALUE*/
SE_ECHO8_WINDOW:TYPINT,$;		/*ECHO 8 WINDOW VALUE*/
SE_ECHO8_LEVEL:	TYPINT,$;		/*ECHO 8 LEVEL VALUE*/
excess:		BYTARR(684)$;			;;;;;;;;was 676
}



;image header
MRIMAGEDATATYPE={ 							$
IM_SUID: 	BYTARR(4),$;		/*SUITE ID FOR THIS IMAGE*/
IM_UNIQ:	TYPINT,$;		/*THE MAKE-UNIQUE FLAG*/
IM_DISKID:	TYPINT,$;		/*DISK ID FOR THIS IMAGE*/
IM_EXNO:	TYPINT,$;		/*EXAM NUMBER FOR THIS IMAGE*/
IM_SENO: 	TYPINT,$;		/*SERIES NUMBER FOR THIS IMAGE*/
IM_NO:   	TYPINT,$;		/*IMAGE NUMBER*/
IM_DATETIME:	TYPLON,$;		/*ALLOCATION IMAGE DATE/TIME STAMP*/
IM_ACTUAL_DT:	TYPLON,$;		/*ACTUAL IMAGE DATE/TIME STAMP*/
IM_SCTIME:	TYPLON,$;		/*DURATION OF SCAN (SECS)*/
IM_SLTHICK:	TYPFLT,$;		/*SLICE THICKNESS (MM)*/
IM_IMATRIX_X:	TYPINT,$;		/*IMAGE MATRIX SIZE - X*/
IM_IMATRIX_Y:	TYPINT,$;		/*IMAGE MATRIX SIZE - Y*/
IM_DFOV:	TYPFLT,$;		/*DISPLAY FIELD OF VIEW - X (MM)*/
IM_DFOV_RECT:	TYPFLT,$;		/*DISPLAY FIELD OF VIEW - Y (MM)*/
IM_DIM_X:	TYPFLT,$;		/*IMAGE DIMENSION - X*/
IM_DIM_Y:	TYPFLT,$;		/*IMAGE DIMENSION - Y*/
IM_PIXSIZE_X:	TYPFLT,$;		/*IMAGE PIXEL SIZE - X*/
IM_PIXSIZE_Y:	TYPFLT,$;		/*IMAGE PIXEL SIZE - Y*/
IM_PDID:	BYTARR(14),$;	/*PIXEL DATA ID*/
IM_CONTRASTIV:	BYTARR(7),$;	/*IV CONTRAST AGENT*/
IM_CONTRASTORAL:BYTARR(27),$;	/*ORAL CONTRAST AGENT*/
IM_CONTMODE:	TYPINT,$;		/*IMAGE CONTRAST MODE*/
IM_SERRX:	TYPINT,$;		/*SERIES FROM WHICH PRESCRIBED*/
IM_IMGRX:	TYPINT,$;		/*IMAGE FROM WHICH PRESCRIBED*/
IM_SCREENFORMAT:TYPINT,$;		/*SCREEN FORMAT(8/16 BIT)*/
IM_PLANE:	TYPINT,$;		/*PLANE TYPE*/
IM_SCANSPACING:	TYPFLT,$;		/*SPACING BETWEEN SCANS (MM?)*/
IM_COMPRESS:	TYPINT,$;		/*IMAGE COMPRESSION TYPE*/
IM_SCOUTTYPE:	BYTARR(2),$;		/*SCOUT TYPE (AP OR LATERAL)*/
IM_LOC_RAS:	BYTARR(2),$;		/*RAS LETTER OF IMAGE LOCATION*/
IM_LOC:		TYPFLT,$;		/*IMAGE LOCATION*/
IM_CTR:		FLTARR(3),$;		/*CENTER COORDS OF PLANE IMAGE, RAS*/ 
IMIM_NORM:	FLTARR(3),$;		/*NORMAL R COORDS, RAS*/
IM_TLHC:	FLTARR(3),$;		/*COORDS OF TOP LEFT HAND CORNER, RAS*/
IM_TRHC:	FLTARR(3),$;		/*COORDS OF TOP RIGHT HAND CORNER,RAS*/
IM_BRHC:	FLTARR(3),$;		/*COORDS OF BOTTOM RIGHT HAND CORNER*/
IM_FORIMGREV:	BYTARR(4),$;		/*FOREIGN IMAGE REVISION*/
IM_TR:		TYPLON,$;		/*PULSE REPETITION TIME(USEC)*/
IM_TI:		TYPLON,$;		/*PULSE INVERSION TIME(USEC)*/
IM_TE:		TYPLON,$;		/*PULSE ECHO TIME(USEC)*/
IM_TE2:		TYPLON,$;		/*SECOND ECHO ECHO (USEC)*/
IM_NUMECHO:	TYPINT,$;		/*NUMBER OF ECHOES*/
IM_ECHONUM:	TYPINT,$;		/*ECHO NUMBER*/
IM_TBLDLTA:	TYPFLT,$;		/*TABLE DELTA*/
IM_NEX:		TYPFLT,$;		/*NUMBER OF EXCITATIONS*/
IM_CONTIG:	TYPINT,$;		/*CONTINUOUS SLICES FLAG*/
IM_HRTRATE:	TYPINT,$;		/*CARDIAC HEART RATE (BPM)*/
IM_TDEL:	TYPLON,$;		/*DELAY TIME AFTER TRIGGER (USEC)*/
IM_SARAVG:	TYPFLT,$;		/*AVERAGE SAR*/
IM_SARPEAK:	TYPFLT,$;		/*PEAK SAR*/
IM_MONSAR:	TYPINT,$;		/*MONITOR SAR FLAG*/ 
IM_TRGWINDOW:	TYPINT,$;		/*TRIGGER WINDOW (% OF R-R INTERVAL)*/
IM_REPTIME:	TYPFLT,$;		/*CARDIAC REPETITION TIME*/
IM_IMGPCYC:	TYPINT,$;		/*IMAGES PER CARDIAC CYCLE*/
IM_XMTGAIN:	TYPINT,$;		/*ACTUAL TRANSMIT GAIN (.1 DB)*/
IM_RCVGAIN1:	TYPINT,$;		/*ACTUAL RECEIVE GAIN ANALOG (.1 DB)*/
IM_RCVGAIN2:	TYPINT,$;		/*ACTUAL RECEIVE GAIN DIGITAL (.1 DB)*/
IM_MR_FLIP:	TYPINT,$;		/*FLIP ANGLE FOR GRASS SCANS (DEG.)*/
IM_MINDAT:	TYPLON,$;		/*MINIMUM DELAY AFTER TRIGGER (USEC)*/
IM_CPHASE:	TYPINT,$;		/*TOTAL CARDIAC PHASE PRESCRIBED*/
IM_SWAPPF:	TYPINT,$;		/*SWAP PHASE/FREQUENCY AXIS*/
IM_PAUSEINT:	TYPINT,$;		/*PAUSE INTERVAL (SLICES)*/
IM_PAUSETIME:	TYPLON,$;		/*PAUSE TIME*/
IM_OBPLANE:	TYPLON,$;		/*OBLIQUE PLANE*/
IM_SLOCFOV:	TYPFLT,$;		/*SLICE OFFSETS ON FREQ AXIS*/
IM_XMTFREQ:	TYPLON,$;		/*CENTER FREQUENCY (0.1 HZ)*/
IM_AUTOXMTFREQ:	TYPLON,$;		/*AUTO CENTER FREQUENCY (0.1 HZ)*/
IM_AUTOXMTGAIN:	TYPINT,$;		/*AUTO TRANSMIT GAIN (0.1 DB)*/
IM_PRESCAN_R1:	TYPINT,$;		/*PRESCAN R1 - ANALOG*/
IM_PRESCAN_R2:	TYPINT,$;		/*PRESCAN R2 - DIGITAL*/
IM_USER_BITMAP:	TYPLON,$;		/*BITMAP DEFINING USER CVS*/
IM_CENFREQ:	TYPINT,$;		/*CENTER FREQUENCY METHOD*/
IM_IMODE:	TYPINT,$;		/*IMAGING MODE*/
IM_IOPT:	TYPLON,$;		/*IMAGING OPTIONS*/
IM_PSEQ:	TYPINT,$;		/*PULSE SEQUENCE*/
IM_PSEQMODE:	TYPINT,$;		/*PULSE SEQUENCE MODE*/
IM_PSDNAME:	BYTARR(34),$;		/*PULSE SEQUENCE NAME*/
IM_PSD_DATETIME:TYPLON,$;		/*PSD CREATION DATE AND TIME*/
IM_PSD_INAME:	BYTARR(14),$;	/*PSD NAME FROM INSIDE PSD*/
IM_CTYP:	TYPINT,$;		/*COIL TYPE*/
IM_CNAME:	BYTARR(18),$;	/*COIL NAME*/
IM_SURFCTYP:	TYPINT,$;		/*SURFACE COIL TYPE*/
IM_SURFCEXT:	TYPINT,$;		/*EXTREMITY COIL FLAG*/
IM_RAWRUNNUM:	TYPLON,$;		/*RAWDATA RUN NUMBER*/
IM_CAL_FLDSTR:	TYPLON,$;		/*CALIBRATED FIELD STR. (X10 UGAUSS)*/
IM_SUPP_TECH:	TYPINT,$;		/*SAT FAT/WATER/NONE*/
IM_VBW:		TYPLON,$;		/*VARIABLE BANDWIDTH (HZ)*/
IM_SLQUANT:	TYPINT,$;		/*NUMBER OF SLICES IN THIS SCAN GROUP*/
IM_GPRE:	TYPINT,$;		/*GRAPHICALLY PRESCRIBED*/
IM_INTR_DEL:	TYPLON,$;		/*INTERIMAGE/INTERLOC DELAY (USEC)*/
IM_USERCVS:	FLTARR(25),$;		/*USER VARIABLES*/
IM_ALLOC_KEY:	BYTARR(14),$;	/**/
IM_LASTMOD:	TYPLON,$;		/*DATE/TIME OF LAST CHANGE*/
IM_VERSCR:	TYPINT,$;		/*GENESIS VERSION - CREATED*/
IM_VERSCUR:	TYPINT,$;		/*GENESIS VERSION - NOW*/
IM_PDS_A:	TYPLON,$;		/*PIXELDATA SIZE - AS STORED*/
IM_PDS_C:	TYPLON,$;		/*PIXELDATA SIZE - COMPRESSED*/
IM_PDS_U:	TYPLON,$;		/*PIXELDATA SIZE - UNCOMPRESSED*/
IM_CHECKSUM:	TYPLON,$;		/*ACQRECON RECORD CHECKSUM*/
IM_ARCHIVED:	TYPLON,$;		/*IMAGE ARCHIVE FLAG*/
IM_COMPLETE:	TYPLON,$;		/*IMAGE COMPLETE FLAG*/
IM_SATBITS:	TYPINT,$;		/*BITMAP OF SAT SELECTIONS*/
IM_SCIC:	TYPINT,$;		/*SURFACE COIL INT. CORRECTION FLAG*/
IM_SATXLOC1:	TYPINT,$;		/*R-SIDE SAT PULSE LOC REL TO LNDMRK*/
IM_SATXLOC2:	TYPINT,$;		/*L-SIDE SAT PULSE LOC REL TO LNDMRK*/
IM_SATYLOC1:	TYPINT,$;		/*A-SIDE SAT PULSE LOC REL TO LNDMRK*/
IM_SATYLOC2:	TYPINT,$;		/*P-SIDE SAT PULSE LOC REL TO LNDMRK*/
IM_SATZLOC1:	TYPINT,$;		/*S-SIDE SAT PULSE LOC REL TO LNDMRK*/
IM_SATZLOC2:	TYPINT,$;		/*I-SIDE SAT PULSE LOC REL TO LNDMRK*/
IM_SATXTHICK:	TYPINT,$;		/*THICKNESS OF X-AXIS SAT PULSE*/
IM_SATYTHICK:	TYPINT,$;		/*THICKNESS OF Y-AXIS SAT PULSE*/
IM_SATZTHICK:	TYPINT,$;		/*THICKNESS OF Z-AXIS SAT PULSE*/
IM_FLAX:	TYPINT,$;		/*PHASE CONTRAST FLOW AXIS*/
IM_VENC:	TYPINT,$;		/*PHASE CONTRAST VELOCITY ENCODING*/
IM_THK_DISCLMR:	TYPINT,$;		/*SLICE THICKNESS*/
IM_PS_FLAG:	TYPINT,$;		/*AUTO/MANUAL PRESCAN FLAG*/
IM_PS_STATUS:	TYPINT,$;		/*BITMAP OF CHANGED VALUES*/
IM_IMAGE_TYPE:	TYPINT,$;		/*MAGNITUDE, PHASE, IMAGINARY,OR REAL*/
IM_VAS_COLLAPSE:	TYPINT, $;		/*COLLAPSE IMAGE*/
excess:		bytarr(434)	}

;
;RDBM_HEADER={							$
;	rec:		RDB_HEADER52_REC,$;
;	per_pass:	RDB_PER_PASS_TAB,$;
;	unlock_raw:	RDB_PER_PASS_TAB,$;
;	data_acq_tab:	RDB_DATA_ACQ_TAB,$;
;	nex_tab:	RDB_NEX_TYPE,$;
;	nex_abort_tab:	RDB_NEX_TYPE $;
;}

;IMAGE_HEADER={							$
;	tool:		TOOLSDATA,$;         /* From toolsdata.h */
;	exam:		EXAMDATATYPE,$;         /* From imagedb.h */
;	series:		SERIESDATATYPE,$;       /* From imagedb.h */
;	image:		MRIMAGEDATATYPE $;        /* From imagedb.h */
;}       
                              






POOL_HEADER={	$


	suite:		SUITEDATA, $  ;			/*     4836  
	exam:		EXAMDATATYPE,$;         /* From imagedb.h 	1024*/	OK NOW
	series:		SERIESDATATYPE,$;       /* From imagedb.h 	1020*/	OK NOW
	image:		MRIMAGEDATATYPE,$;        /* From imagedb.h 	1022*/ OK NOW
	dummy_filler:	TYPINT $;         	/*     2 sparc align */
}                                     ;   /* 39940 total */





return,pool_header

end
