#!/bin/csh
#	Module:	t88mean
#	Date:	07-Oct-93
#	Author:	Tom Videen
#	Use:	Create a stereotaxic-reformatted image to Talairach 1988 atlas brain
#			Uses parameter and imagelist files

if ($#argv != 3) then
	echo "Usage: t88mean prm imglist image"
	echo " i.e.: t88mean my.prm my.lst output.t88"
	exit
endif

set BINPATH = /home/npggw/tom/src/t88mean
set prm = $1
set lst = $2
set smg = $3
set rec = ${smg}.rec
set now = `date`
set today = `date '+%m/%d/%y'`
set uid = `whoami`

if (!(-e ${prm})) then
	echo t88mean": parameter file ${prm} does not exist"
	exit
endif

if (!(-e ${lst})) then
	echo t88mean": imagelist file ${lst} does not exist"
	exit
endif

if (-e ${rec}) then
	rm $rec
endif
echo "rec ${smg} ${now} ${uid}" > ${rec}
echo "t88mean $1 $2 $3" >> ${rec}
ident ${BINPATH}/t88mean.bin | grep t88mean.c >> ${rec}
echo "prm" >> ${rec}
cat ${prm} >> ${rec}
echo "endprm" >> ${rec}
echo "imglst" >> ${rec}
cat ${lst} >> ${rec}
echo "endimglst" >> ${rec}

echo run ${prm} ${lst} ${smg} ${rec} ${now} ${today} ${uid}

echo "endrec" >> ${rec}
