#!/bin/csh
#if (`uname -r` == "5.6") then
  set os = "Solaris"
#else
#  set os = "SunOs"
#endif
echo $os

if ($os == "Solaris") then
#
# SOLARIS 5.4
#============
  echo "NChrplus"
  make -f NChrplus_solaris.make
  echo "copy_imagev7"
  #copy_imagev7.solaris -static
  copy_imagev7.solaris
  echo "get_minmaxv7"
  #get_minmaxv7.solaris -static
  get_minmaxv7.solaris
  echo "convolgaussv7"
  #convolgaussv7.solaris -static
  convolgaussv7.solaris
else
#
# SunOs 4.1.3
#============
  make -f NChrplus_sunos.make
  echo "copy_imagev7"
  copy_imagev7.sunos -static
  echo "get_minmaxv7"
  get_minmaxv7.sunos -static
  echo "convolgaussv7"
  convolgaussv7.sunos -static
endif
