#!/bin/csh
#   Module: idl
#   Date:   Mar-98
#   Author: Tom Videen
#   Use:    Set environmental variables and call idl

setenv IDL_DEVICE X
setenv IDL_DIR /usr/local/pkg/idl
setenv IDL_LIB /usr/local/pkg/idl/lib
setenv LOC_LIB /home/npggw/tom/idl/npg/libimage
setenv LOC_IDL /home/npggw/tom/idl/vidi
setenv NPG_DIR /usr/local/npg/idl
setenv IDL_PATH +/home/npggw/tom/idl/vidi:+/home/npggw/tom/idl/npg/libimage:+/usr/local/pkg/idl/lib:+/usr/local/npg/idl
#setenv IDL_PATH $LOC_IDL+$LOC_LIB+$IDL_LIB+$NPG_DIR
setenv LM_LICENSE_FILE $IDL_DIR/license.dat
/usr/openwin/bin/xrdb -load /usr/local/npg/idl/vidi.xrdb
$IDL_DIR/bin/idl

#setenv IDL_PATH +/usr/local/lib/idl:+/usr/local/pkg/idl/lib:+/home/npggw/tom/idl/vidi/:+/home/npggw/tom/idl/npg:+/usr/local/npg/capp
#setenv IDL_STARTUP $IDL_DIR/idl/idl_startup.pro
#setenv IDL_LIB $IDL_DIR/lib/sun
#setenv CAPP_DIR /usr/local/npg/capp
#/usr/openwin/bin/xrdb -load /usr/local/npg/capp/Idl
