#!/bin/csh
#
# Name:		fastproc
# Date:		26-Apr-93
# Author: Tom Videen
# Intent:	Fast creation of a hdr file for viewing ECAT images as CBF

set argc = $#argv
if ($argc != 3) then
	echo " Usage:   fastflow <subject_id> <scan_id> <scan_start_time>"
	echo " Example: fastflow p2000 ho1 24"
	exit
endif

set crtname = $1$2.crt
set pltname = $1$2.plt
set crvname = $1$2.crv
set dtaname = $1$2.dta
set hdrname = $1$2.hdr
set rcdname = $1$2.rcd
set scanid  = $2
set starttime = $3

if (!(-e ${crtname})) then
	echo " Error: Blood curve file ${crtname} does not exist."
	exit
endif 

if (!(-e ${pltname})) then
	echo " Error: Head curve file ${pltname} does not exist."
	exit
endif 

if (!(-e fastflow.dat)) then
	echo " Error: Fastproc input file fastflow.dat does not exist."
	exit
endif

echo "run crt2crv"
crt2crv ${crtname} ${pltname} ${crvname}

if (!(-e ${crvname})) then
	echo " Error: File ${crvname} was not created."
	exit
endif 

echo "run fastdta"
fastdta.bin ${crvname} ${dtaname} ${scanid} ${starttime}

if (!(-e ${dtaname})) then
	echo " Error: File ${dtaname} was not created."
	exit
endif 

echo "run fastproc"
fastproc.bin ${hdrname} ${dtaname} ${rcdname}
