c $Log: linfit.f,v $
c Revision 1.1  1996/10/29  19:27:43  tom
c Initial revision
c
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C  Subroutine:   LINFIT.FTN
C  Author:	 Tom O. Videen
C  Date:	   12-Jun-87
C  Written for:  METPROC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
	SUBROUTINE LINFIT (A, B, N1, N2, COR)
C
	REAL		A, B, COR
	INTEGER*4	N1, N2

	REAL		XI, YI
	REAL 		SUMX, SUMY, SUMXY, SUMX2, SUMY2, SXY, SXX, SYY
	INTEGER*4	N, I
	CHARACTER*256 RCSHEADER
C
	INCLUDE 'metproc.inc'

	RCSHEADER = "$Id: linfit.f,v 1.1 1996/10/29 19:27:43 tom Exp $"
C
	N = N2 - N1 + 1
	SUMX = 0.0
	SUMY = 0.0
	SUMXY = 0.0
	SUMX2 = 0.0
	SUMY2 = 0.0
	DO 10 I = N1, N2
		XI = TIME(I)
		YI = CORACTIV(I)
		SUMX = SUMX + XI
		SUMY = SUMY + YI
		SUMXY = SUMXY + XI * YI
		SUMX2 = SUMX2 + XI * XI
		SUMY2 = SUMY2 + YI * YI
10	CONTINUE
	SXX = SUMX2 - SUMX * SUMX / N
	SXY = SUMXY - SUMX * SUMY / N
	SYY = SUMY2 - SUMY * SUMY / N
	B = SXY / SXX
	A = (SUMY - B * SUMX) / N
	COR = SXY / SQRT(SXX * SYY)
	RETURN
	END
