.TH SUMDYN40 1 "05-Dec-2001" "Neuroimaging Lab"

.SH NAME
sumdyn40 - sum dynamic image to create 40-sec image

.SH SYNOPSIS
.nf
sumdyn40 path prefix subject tracer scan ext [X Y Z]

.SH DESCRIPTION
Sumdyn40 reads a dynamic PET image. If no reference coordinates
are passed as parameters (for the center of brain) the program
sums all frames of the input image, filters this composite, and
prompts the user to display it with vidi and identify the center
of brain (X,Y,Z). If coordinates are passed (typical if multiple
images are processed), then this step is skipped.

After getting the center-of-brain, sumdyn40 prompts for:

.nf
1) Zero Time
   This is the time of initiation of first data frame.
   For our data, usually frame 2 is started with injection,
   and this time is 0.

.fi
Voistat will be called and a curve of counts vs. frame number plotted.
Note the number of the first frame with counts > background.
Enter "P" to print the curve; then "Return" to continue.

.nf
2) First frame number for 40-sec integration?
   Enter the number of the frame AFTER the first frame above
   background activity. 40-sec scans have always been started
   after the operator sees the rise in background.

3) Last frame number?
   If there are not 19 frames following the first frame,
   you are shown the frame numbers and times and prompted
   for the number of the last frame. (3D acquisitions will
   not have 2-sec frames throughout)

4) Use this range? <y/n>
   The integration time for 20 frames beginning with the one
   selected is shown. If this is OK, enter y and/or Return.
   If not, enter n or N and you will be prompted for both the
   first and last frame numbers.

.SH FILES CREATED
.nf
p5000ho1_g3.v - filtered 40-sec image
p5000ho1.r    - headcurve format for makedta
p5000ho1.cnt  - single column of mean count rate/frame
p5000ho1.reg  - retaining the center-of-brain coordinate 
p5000ho1_f10to29.v - 40-sec image 

.SH EXAMPLES
.nf
sumdyn40 . p 5000 ho 1 v
sumdyn40 . p 5000 ho 1 v 62 66 24
sumdyn40 /data/nnicu/raw p 5000 ho 1 v

.SH AUTHOR
Tom Videen, 2001
