#!/bin/csh
#	Module: rec6ho
#	Author: Tom Videen
#	Date:   Apr-99
#	Use:    Process NRM TRN and all HOs for PETT VI reconstruction

if ($#argv != 2) then
	echo "Usage:  rec6ho pid num_hos"
	echo " e.g.:  recon6 1500 9"
	exit
endif

set PID = $1
set NUM = $2
set OP  = `whoami`
pronorm6 R${PID}NRM $OP
protran6 R${PID}TRN p${PID}tr1 filterg $OP
set i = 1
while ($i <= $NUM)
	recon6 R${PID}HO$i p${PID}ho$i filterg $OP
	@ i++
end
cleanid6 $OP
