.TH AIR 1 "08-Sep-2009" "Neuroimaging Lab"

.SH NAME
.nf
alignlinear (AIR 3.0 automated linear registration both within and across subjects) 
alignmritopet (old AIR 1.0 intermodality registration, no longer distributed) 
alignpettomri (old AIR 1.0 intermodality registration, no longer distributed) 
alignpettopet (old AIR 1.0 intramodality registration, no longer distributed) 
align_warp (AIR 3.0 automated nonlinear registration) 
binarize (converts 8 or 16 bit file to a binary file) 
binarymask (applies a binary mask to a file) 
binarymath (performs binary operations on pairs of binary input files) 
cd_air (changes .air file's target directory) 
cd_warp (changes .warp file's target directory) 
combine_air (combines multiple .air files) 
combine_warp (combines .air and .warp files) 
definecommon_air (finds a good common space for data analysis based on .air files) 
fixheader (corrects header file's voxel sizes) 
gsmooth (Gaussian convolution) 
identify (computes hash value, verifies header and image compatibility) 
invert_air (interconverts .air file's reslice file and standard file) 
layout (creates 2D layout of 3D data) 
magnify (magnifies images using Fourier interpolation) 
makeaheader (creates new header files) 
manualreslice (trial and error registration, creates initialization files) 
mv_air (changes .air file's reslice file) 
mv_warp (changes .warp file's reslice file) 
reconcile_air (reconciles discrepancies between a series of .air files defining all
possible pairwise registrations) 
reorient (rotates file 90 or 180 degrees or creates file's mirror image) 
resize (changes file's matrix size and/or shifts file within matrix) 
reslice (reslices data based on specified .air file) 
reslice_warp (reslices data based on specified .warp file) 
reunite (joins multiple 2D files into a single 3D file) 
scanair (displays contents of .air file) 
scanheader (displays contents of header file) 
scan_warp (displays contenst of .warp file) 
separate (cuts a 3D volume into multiple 2D files) 
setheadermax (changes header file's maximum) 
sizeof (displays C variable sizes) 
softmean (averages files together compensating for missing data) 
zoomer (interpolates file to cubic voxels) 

.SH REFER TO
Complete documentation for AIR programs may be found at:

http://bishopw.loni.ucla.edu/AIR5/indx.html
