.TH AIRDIF1 1 "04-Aug-99" "Neuroimaging Lab"
.SH NAME
airdif1 - compares the difference between 2 air files

.SH SYNOPSIS
airdif a.air b.air mask_image

.SH DESCRIPTION
This program reads 2 air files and computes the vector difference between them
using pixels with values > 0 in the mask_image. This is a version of airdif
which writes an abbreviated output.

The output is a single line the name of the air file and 7 columns of numbers representing:

  airfile  mean x_dist y_dist z_dist x_ang y_ang z_ang.

Distances are in mm and angles in degrees.

The mask image must be in ECAT or PETT VI format.

.SH RELATED PROGRAMS
air(1), airdif(1)

.SH AUTHOR
Tom O. Videen
