.TH AIRDIF 1 "04-Aug-99" "Neuroimaging Lab"
.SH NAME
airdif - compares the difference between 2 air files

.SH SYNOPSIS
airdif a.air b.air [maskimage]

.SH DESCRIPTION
This program reads 2 air files and computes the difference between them.
If a mask image is given, the vector differences between 
all pixels with values > 0 in that image will be computed using the
matrices specified in the two air files and the
average differences in mm will be displayed.

The .air files are created by alignlinear (Roger Woods' AIR package).
Either version 1 and 2 air files may be used.

The mask image must be in ECAT or PETT VI format.

.SH RELATED PROGRAMS
air(1), airdif1(1)

.SH AUTHOR
Tom O. Videen
