.TH AIRMATRIX 1 "Jan-96" "Neuroimaging Lab"

.SH NAME

airmatrix - read the matrix from an AIR file

.SH SYNOPSIS

airmatrix airfile

.SH DESCRIPTION

This program gets the matrix computed by AIR to align 2 images and
writes it.  It is intended as an interface to IDL routines which
use the AIR transformation.

.SH EXAMPLES
.nf
airmatrix mrpet 

.SH RELATED PROGRAMS

air

.SH AUTHOR

Tom O. Videen
