.TH AIRSLICES 1 "12-Jan-98" "Neuroimaging Lab"

.SH NAME

airslices - change number of slices in key for an AIR file

.SH SYNOPSIS

airdif a.air nslices

.SH DESCRIPTION

This program alters an AIR file by changing the number of slices
(zdim) for both the standard and reslice file. It is useful when
a 2-D alignment must be made in 2 portions of a CT image set, e.g.,
when mv_air produces a "matrix size discrepancy" error message.

.SH EXAMPLE
Given a CT image with 50 slices with an offset between plane
30 and 31:

1) Use Analyze to read the image and save as 4 images (Analyze
numbers slices from 1 starting at the bottom of the head):
.nf
	bot = slices 1-30
	top = slices 31-50
	p30 = slice 30
	p31 = slice 31

2) Align p30 and p31 in 2-D (Model 23):
	setanamin p30 0
	setanamin p31 0
	alignlinear p30 p31 p31_to_p30.air -m 23 -p1 256 -t1 1000 -p2 256 -t2 1000

3) Use air file to reslice bot to top:
	airslices p31_to_p30.air 20
	mv_air p31_to_p30.air top
	setanamin top -1
	reslice p31_to_p30.air newtop -n 1 -k -o

4) Concatenate the images and create a new hdr file:
	cat bot.img newtop.img > new.img
	cp original.hdr new.hdr

.SH RELATED PROGRAMS
air(1)

.SH AUTHOR
Tom O. Videen
