.TH AIRXFID 1 "21-Dec-94" "Neuroimaging Lab"

.SH NAME

airxfid - multiplies an AIR matrix times a set of fiducial points

.SH SYNOPSIS

airxfid

.SH DESCRIPTION

This program requests the name of an air file (created by alignpettomri)
and a file of fiducial points which contains coordinates of 6 points
created by fit_fiducials.  It multiples the AIR transformation matrix times
the coordinates to generate the coordinates in the space coresponding to the
mri image to which the pet was aligned.  The new coordinates are written to
a new file, entered in reponse to a prompt.

.SH INPUT/OUTPUT FILE FORMAT

Input and output files of coordinates contain 6 rows and 3 columns of real numbers:

.nf
      68.3834      169.627      82.6594
      36.3891      138.042      80.2525
      47.2675      18.7822      9.61112
      15.8650      19.2003      42.1753
      14.1173      41.6793      11.8339
      10.8586      41.6793      69.2103

.SH RELATED PROGRAMS

fit_fiducials(1), AIR programs (no man pages)

.SH AUTHOR

Tom O. Videen
