.TH ANA 1 "17-Sep-2012" "Neuroimaging Lab"

.SH NAME
ana - programs which create or manipulate Analyze images

.SH DISPLAY PROGRAMS
.nf
analyze_avw	- latest version of Analyze
vidi			- general visualization, editing, VOI tool
vidivoi		- create VOIs editing transverse/coronal views

.SH CONVERSION PROGRAMS
.nf
anafloat2int	- Analyze floating point to integer
anaint2float	- Analyze integer to floating point 
analyze2cicerone - Analyze to Cicerone orientation
analyze2ecat6	- Analyze to ECAT Matrix 6
analyze2img	- Analyze to ECAT Matrix 7
analyze2img8	- 8-bit Analyze to ECAT Matrix 7 (redundant; analyze2img incorporates)
analyze8to16	- 8-bit Analyze to 16-bit Analyze
analyze32to16	- 32-bit integers to 16-bit Analyze
anahdrnew		- create hdr file for binary image
ct2analyze	- SSPLUS to  Analyze
dcm_ct2analyze	- Dicom CT to Analyze
fdf2analyze	- FDF to Analyze
if2analyze	- Interfile to Analyze
img2analyze	- ECAT to Analyze
img2spm		- ECAT to SPM99 (Analyze with different orientation)
img2spmf		- ECAT to SPM99 (floating point)
img2spm5		- ECAT to SPM5 (same orientation as Analyze)
mri2analyze	- Siemens MR to Analyze
mriseq2analyze	- time-sequence of Siemens MR images to Analyze
nii2ana		- NifTi to Analyze
tse2analyze	- Siemens TSE sequence to Analyze
4dfp2ana	- 4dfp files to 16-bit Analyze restoring proper orientation

.SH IMAGE PROCESSING PROGRAMS
.nf
ana2dcrop		- crop 2D (single-plane) image
ana2dflip		- flip 2D image
ana2dgauss	- filter 2D image
ana3dcrop		- crop 3D image (specify start, end pts)
ana3dmask		- zero all pixels outside a volume
ana3dpad		- expand a 3D image
anaabs		- compute absolute value for each pixel
anacrop		- crop 3D image (specify start pt, size)
anadif		- subtract image from another
anadiv		- divide one image by another
anadouble2int	- convert doubles to short integers
anaflip		- flip 3D image (right/left only)
anahdr		- dump full contents of hdr
anahistonrm		- normalize slices of image using histogram peak
anaint2double	- convert short integers to doubles
analocalmean	- compute mean of 2 or more images dividing by local n
analyze_read	- alternative to anahdr (IDL based)
anamask		- mask image with another
anamasklateral	- apply sagittal mask to 3D image
anamaskshrink	- shrink mask by specified pixels
anamaskslc	- zero slices
anamax		- output image is max value of input pixels in 2 images
anamaxpix		- get maximum pixel value (header is usually wrong)
anamean		- compute mean of 2 or more images
anamin		- get the minimum pixel value for 2 or more images
anameanpix	- compute mean pixel value within mask
anamult		- multiply image by a constant
anaorigin		- clears origin in an Analyze hdr to use SPM5 defaults
anapeak		- searches for peaks over a range of planes and fits locations (for lines)
anapeak1	- finds max voxel and finds mean peak location within a 3D volume around it
anapdimg		- compute percent difference image
anarange		- restrict the range of intensities in an image
anaroty		- rotates on y, switching X and Z coordinates
anasub		- subtract constant from an image
anasum		- add 2 images
anasum_nobj	- compute number of images with pixels in object
anasumlateral	- sum sagittal projection of image
anasumplanes	- sum across planes of image (type float only)
anaswapbytes	- fix endian in hdr and img by byte swapping
anavol		- compute number of pixels within specified range
box2d		- apply 2D boxcar filter
centroid		- compute center of mass for voxels above threshold
chkspm5		- check orientation of SPM hdr files
combinepln_ana	- combine single-plane images into single frame
downsize2d	-	resample 2 dimensions of a 3D image
expandor		- set to value all connected pixels <= min OR >= max
invert_t2		- invert pixel intensities in an image
maskand		- set to value all pixels >= min AND <= max
maskelevlines	- set to value any pixel between 2 others < val
maskimg		- mask one image using another
maskor		- set to value all pixels < min OR > max
maskout		- set to value all pixels NOT >= min AND <= max
maxana		- create an image containing maximum pixel value from all input images
mergemasks	- output pixels=0 where any input pixel=0
merge_coronal_planes - merge single-slice coronal files into a 3D volume
separate_coronal_planes - create single-slice files using coronal planes
setanamin		- set min & max in hdr
setanapixsize	- set pixel sizes in header
setpixval		- set to value pixels >= min AND <= max in mask
singlepln_ana	- separate 3D image into single-plane images
sumana		- add 2 or more images (integer or floats)


.SH SEE ALSO
.nf
dcm		- programs for DICOM format
ctima	- programs for Siemens CT files in ima format
mri		- programs for Siemens MR files in ima format

.SH AUTHOR
Tom Videen, 2010

