.TH ANA2DCROP 1 "04-Feb-2000" "Neuroimaging Lab"

.SH NAME
ana2dcrop - crop a 2-D Analyze image

.SH SYNOPSIS
ana2dcrop infile outfile x0 y0 xlen xlen

.SH DESCRIPTION
Reads a 2-D Analyze image and crops it to the size specified
by an initial coordinate [x0, y0] and dimensions
specified by xlen, ylen.

Writes the result to an Analyze-format file.

.SH EXAMPLE
.nf
ana2dcrop p5000scout p5000scout 10 10 100 100

.SH RELATED PROGRAMS
anacrop(1), ana3dcrop(1), ana2flip(1)

.SH AUTHOR
Tom Videen, 2000.

