.TH ANA3DCROP 1 "27-Apr-2000" "Neuroimaging Lab"

.SH NAME
ana3dpad - pad a 3-D Analyze image

.SH SYNOPSIS
ana3dpad input output x y z

.SH DESCRIPTION
Reads an Analyze image and pads it by adding x, y and z
pixels to each side of the volume (i.e., total pixels
added in any dimension is 2*x, 2*y or 2*z).

Writes the result to an Analyze-format file.

.SH EXAMPLE
.nf
ana3dpad p5000mprage p5000mpr 6 6 6

.SH RELATED PROGRAMS
ana3dcrop(1), ana3dmask(1)

.SH AUTHOR
Tom Videen, 2000.

