.TH ANAABS 1 "09-Oct-2002" "Neuroimaging Lab"

.SH NAME
anaabs - compute absolute value of an Analyze image

.SH SYNOPSIS
anaabs input output

.SH DESCRIPTION
This programs compute the absolute value for all pixels in an Analyze image
and writes the result to a new Analyze image file.

.SH EXAMPLE
anaabs p6000mrpndif p6000mrpnadif

.SH RELATED PROGRAMS
img2analyze(1)

.SH AUTHOR
Tom Videen, Oct 2002.

