.TH ANACROP 1 "04-Feb-2000" "Neuroimaging Lab"

.SH NAME
anacrop - crop a 3-D Analyze image

.SH SYNOPSIS
anacrop infile outfile x0 y0 z0 xlen ylen zlen

.SH DESCRIPTION
Reads an Analyze image and crops it to the volume specified
by an initial coordinate [x0, y0, z0] and dimensions
specified by xlen, ylen, zlen. The initial coordinate will be
the center of the new, cropped image.

Writes the result to an Analyze-format file.

See ana3dcrop for same processing using different input.

.SH EXAMPLE
.nf
anacrop p5000mprage p5000mpr 150 150 150 80 80 80

.SH RELATED PROGRAMS
ana3dcrop(1), ana2dcrop(1)

.SH AUTHOR
Tom Videen, 2000.

