.TH ANADIF 1 "08-Feb-99" "Neuroimaging Lab"

.SH NAME
anadif - subtract one Analyze image from another

.SH SYNOPSIS
anadif input1 input2 output

.SH DESCRIPTION
.nf
Computes:
	output = input1 - input2
and writes the result to an Analyze-format file.

.SH EXAMPLE
anadif p5000seg p5000clot p5000tis

.SH RELATED PROGRAMS
anasub(1), anamask(1), img2analyze(1)

.SH AUTHOR
Tom Videen, Feb 1999.

