.TH ANAHISTONRM 1 "Apr 2009" "Neuroimaging Lab"

.SH NAME
anahistonrm - normalize slices of an Analyze image 

.SH SYNOPSIS
.nf
anahistonrm input output value range

value = normalization value (see below)
range = max pixel intensity bin in the histogram

.SH DESCRIPTION
This was written to correct for slice variation in a series of photographs of microtome cuts.
Despite constant lighting and camera settings, changes in the temperature of the tissue
due to added ice caused variations in photo intensity. This routine creates a histogram of
pixel intensity foreach slice, finds the histogram peak, and then identifies the lower and
upper bins of the half-maximum. The input value is divided by the midpoint of the half-maximum 
to determine the scaler, which is then multiplied times all pixel intensities for that slice.

.SH EXAMPLE
anahistonrm db123 db123nrm 150 

.SH AUTHOR
Tom Videen, Apr 2009.

