.TH ANALYZE2ECAT6 1 "22-Oct-98" "Neuroimaging Lab"

.SH NAME

analyze2ecat6 - converts 16-bit ANALYZE files (img & hdr) to an ECAT 6 file

.SH SYNOPSIS

analyze2ecat6 ANALYZE_root ECAT_filename [stdimg frm#]

.SH DESCRIPTION

Only the rootname for the input Analyze file is specified. However,
the complete output ECAT filename (with extension) should be used.

If a standard image and frame number (3rd and 4th parameters) are specified,
the output ECAT file will contain the header information from the standard
image. This is necessary if frame start time and duration are important
as the Analyze file contains none of this information.

analyze2ecat6 reads a pair of  Analyze hdr and img files and creates an ECAT 6
image file.  Images will be re-oriented so that right brain is on the right and
slice 1 is the top of brain.  The output image will be padded or clipped so that
the slices are 128x128.  The number of slices will not be altered.

Effectively, running img2analyze followed by analyze2ecat6 should restore the
original image in ECAT version 6 format with much of the header information
missing, unless a standard image is used to read the info.

.SH EXAMPLES
.nf
analyze2ecat6 rap2000ho1 rp2000ho1.img
analyze2ecat6 rap2000ho1 rp2000ho1.img p2000ho1.img 2

.SH RELATED PROGRAMS

analyze2img(1), analyze, img2analyze(1)

.SH AUTHOR

Tom O. Videen, Oct 1998.
