.TH ANALYZE2IMG_DECAYCOR 1 "04-Aug-2008" "Neuroimaging Lab"
.SH NAME
analyze2img_decaycor - convert ANALYZE to ECAT 7 format

.SH SYNOPSIS
analyze2img_decaycor in out original original_frm#

.SH DESCRIPTION
Converts 8-bit or 16-bit short integer or 32-bit floating point Analyze files.

Only the rootname for the input Analyze file is specified. However,
the complete output ECAT filename (with extension) should be used.

The output ECAT file will contain the header information from the standard
image including start time and decay correction factor.

If stdimg and frm are specified with no 5th parameter, the output image will have the 
same voxel size as the standard image. However, if a 5th parameter (i.e., "v") is
passed in addition, then the output image will have the same voxel size
as the input Analyze image.

analyze2img_decaycor reads a pair of Analyze hdr and img files and creates an ECAT 7
image file.  Images will be re-oriented so that right brain is on the right and
slice 1 is the top of brain.  The output image will be padded or clipped so that
the slices are 128x128.  The number of slices will not be altered.

Effectively, running img2analyze followed by analyze2img_decaycor should restore the
original image in ECAT 7 format with header information preserved.

.SH EXAMPLES
.nf
analyze2img_decaycor rap5000fdg1 rp5000fdg1.v p5000fdg1.v 10

.SH RELATED PROGRAMS
singleframe, merge_dynframes_decaycor, analyze2img, img2analyze

.SH AUTHOR
Tom Videen, 2008.
