.TH ANAMASK 1 "29-Apr-99" "Neuroimaging Lab"

.SH NAME
anamask - mask one Analyze image with another

.SH SYNOPSIS
anamask input mask output threshold [sign]

.SH DESCRIPTION
.nf
If sign is not specified or sign > 0, it computes:
	output = input where mask >= threshold
If sign < 0, it computes:
	output = input where mask <= threshold

Writes the result to an Analyze-format file.

.SH EXAMPLES
.nf
anamask p5000seg p5000clot p5000tis 1
anamask p5000seg p5000seg2 p5000seg3 100 -1

.SH RELATED PROGRAMS
anadif(1), anasub(1), img2analyze(1)

.SH AUTHOR
Tom Videen, Feb 1999.

