.TH ANAMULT 1 "13-Oct-2000" "Neuroimaging Lab"

.SH NAME
anamult - multiply Analyze image by a real number

.SH SYNOPSIS
anamult input output factor

.SH DESCRIPTION
.nf
Computes:
	output = factor * input
and writes the result to an Analyze-format file.

.SH EXAMPLE
anamult p5000mpr1 p5000mpr2 100

.SH RELATED PROGRAMS
anadif(1), anasub(1), anasum(1), anamask(1), img2analyze(1)

.SH AUTHOR
Tom Videen, Apr 2000.

