.TH ANAPDIMG 1 "27-Apr-2000" "Neuroimaging Lab"

.SH NAME
anapdimg - compute percent difference image 

.SH SYNOPSIS
anapdimg image1 image2 output [flag]

.SH DESCRIPTION
Reads 2 Analyze images and computes a percent difference image.
.nf

For flag = 0:  for each pixel
	output = 100 * (image1 - image2) / image2

For flag = 1:  for each pixel
	output = 100 * (image1 - image2) / meanval

.fi
where meanval is the mean value for all non-zero pixels in image2.

Writes the result to an Analyze-format file.

.SH EXAMPLES
.nf
anapdimg p5000mpr2 p5000mpr1 p5000pd1
anapdimg p5000mpr2 p5000mpr1 p5000pd1 1

.SH RELATED PROGRAMS
ana3dcrop(1), ana3dmask(1)

.SH AUTHOR
Tom Videen, 2000.

