.TH ANARANGE 1 "05-May-00" "Neuroimaging Lab"

.SH NAME
anarange - set intensity range limits on Analyze image

.SH SYNOPSIS
anarange image max [min]

.SH DESCRIPTION
.nf
Set all pixels > max to max.
Optionally set all pixels < min to min.

Writes the result to an Analyze-format file.

.SH EXAMPLES
.nf
anarange v1000mpr 1000
anarange v1000mpr 1000 0

.SH AUTHOR
Tom Videen, May 2000.

