.TH ANADIF 1 "02-Jan-2012" "Neuroimaging Lab"

.SH NAME
anaswapbytes - swap bytes in Analyze hdr and img to fix endian

.SH SYNOPSIS
anaswapbytes filename

.SH DESCRIPTION
Adjusts byte order in an Analyze file to correspond to Sun endian.

Swaps byte order in hdr size, dim, datatype, bitpix, pixdim, max, and min as well as all data in img.

If hdr has already been byte-swapped, will not repeat the swap (check the sizeof_hdr is correct).

NOTE: should the image be read but appear incorrect (speckled pixels and values above 32000), you
can reswap the img only using anaswapbytes_img to see if that fixes it.

.SH EXAMPLE
anaswapbytes db999mpr

.SH RELATED PROGRAMS
anaswapbytes_img

.SH AUTHOR
Tom Videen, Dec 2011.

