.TH ANASUB 1 "08-Feb-99" "Neuroimaging Lab"

.SH NAME
anasub - subtract a constant from an Analyze image

.SH SYNOPSIS
anasub rootname constant

.SH DESCRIPTION
This program subtraces a constant from all pixels in
an Analyze-format image. One use is to convert CT images
to pixel intensities in Hounsfield units.

.SH EXAMPLE
anasub p5000ct_n 1020

.SH RELATED PROGRAMS
anadif(1), img2analyze(1)

.SH AUTHOR
Tom Videen, Feb 1999.

