.TH ANASUM 1 "11-Feb-99" "Neuroimaging Lab"

.SH NAME
anasum - add 2 Analyze images

.SH SYNOPSIS
anasum input1 input2 output

.SH DESCRIPTION
.nf
Computes:
	output = input1 + input2
and writes the result to an Analyze-format file.

.SH EXAMPLE
anasum p5000clot1 p5000clot2 p5000clotsum

.SH RELATED PROGRAMS
anadif(1), anasub(1), anamask(1), img2analyze(1)

.SH AUTHOR
Tom Videen, Feb 1999.

