.TH ANAVOl 1 "08-Feb-99" "Neuroimaging Lab"

.SH NAME
anavol - compute volume of pixels between min and max

.SH SYNOPSIS
anavol image min max

.SH DESCRIPTION
This program reads an Analyze file and computes the total
voxels having pixel intensities >= min AND <= max.
The result is written both in number of voxels and in cc
(based on the voxel size in the image hdr).

.SH EXAMPLE
anavol p5000clot 1 200

.SH RELATED PROGRAMS
anadif(1), anasub(1), img2analyze(1)

.SH AUTHOR
Tom Videen, Feb 1999.

