.TH BETAWel 1 "22-Mar-2005" "Neuroimaging Lab"
.SH NAME
betawel - computes beta probe calibration factor
.SH SYNOPSIS
betawel

.SH DESCRIPTION
Betawel runs interactively to compute the calibration factor to
convert beta probe (automated blood sampler) counts to well counter counts.
One input file is required (beta probe .crv file acquired with O-15 or C-11 sample)
and a second will be created if it does not exist (.wel file).
If a .wel file exists, you can read and edit it.

The calibration factor is necessary for processing all 
automated blood sampler files (crt/crv) with betadcv.
This factor is written to the last line of the .wel file.

Note: prior to Feb 25, 2002 (p5999) the crv file had the extension .crt.
The new PC and software installed on this date saves erroneous values for
the first 2 time bins, and these are not used by betawel.

betawel requires and IDL runtime license.

.SH SEE ALSO
betadcv(1)

.SH AUTHOR
Tom Videen, Mar 2005.
