.TH BOX2D 1 "08-Feb-99" "Neuroimaging Lab"

.SH NAME
box2d - filters images using a 2D 3x3 boxcar filter

.SH SYNOPSIS
box2d input output

.SH DESCRIPTION
box2d filters images in Analyze format using a 3x3 boxcar filter
in 2 dimensions only. The original intent was to remove noise
from CT images to facilitate segmentation.

.SH EXAMPLE
box2d p5000ct p5000ct2

.SH AUTHOR

Tom Videen, Feb 1999.
