.TH BUTTERWORTH 1 "20-Dec-95" "Neuroimaging Lab"

.SH NAME
butterworth - filters ECAT 953B or 961 images with a 3D Butterworth
lowpass filter

.SH SYNOPSIS
butterworth infile [outfile] half_freq order

.SH DESCRIPTION
butterworth filters ECAT 953B and 961 images by applying a lowpass Butterworth
filter with the specified order and half-frequency in all 3 dimensions.
For the filtered image to be interpretable, the input image should have
been reconstructed with a ramp filter with cutoff at the Nyquist frequency.

The output filename is optional; if not specified, a common default
name is created.
A recfile will be created.

.SH PARAMETERS
.nf
infile    - input image filename
outfile   - output filename (optional)
half_freq - half frequency (cycles/cm)
order     - order of the filter
.fi

.SH RESOLUTION OF FILTERED 953B IMAGES
For images reconstructed with ramp filter and then processed by butterworth.
The resolutions are measured on a line source in air and represent the central
11 slices of a 31-slice image.  Resolution for 3-D images is greater in the end
slices.  [Round all of these to the nearest 1/2 cm for citations.]
.nf

.ta 0.1i 0.3i 1.3i 1.6i 2.5i 2.8i 3.7i 4.0i
			 2-D Wob	 3-D Sta	 2-D Sta
	Half-Freq	FWHM (mm)	FWHM (mm)	FWHM (mm)
	---------	---------	---------	---------
		none		 5.4		 5.6	 	 5.7
		1.0		 7.7		 7.8		 7.9
		0.9		 8.4		 8.4		 8.6
		0.8		 9.3		 9.2		 9.5
		0.7		10.4		10.5		10.6
		0.6		12.0		12.0		12.2
		0.5		14.2		14.2		14.4
		0.4		17.2		17.0		17.3
		0.3		23.4		23.2		23.6

.bp
.SH EXAMPLES
.nf
butterworth p2000ho1.img 0.7 5
butterworth p2000ho1.img p2000ho1_5b7.img 0.7 5
butterworth p3000ho1.v 0.5 5
.fi

.SH SEE ALSO

gauss(1). 

.SH AUTHOR

Tom O. Videen: Dec 1995

