.TH CHECK_ABSENT_FILES 1 "01-May-2009" "Neuroimaging Lab"
.SH NAME
check_absent_files - Check the existence of a set of files

.SH SYNOPSIS
check_absent_files file1 [file2 file3 ...]

.SH DESCRIPTION
check_absent_files checks for the existence of any filename passed
as an argument and either returns the message
"No existent files" and status=0 or a list of the file(s)
found and status=1.

It is intended to check that files created or overwritten by an operation
are not already present to prevent them being unintentionally removed.

.SH EXAMPLE 
check_absent_files data.lst p5000ho1.v p5000ct.img

.SH RELATED PROGRAMS
checkfiles

.SH AUTHOR
Tom Videen, 2009.
