.TH CHECKDTACAL 1 "29-Oct-96" "Neuroimaging Lab"
.SH NAME
checkdtacal - check calibration in a dta file

.SH SYNOPSIS
.B checkdtacal

.SH DESCRIPTION

This program is intended to be used as a test for the adjustment of the
pieslope in metproc which may be necessary for data in which the
automated blood sampler (ABS) calibration had drifted.
It compares a linear fit the decay-corrected tail of a blood curve collected
with the ABS with a hand-sampled point entered in the dta file.

Each dta file curve must contain one hand-sampled
point entered after the end of the ABS curve
(with at least 1 point with zero activity after the end of the ABS curve).
The program reads a dta file and plots each curve, one at a time.
A linear fit is made to the tail of the blood curve, and the fit line is plotted.
The number of points at the end of the blood curve default is user-selected.

A runtime IDL license is required for this program.

.SH RELATED PROGRAMS

dta(5), metproc(1)

.SH AUTHOR

Tom O. Videen
