.TH CHECKFILES 1 "26-Jul-979 "Neuroimaging Lab"
.SH NAME
checkfiles - Check the existence of a set of files

.SH SYNOPSIS
chklist file1 [file2 file3 ...]

.SH DESCRIPTION
Checkfiles check for the existence of each filename passed
as an argument and either returns the message
"All files found" and status=0 or a list of the file(s)
not found and status=1.

.SH EXAMPLE 
checkfiles data.lst p5000ho1.v p5000ct.img

.SH AUTHOR
Tom Videen, 1999.
