.TH CHKSPM5 1 "24-May-2007" "Neuroimaging Lab"
.SH NAME
chkspm5 - Check the existence of PET image and sxr files 

.SH SYNOPSIS
chkspm5 root

.SH DESCRIPTION
chkspm5 checks all hdr files with names ${root}*.hdr in the current directory
and writes the names of any that are NOT properly oriented (right/left) for SPM5.
It uses multiple calls to anahdr to read the contents of the aux_file field of the Analyze hdr.

.SH EXAMPLE 
chkspm5 p

.SH SEE ALSO
img2spm, img2spm5

.SH AUTHOR
Tom Videen, 2007
