.TH COMBINE_STRIATUM 1 "21 Nov 2001" "Neuroimaging Lab"

.SH NAME
combine_striatum striatum left_ant_put right_ant_put output

.SH DESCRIPTION
This program combines 3 specific object images into a new image.
The 3 input images have voxel values set to define particular objects:

.nf
striatum.img (5 objects)
	1 = left caudate
	2 = right caudate
	3 = left putamen
	4 = right putamen
	5-9 = occipital (all numbers will be mapped to 9)

left_ant_put.img
	3 = left anterior putamen
	(same as striatum.img with left posterior putamen removed)

right_ant_put.img
	4 = right anterior putamen
	(same as striatum.img with right posterior putamen removed)

The new image will contain 7 objects:
	1 = left caudate
	2 = right caudate
	3 = left anterior putamen
	4 = left posterior putamen
	5 = right anterior putamen 
	6 = right posterior putamen
	9 = occipital

.fi
The final object image is used in the script Fdopa_voi to create and
process 9 VOIs defined on an MR image.

.SH EXAMPLE
.nf
combine_striatum p2000_striatum.img p2000_left_ant_put.img\
 p2000_right_ant_put.img p2000_all.img

.SH SEE ALSO
vidivoi(1), fdopa(1)

.SH AUTHOR
Tom Videen, Nov 2001
