.TH CONTACT_DIST 1 "20-Feb-2008" "Neuroimaging Lab"
.SH NAME
contact_dist - compute distance between atlas contact points

.SH SYNOPSIS
contact_dist DBID

.SH DESCRIPTION
.nf
contact_dist reads a pair of left and right .atl files
	dbid_left_contacts.atl
	dbid_right_contacts.atl
.fi
and computes the vector distance in mm between contact #0 and contact #3.
For standard DBS STN electrodes, this should be 6.0 mm.
If it differs by > 1 mm, these files may have been created with an buggy version
of ctpts_to_mai.
Differences of about 0.5 mm reflect the accuracy and precision by which the
electrode track locations were identified in the original CT.

.SH EXAMPLE
.nf
contact_dist db171

  Left  =  6.43
  Right =  5.56

.SH RELATED PROGRAMS
ctpts_to_mai - creates the .atl files from a CT-to-MaiAtlas .air file

.SH AUTHOR
Tom Videen Feb 2008

