.TH CTIMA 1 "09-Dec-2002" "Neuroimaging Lab"

.SH NAME
ctima - programs for Siemens CT files in ima format

.SH CONVERSION PROGRAMS
.nf
change_to_vaxnames - convert names to 00001.ima format
ct2analyze	-	convert to Analyze/IFH format

.SH HEADER INFORMATION
.nf
ctcheck	-	check CT headers for scouts and duplicates
ctdup	-	print filenames of with duplicate table positions
ctheader	-	read CT headers
cttable	-	display table position for CT images

.SH IMAGE MANIPULATION
.nf
cttilt	-	correct for gantry tilt
cttilt_all -	correct for gantry tilt in CT images

.SH SEE ALSO
.nf
dcm		-	programs for DICOM format
mri		-	programs Siemens MR files in ima format

.SH AUTHOR
Tom Videen, 2002

