.TH CTTILT 1 "17-Dec-96" "Neuro PET Group"

.SH NAME
cttilt - reorient CT to correct for gantry tilt
  
.SH SYNOPSIS
.B cttilt inprefix outprefix gantrytilt

.SH DESCRIPTION
This program corrects a CT for gantry tilt after the CT has already been converted to Analyze format (for instance, by running the program "ct2analyze"). 

.SH OPERANDS
.B 
.nf
inprefix - prefix of Analyze-format input files (.img, .hdr),
           e.g., "p5064n"
outprefix - prefix of output files (.img, .hdr, .ifh), 
            e.g., "p5064r"
gantrytilt - gantry tilt in degrees, e.g., "-25"

Note: Use ctheader to determine gantry tilt. For instance:
      ctheader -v 3 3     # look at values for slice 3
.fi
Make sure that you are not looking at a localizer (usually slice 1) when you run ctheader, as the gantry tilt will always be 0 for localizers.

.SH EXAMPLE

Convert an SSPLUS CT to Analyze format without correcting for gantry tilt:
.nf
   ct2analyze 2 50 p5064n -n

.fi
Determine the gantry tilt for the above image:
.nf
   ctheader 1 50     # determine which slice is localizer
   ctheader -v 2 2   # look at gantry tilt for non-localizer
 
.fi
Reorient the above image to correct for gantry tilt:
.nf
   cttilt p5064n p5064r -25

.fi
             
.SH SEE ALSO
ct2analyze(1), ctheader(1)

.SH AUTHOR

Jane Dunford-Shore, 1996.
