.TH CV7TOPETT6 1 "04-Nov-96" "Neuroimaging Lab"
.SH NAME

cv7topett6 - convert ECAT Version 7 images to PETT VI image format

.SH SYNOPSIS

cv7topett6 infile frame [outfile]

.SH DESCRIPTION
This program reads 1 frame from a version 7 ECAT image file and writes 
a PETT VI image file. It thereby permits compatibility with old programs
which only read this format.

Filenames should be specified \fIwithout\fP extensions (.v is assumed for the
input and .img for the output).  If no output filename is specified,
it will have the same root name as the input file.

Note that the binary will convert version 6 ECAT files but the current
script is written for version 7 files

.SH EXAMPLES 
.nf
cv7topett6 p5000ho1 2
cv7topett6 p5000cg1 10 p5000cg10

.SH AUTHOR

Tom Videen, May 1996.
