.TH CV7TO6 1 "12-Aug-96" "Neuroimaging Lab"
.SH NAME

cv7to6 - convert ECAT Version 7 images to ECAT Version 6 image format

.SH SYNOPSIS
.nf
cv7to6 infile [frame]
cv7to6 infile outfile frame
.fi

.SH DESCRIPTION
This program reads 1 frame from a version 7 ECAT image file and writes 
a version 6 ECAT VI image file. It thereby permits compatibility with programs
which only read this older format.

If the program is called with either 1 or 2 parameters ("cv7to6 infile" or
"cv7to6 infile frame"), the filename of the input file should be specified
without an extension. The program will automatically append the extension ".v"
for the input file and use the same root filename with the extension ".img" for
the output file.

If you wish to convert a specified file which does not have the extension ".v",
then you must call the program with 3 parameters ("cv7to6 infile outfile frame").
You must give the complete filename including extension for both the input
and output filenames.

.SH EXAMPLES 
.nf
cv7to6 p5000ho1
cv7to6 p5000cg1 10
cv7to6 p5000mean.t88 p5000mean.img 1

.SH AUTHOR

Tom Videen, Aug 1996.
