.TH DCM 1 "26-Jul-2010" "Neuroimaging Lab"

.SH NAME
dcm - Programs for manipulating DICOM files

.SH PROGRAMS FOR HANDLING DICOM FILES
.nf
dcm2analyze         - convert to Analyze (for both MR and CT)
dcmpet_rename		- rename Biograph PET/CT files to n00001.dcm
dcmpet2img		- convert Biograph PET/CT to Matrix 7 (ECAT)
dcmexist         	- check existence of file by number
dcm_anon        	- anonymizes single DICOM files 
dcm_ctheader        - dump contents of CT header
dcm_dump_element    - get single element in header
dcm_dump_file       - dump entire contents of header
dcm_move            - move .dcm files to another path by number
dcm_mrisort         - rename and move .dcm files from number subdirectories under patient/mri
dcm_mrsort          - rename and move .dcm files from number subdirectories to Raw by number
dcm_mrsort1         - version for sequences that all begin with file# 1 (skips ep2d scans)
dcm_mrsort2         - version for sequences that all begin with file# 1
dcm_order           - display slice order
dcm_rename          - rename to nnnnn.dcm (typically run first)
dcm_renum           - renumber images to begin with any number
dcm_renumber        - renumber images to begin with 00001.dcm
dcm_reorder         - renumber in slice order and eliminate gaps
dcm_reorder_echo	- reorder by echo number
dcm_reorder_image	- reorder by relative image number (0008 0013)
dcm_reorder_time	- reorder by acquisition series time
dcm_reorder_ep   	- reorder EP dual-acquisition
dcm_reorder_tse2d   - reorder dual-echo TSE 2D sequences
dcm_reorder_tse3d   - reorder TSE 3D sequences
dcm_reverse_reorder - reverse slice sequence order
dcm_series_reorder  - reorder by series type
dcm_slice_reorder   - reorder by slice number
dcm_slice_spacing   - computes mean slice spacing over a range of slices
dcmdiff             - display differences between 2 headers (00123.dcm) 
dcminfo             - display select info from header
dcmren              - rename files like 123 to 00123.dcm
dcmren_000000       - rename files like 000123 to 00123.dcm
dcmren_00000000     - rename files like 00000123 to 00123.dcm
dcmscans            - summarize scan types (creates Scans.lst)
dcmscans_summary	- abbreviated Scans.lst (creates Summary.lst)
dcmtilt             - get gantry tilt
dcmtime			- get difference in acquisition times

.NOTES
Some commands require user write permission even though the file is not modified. The
problem lies in the ERL routine dcm_dump_element.

.SH WINDOWS Programs for Viewing and Conversion
.nf
ezDicom	- viewer (www.cabiatl.com/mricro/ezdicom/index.html)
MRIcroN	- viewer (www.cabiatl.com/mricro/mricon/install.html)
dcm2niiGUI - converter (www.cabiatl.com/mricro/mricon/install.html)
MRIConvert - convert (lcni.uoregon.edu/~jolinda/MRIConvert)

.SH SEE ALSO
.nf
dicom for DICOM/PACS format
mri for programs for Siemens MR in ima format
ctima for programs for Siemens CT in ima format

.SH AUTHOR
Tom Videen, 2010

