.TH DCM_CT2ANALYZE 1 "06-Dec-2002" "Neuroimaging Lab"

.SH NAME
dcm_ct2analyze - Converts CT images from DICOM to Analyze and Interfile format (img, hdr,
and ifh files).

.SH SYNOPSIS
dcm_ct2analyze <first> <last> <output_root> [-n] [-debug]

Using "-n" will turn off correction for gantry tilt.
(Use this for segmentation for partial volume correction).

.SH DESCRIPTION
dcm_ct2analyze reads multiple, sequential CT image files in DICOM format, reorients them to the 3D
ordering expected by Analyze and writes a single image file comprising all slices
plus an Analyze header file (.hdr) and an Interfile Format header file (.ifh).  It does not
change the input data except for reorientation; specifically, it does not
generate voxels with uniform, cubic dimensions.

Input DICOM files must be named with a 5 digit  number  followed
by the extension .dcm; i.e., "00001.dcm". The program
"dcm_rename" converts Siemens DICOM filenames to names with this format.

The Analyze orientation will match labels within Analyze.  Note that Analyze thinks in
radiological orientation and displays right-on-left (viewing the body from the feet).

Use dcm_ctheader to determine the appropriate file numbers.

.SH NOTE
Use dcm2analyze for MR DICOM files!

.SH EXAMPLES
.nf
dcm_ct2analyze 2 47 p2134 -n     # no correction for gantry tilt
dcm_ct2analyze 3 3 p4567         # correction for gantry tilt

.SH RELATED PROGRAMS
.nf
dcm for programs for DICOM format
interfile(5)

.SH AUTHOR
Tom Videen

