.TH DCM_SERIES_REORDER 1 "06-Dec-2002" "Neuroimaging Lab"

.SH NAME
dcm_series_reorder - reorders DICOM scans by relative image number

.SH SYNOPSIS
dcm_series_reorder first last

.SH DESCRIPTION
dcm_series_reorder renumbers the scans in the order in which they were
originally acquired. It is useful to undo reordering of TSE sequences
after they have been combined with dcm_slice_reorder.

The filenames must be a 5 digit number followed
by the extension .dcm; i.e., "00001.dcm". 

This perl script calls the program dcm_dump_element from the ERL DICOM package.

.SH EXAMPLES
dcm_series_reorder 1 299

.SH RELATED PROGRAMS
dcm for programs for DICOM format

.SH AUTHOR
Tom Videen
