.TH DCM_SLICE_REORDER 1 "06-Dec-2002" "Neuroimaging Lab"

.SH NAME
dcm_slice_reorder - reorders DICOM scans by slice position

.SH SYNOPSIS
dcm_slice_reorder first last

.SH DESCRIPTION
dcm_slice_reorder renumbers the scans between first and last so slice
positions run from low to high continuously. It is useful 
when combining two TSE sequences.

The filenames must be a 5 digit number followed
by the extension .dcm; i.e., "00001.dcm". 

This perl script calls the program dcm_dump_element from the ERL DICOM package.

.SH EXAMPLES
dcm_slice_reorder 4 131

.SH RELATED PROGRAMS
dcm for programs for DICOM format

.SH AUTHOR
Tom Videen
