.TH DCM_DUMP_FILE 1 "26-Feb-2003" "Neuroimaging Lab"

.SH NAME
dcm_dump_file - dump contents of a DICOM file header

.SH SYNOPSIS
.nf
dcm_dump_file [-b] [-e] [-g] [-t] [-v] [-z] filename

-b	read input in big-endian format
-e	exit on file open error
-g	remove group length elements as file is read
-t	read as part 10 file
-v	verbose mode
-z	perform format conversion (verification) on data

.SH DESCRIPTION
dcm_dump_file reads DICOM file headers and displays 
the contents, including:
.nf
	DICOM Tag (group and element number)
	data value length
	short English description
	some or all of the data for each tag

.fi
Some files require the "-t" flag and others require its
absence. If you get lots of errors, try the opposite.

.nf
For complete documentation, see:
	http://wuerlim.wustl.edu/DICOM/ctn-docs/utilities.pdf

.SH EXAMPLES
.nf
dcm_dump_file -t 00012.dcm
dcm_dump_file .MR..2.1.2001.8.21.14.30.40.203000.660978.IMA

.SH RELATED PROGRAMS
dcm for programs for DICOM format

.SH AUTHOR
.nf
Steve Moore
Electronic Radiology Laboratory
http://wuerlim.wustl.edu/DICOM/ctn.html
ftp.erl.wustl.edu
