.TH DCM_RENAME 1 "06-Dec-2002" "Neuroimaging Lab"

.SH NAME
dcm_rename - rename DICOM scans to nnnnn.dcm

.SH SYNOPSIS
dcm_rename root

.SH DESCRIPTION
dcm_rename renames all DICOM files beginning with the specified root.
The new filenames are a 5 digit number followed
by the extension .dcm; i.e., "00001.dcm". The ordering of the numbers
corresponds to the ordering of scan times read from the file headers.

The new file numbers are assigned to the original filenames after
alphabetic sorting of the names. For filenames beginning with MR or
.MR this will be incorrect and those files must be reordered for each
sequence using dcm_slice_reorder.

The rename commands are saved in the file dcm_rename.log.

This perl script calls the program dcm_dump_element from the ERL DICOM package.

.SH EXAMPLES
.nf
dcm_rename 1.
dcm_rename MR

.SH RELATED PROGRAMS
dcm for programs for DICOM format

.SH AUTHOR
Jane Dunford-Shore
