.TH DCM_RENUM 1 "30-May-2006" "Neuroimaging Lab"

.SH NAME
dcm_renum - renumber DICOM scans 

.SH SYNOPSIS
dcm_renum first last new_first

.SH DESCRIPTION
dcm_renum renames sequential DICOM files with 5-digit filenames, e.g., 00001.dcm.
It is intended to be used to


.SH EXAMPLES
.nf
dcm_renum 1 30 3
	(renumbers 00001.dcm-00030.dcm to 00003.dcm-00033.dcm

dcm_renum 10 30 1
	(renumbers 00010.dcm-00030.dcm to 00001.dcm-00020.dcm

.SH RELATED PROGRAMS
dcm for programs for DICOM format

.SH AUTHOR
Tom Videen, 2006.
