.TH DCM_DUMP_ELEMENT 1 "25-Feb-2003" "Neuroimaging Lab"

.SH NAME
dcm_dump_element - dump one element from a DICOM file header

.SH SYNOPSIS
.nf
dcm_dump_element [-b] [-t] [-v] group element filein fileout

-b	read input in big-endian format
-t	read in DICOM Part 10 format
-v	verbose mode

.SH DESCRIPTION
dcm_dump_element reads one element from a DICOM file and writes
the date to a file.

Some files require the "-t" flag and others require its
absence. If you get lots of errors, try the opposite.

.nf
For complete documentation, see:
    http://wuerlim.wustl.edu/DICOM/ctn-docs/utilities.pdf

.SH EXAMPLE
dcm_dump_element -t 00012.dcm 0008 0032 00001.dcm tmp

.SH RELATED PROGRAMS
dcm for programs for DICOM format

.SH AUTHOR
.nf
Steve Moore
Electronic Radiology Laboratory
http://wuerlim.wustl.edu/DICOM/ctn.html
ftp.erl.wustl.edu
