.TH DCM_REORDER 1 "06-Dec-2002" "Neuroimaging Lab"

.SH NAME
dcm_reorder - renumbers DICOM filenames to eliminate gaps

.SH SYNOPSIS
dcm_reorder first last

.SH DESCRIPTION
dcm_reorder renumbers the scans between first and last so that
the sequence is continuous. I.e., if a slice number is missing,
all files following it are moved up a number. It is useful when
there is a duplicate slice in a series (which often happens with CT)
or when combining two TSE sequences.

The filenames must be a 5 digit number followed
by the extension .dcm; i.e., "00132.dcm". 

This perl script calls the program dcm_dump_element from the ERL DICOM package.

.SH EXAMPLES
dcm_reorder 4 131

.SH RELATED PROGRAMS
dcm for programs for DICOM format

.SH AUTHOR
Tom Videen
