.TH DCMINFO 1 "25-Oct-2005" "Neuroimaging Lab"

.SH NAME
dcminfo - extracts specified info from a DICOM image

.SH SYNOPSIS
.nf
dcminfo filename <s/p/a/i/r>
dcminfo filename <ID/PAT/ACQ/IMG/REL>

.SH DESCRIPTION
dcminfo writes specified info from a DICOM image header.
If a complete filename is used, it may have any name. 
If a number only is given as the filename, the name must be
a 5 digit number followed by the extension .dcm; i.e., "00123.dcm".

.nf
     s or ID  = Study, scanner, and site information
     p or PAT = Patient information
     a or ACQ = Acquisition sequence information
     i or IMG = Image information
     r or REL = Relative slice position information
          PPS = Scan time

.fi
The keys may be entered in upper or lowercase and may be abbreviated
by using a single letter. DCM filenames in the "00123.dcm" format
may be entered as "123" and both the extension and preceding 0's will
be added.

This script uses the program dcm_dump_element from the ERL DICOM package.

.SH EXAMPLES
.nf
dcminfo 00123.dcm ID
dcminfo 123 ACQ

.SH RELATED PROGRAMS
dcm for programs for DICOM format

.SH AUTHOR
Tom Videen
