.TH DCMPET2IMG 1 "30-Apr-2010" "Neuroimaging Lab"
.SH NAME
dcmpet2img - convert Siemens PET/CT files to Matrix 7 format

.SH SYNOPSIS
dcmpet2img series_number output 

.SH DESCRIPTION
Converts Siemens PET/CT Biograph files to Matrix 7 or ECAT format.

Input files first must be renamed to 6 digit number with extension .dcm (dcmpet2_renam).
The conversion will take all files in a series (denoted by first digit of file name)
and create a single 4-D output file.

The output image has pixels ordered in rows opposite of Siemens/CTI convention but
according to our NPG convention (where we display right-on-right). The ordering is
recognized and handled properly by all NPG software (which recognizes the Comment
string "X:r") but may display images with opposite left/right to what you might expect
should you be using external or Siemens software.

The conversion is critically dependent on common attributes being defined in the DICOM
files and could fail should a different implementation of DICOM fail to used attributes
used in version 2009A of the Siemens images. The DICOM "standard" merely defines
attributes and sets minimal, if any, requirements on which must appear in a image file.

The conversion has had limited testing with dynamic PET emission images (HO, OO, CO)
and the CT acquired for attenuation. 

.SH EXAMPLE
.nf
dcmpet2img 5 pct1000ho1.v

.SH RELATED PROGRAMS
dcmpet2_rename

.SH AUTHOR
Tom Videen, 2010.
