.TH DCMPET_RENAME 1 "22-Feb-2011" "Neuroimaging Lab"

.SH NAME
dcmpet_rename - rename Siemens PET/CT files to nnnnnn.dcm

.SH SYNOPSIS
dcmpet_rename root extension

.SH DESCRIPTION
dcmpet_rename renames all DICOM files beginning with the specified root.
New file names are a 6 digit number followed by the extension .dcm.
.nf

The first digit is the Series Number (attribute 0020 0011).
The following 5 digits are the Image Number (attribute 0020 0013).

The script is run from tcsh as typical dynamic images exceed the number
of files that csh can handle.

Attributes are extracted from DICOM files using dcm_dump_file.
Note that version 3.0.6 of dcm_dump_file does not appear to work.

.SH EXAMPLES
.nf
dcmpet_rename E 

.SH RELATED PROGRAMS
dcmpet2img

.SH AUTHOR
Tom Videen
