.TH DCMSCANS 1 "02-Mar-2004" "Neuroimaging Lab"

.SH NAME
dcmscans - identifies DICOM scans by series number

.SH SYNOPSIS
dcmscans

.SH DESCRIPTION
dcmscans reads all DICOM files in a directory, sorts them by series number,
then writes:
.nf

1) first and last filenames in each series; acquisition date; series time
2) sequence filename and sequence description
3) subject id, study date, orientation, image dimensions,
   and pixel dimensions

This information will be save in a file Scans.lst.

.fi
Input DICOM files must be named with a 5 digit number followed
by the extension .dcm; i.e., "00001.dcm". The program "dcm_rename"
will convert DICOM filenames to names with this format.

.SH EXAMPLE
dcmscans

.SH RELATED PROGRAMS
dcm for programs for DICOM format

.SH AUTHOR
Tom Videen

