.TH DILATE2d 1 "15-Mar-2005" "Neuroimaging Lab"

.SH NAME
dilate2d - 2D dilation performed on image

.SH SYNOPSIS
dilate2d infile outfile iterations

.SH DESCRIPTION
dilate2d reads an image, performs the specified number of dilations 
on the structure defined by pixels > 0, and saves the result in
Interfile format. Unlike the dilation option in vidi, these are done in 2-D
(1 plane at a time). It requires and IDL runtime license.

.SH PARAMETERS
.nf
infile    - input image filename
outfile   - output filename 
iterations - number of times to dilate
.fi

.SH EXAMPLE
.nf
dilate2d p6000infarct1.img p6000infarct2.img 5
.fi

.SH AUTHOR
Tom Videen: Mar 2005
