.TH ENLARGE_PIX 1 "10-Jul-99" "Neuroimaging Lab"

.SH NAME
enlarge_pix - enlarges pixels of an ECAT image

.SH SYNOPSIS
enlarge_pix infile outfile trans_multiplier axial_multiplier

.SH DESCRIPTION
This is a smoothing function which creates a new image in which each
pixel represents the mean of an integral number of pixels of the input
image. The number of pixels to combine in the x- and y-dimensions is
specified by the trans_multiplier and the number of pixels to
combine in the z-dimension is specified by the axial_multiplier.

A recfile will be created.

.SH PARAMETERS
.nf
infile    - input image filename
outfile   - output filename
trans_multiplier - number of pixels to combined in x and y dimensions
axial_multiplier - number of pixels to combined in z-dimension
.fi

.SH EXAMPLES
.nf
enlarge_pix p5000ho1.v p5000ho1a.v 2 1
enlarge_pix p5000ho1.v p5000ho1_6mm.v 3 2  (approx 6-mm voxels)
enlarge_pix p5000ho1.v p5000ho1_10mm.v 5 3 (approx 10-mm voxels)
.fi

.SH SEE ALSO
gauss(1), butterworth(1)

.SH AUTHOR
Tom Videen: Jul 1999
