.TH EXCEL_FDG_VOI 1 "02-Apr-2004" "Neuroimaging Lab"

.SH NAME
excel_fdg_voi - generates text file to import into Excel

.SH SYNOPSIS
excel_fdg_voi id voi output

.SH DESCRIPTION
excel_fdg_voi reads files created by Proc_fdg_vois, extract metabolic values,
and saves them in a text file that is easily imported into Excel.
.nf
Excel commands to import a data file:
   select first PID cell
       Alt-d,d,t
   select datafile.txt
       Alt-m,d
       Return
       s,r,f
   move cursor over Import Data window
       Alt-r,a,o
       Return
       Return

.SH EXAMPLE
excel_fdg_voi 6123 l_caud p6123_fdg_voi.txt

.SH RELATED PROGRAMS
Proc_fdg_vois, metcalc, metcalc_pvc

.SH AUTHOR
Tom Videen

