.TH FDGCALC 1 "28-Dec-2001" "Neuroimaging Lab"

.SH NAME
fdgcalc - compute CMRfdg at time t

.SH SYNOPSIS
.nf
fdgcalc ECATcounts dta k1 k2 k3 k4 glucose framestart framelength pie

.SH DESCRIPTION
.nf
fdgcalc computes CMRfdg at time t given:

	ECATcounts  = raw PET counts (from an image ROI)
	dta         = blood curve 
	k1,k2,k3,k4 = rate constants (1/min)
	glucose     = glucose concentration (micromoles/ml)
	framestart  = start time of frame (sec)
	framelength = frame length (sec)
	pie         = conversion factor

.SH NOTE
If ECATcounts are obtained from imgmean or voistat, be certain you use:

.nf
	processing:  none

in your parameter file.

.SH EXAMPLE
.nf
fdgcalc 25150.11 p5356fdg1.dta 0.08911 0.25946 0.23194 0.01042 4.1100 3600 1200 4.3621

.SH OUTPUT lists all parameters:
.nf
framelength   = 1200.00 sec
pie = 4.362100
tau = 0.000105 1/sec
k1  = 0.089110 ml/g/min
k2  = 0.259460 1/min
k3  = 0.231940 1/min
k4  = 0.010420 1/min
LC  = 1.00
plasma FDG =   4.11 microMoles/ml
frame start time = 3600.00 sec
average frm time = 4181.06 sec
ECAT counts =  25150.1 cnts/pixel/frame
well counts =   8519.1 cnts/ml/sec
CMRfdg =  17.177 uMol/min/100g

.SH AUTHOR
Tom Videen
