.TH FILE_CONVERSION 1 "13-Feb-2002" "Neuroimaging Lab"
.SH SYNOPSIS
Procedures for converting COSS PET images to ECAT format.

.SH ANALYZE (Univ of Wisconsin, LSU)
Images in Analyze format appear in pairs: one file will
have the extension .img and the other will have .hdr.
Convert both the water and oxygen to ECAT (Matrix 7) using:

.nf
.ta 0.3i 0.7i 1.5i
	analyze2img input_ho p5000ho1.v
	analyze2img input_oo p5000oo1.v

.fi
where the input filenames are entered without the extension.

.SH INTERFILE (Univ of Iowa)
Images in Interfile format appear in pairs: one file will
have the extension .img and the other will probably have
the extension .hdr. Convert both the water and oxygen to ECAT (Matrix 7) using:

.nf
	iowa2if input_ho p5000ho1.v
	iowa2if input_oo p5000oo1.v

.fi
where the input filenames are entered without the extension.


.SH DESCRIPTOR (Univ of Texas)
Images in Descriptor format have the extension .des.
Convert both the water and oxygen to ECAT (Matrix 7) using:

.nf
	des2img input_ho p5000ho1.v
	des2img input_oo p5000oo1.v

.fi
where the input filenames are entered without the extension.

.SH GE EXPORT (Mayo, Duke)
Images in GE Export format have the extension .ie.
These must be converted using analyze_avw.

.nf
	analyze_avw
		File->Load input_ho
		File->Save As (select Format=AnalyzeImage 7.5) 

.if
Do the same for the oxygen image. Then exist analyze_avw and

.nf
	analyze2img original_ho p5000ho1.v
	analyze2img original_oo p5000oo1.v

.SH DICOM (Univ of Washington)
Images in DICOM format have the extension .ie.
These must be converted using analyze_avw.

.nf
	analyze_avw
		File->Load input_ho
		File->Save As (select Format=AnalyzeImage 7.5) 

.fi
Do the same for the oxygen image. Exit analyze_avw and

.nf
	analyze2img original_ho p5000ho1.v
	analyze2img original_oo p5000oo1.v

.SH AUTHOR
Tom Videen, 2002.
