.TH FIT_TRIANGLE_N 1 "01-Apr-97" "Neuroimaging Lab"

.SH NAME

fit_triangle_n - reads 6 Analyze images containing the branches of 1 triangle
and 1 fiducial N and computes the coordinates of the intersections of 
the branches

.SH SYNOPSIS

fit_triangle_n

.SH DESCRIPTION

This program requests the rootname for a set of 6 files which contain
the branches of 1 fiducial triangle and 1 N on the monkey chair use for PET and MR studies.
The rootname may be anything, but the program expects the filenames to be the following
(where the root is "mr8"):

.nf
mr8lftriback.img
mr8lftridiag.img
mr8lftritop.img
mr8backndiag.img
mr8backnlf.img
mr8backnrt.img
.fi

The program uses linear regression to fit lines to points defining each of
the fiducials.  Each fiducial is assumed to be in a plane, but there are no
constraints on the angles or distances between any of the branches.

Either 8- or 16-bit images may be read (but not both in one run).
The program runs under IDL.

This program is nearly identical to fit_triangle_1n except that this version
will process ideal data where all points of one or more fiducial lies precisely in a plane.

.SH OUTPUT

Program output is to a file <rootname>.fid which will contain the coordinates
of the 6 points of intersection (in mm).  Example:

.nf
      136.009    0.0363569      31.2111		Z: diagonal+left
      33.0497    -0.717107      100.128		Z: diagonal+right
      177.892      11.7376      86.7079		Triangle: back+top
      175.320      99.9721      80.2110		Triangle: diagonal+top
      169.519      5.60356     -1.79455		Triangle: diagonal+back
.fi

.SH RELATED PROGRAMS

fit_triangle_1n(1), fit_fiducials(1), fid_dif(1), analyze, mri2analyze(1), img2analyze(1)

.SH AUTHOR

Tom O. Videen
