.TH FIT_FIDUCIALS 1 "16-Dec-94" "Neuroimaging Lab"

.SH NAME

fit_fiducials - reads 9 Analyze images containing the branches of 3 fiducial N's
and computes the coordinates of the intersections of each of the branches (6 points)

.SH SYNOPSIS

fit_fiducials

.SH DESCRIPTION

This program requests the rootname for a set of 9 files which contain
the 3 branches of 3 fiducial N's on the monkey chair use for PET and MR studies.
The rootname may be anything, but the program expects the filenames to be the following
(where the root is "mr16"):

.nf
mr16topzbtm.img
mr16topzdiag.img
mr16topztop.img
mr16rtzbtm.img
mr16rtzdiag.img
mr16rtztop.img
mr16backndiag.img
mr16backnlf.img
mr16backnrt.img
.fi

The program uses linear regression to fit lines to points defining each of
the fiducials.  It is constrained so that the end-branches of each N are
parallel and separated by a known distance and the angle of the center branch is known.

The Analyze header is read to determine the dimensions of each input image,
and if this header is incorrect you will get an error something like:

.nf
% READU: End of file encountered. Unit: 100
         File: n16topztop.img
% Execution halted at FIT_FIDUCIAL_N </data/npggw/idl/tom/fit_fiducial_N.pro(  84)> 
.fi

If this happens, you will have to fix the hdr file by either recreating
the Analyze images or by using the Header Edit function within Analyze.

.SH OUTPUT

Program output is to a file <rootname>.fid which will contain the coordinates
of the 6 points of intersection.  Example:

.nf
      68.3834      169.627      82.6594
      36.3891      138.042      80.2525
      47.2675      18.7822      9.61112
      15.8650      19.2003      42.1753
      14.1173      41.6793      11.8339
      10.8586      41.6793      69.2103
.fi

.SH RELATED PROGRAMS

fid_dif(1), analyze, mri2analyze(1), img2analyze(1)

.SH AUTHOR

Tom O. Videen
