.TH FIXSINO 1 "10-Mar-95" "Neuroimaging Lab"

.SH NAME
.B fixsino 
- This program changes the bytes in sinograms to remove artifacts caused by
disk-to-tape write errors.

.SH SYNOPSIS
\fBfixsino\fP \fIscnfile matrix [-h]\fP 

.SH DESCRIPTION
\fBfixsino\fP  gives the user a histogram of the sinogram file. It
asks the user for a cutoff value ( > 0). Any pixel value with the
absolute pixel value greater than or equal to the cutoff value
is set to the average of its eight neighbors. 

.SH PARAMETERS

.br
.ta 0.1i 1.2i
	\fIscnfile\fP:	sinogram file name. 
.br
	\fImatrix\fP:	matrix = frame,plane,gate,data_type,bed. The 
.br
		full matrix should be specified. The parameters 
.br
		gate, data type, and bed are required. For 
.br
		example, 2,221,1,0,0 is a valid specification, 
.br
		while 2,221 is not.
.br
	\fI-h\fP:	Optional parameter to generate histogram data 
.br
		only. The original sinogram file is not changed 
.br
		if this parameter is specified.
.fi

.SH EXAMPLES
.nf
fixsino p2498ho8.scn 2,221,1,0,0
fixsino p2498ho8.scn 2,221,1,0,0 -h
.fi

.SH SEE ALSO

scantest (1)

.SH AUTHOR

Tom Yang, March, 1995.
