.TH fpattn7 1 "09 Oct 2006" "Neuroimaging Lab"

.SH NAME
fpattn7 - forward project 961 or 962 attenuation correction

.SH SYNOPSIS
fpattn7 attn_image.v old_attn.a new_attn.a

.SH DESCRIPTION
fpattn7 forward projects a transmission image and creates an attenuation file.
This new attenuation file can be copied to exacthr and used
to re-reconstruct emission sinograms from a study.

An old attenuation file is used to extract file header information.

The utility of fpattn7 is in reconstructing all images of a subject
using a common attenuation correction. When two transmission scans
were collected, these can be coregistered, averaged, forward-projected,
and the average used to reconstruct all sinograms for the subject.

The attenuation correction can be coregistered to each emission scan
using the alignment matrix (air file) for the emission images.
By doing this, a difference image created from coregistered emission images
will not have noise due to the attenuation correction.

.SH EXAMPLE
fpattn7 p5000tr1.v p5000tr1.a p5000tr.a

.SH SEE ALSO
sumattn7, fpattn6, sino

.SH AUTHOR
Tom Videen, 2002
