.TH GAUSS3D 1 "29-Jan-98" "Neuroimaging Lab"

.SH NAME
gauss3d - 3D Gaussian filter using IDL

.SH SYNOPSIS
gauss3d infile [outfile] half_freq

.SH DESCRIPTION
gauss3d filters images in the following formats: CTI ver 6 or 7 (ECAT 953B and 961),
Interfile format, Analyze, and PETT VI.
It uses a Gaussian filter with the specified half-frequency in all 3 dimensions.
For the filtered image to be interpretable, the input image should have
been reconstructed with a ramp filter with cutoff at the Nyquist frequency.

The output filename is optional; if not specified, a common default
name is created. 

The output file will be in Interfile format, which
can be converted to most of the other formats. Currently, the output
file is stored as short integers, which means fractional pixels are rounded
and values exceeding 32767 are truncated. 

gauss3d is functionally similar to gauss except that gauss3d
handles more image formats while gauss writes a CTI ver 7 file
(which also uses short integers but contains a scaling factor to
handle larger values and preserve dynamic range).

.SH PARAMETERS
.nf
infile    - input image filename
outfile   - output filename (optional)
half_freq - half frequency (cycles/cm)
.fi
.bp
.SH RESOLUTION OF MR IMAGES 
For images where the resolution is assumed to be equivalent to 1 pixel.
The resolutions were measured on simulated data (a delta function of a single
pixel).
.nf
 
.ta 0.1i 0.3i 1.3i
	Half-Freq	FWHM (mm)
	---------	---------
		1.0		 4.4
		0.9		 4.9
		0.8		 5.5
		0.7		 6.3
		0.6		 7.4
		0.5		 8.8
		0.45	 9.8
		0.44	10.3
		0.4		11.0
		0.3		14.7
		0.29	15.2
		0.285	15.5
		0.25	17.6
		0.2		22.1
		0.1		44

.SH RESOLUTION OF FILTERED 953B IMAGES
For images reconstructed with ramp filter and then processed by gauss3d.
The resolutions were measured on a line source in air and represent the central
11 slices of a 31-slice image.  Resolution for 3-D images is greater in the end
slices.  [Round all of these to the nearest 1/2 cm for citations.]
.nf
 
.ta 0.1i 0.3i 1.3i 1.6i 2.5i 2.8i 3.7i 4.0i
			 2-D Wob	 3-D Sta	 2-D Sta
	Half-Freq	FWHM (mm)	FWHM (mm)	FWHM (mm)
	---------	---------	---------	---------
		none		 5.4         5.6         5.7
		1.0		 7.1         7.3         7.5
		0.9		 7.5         7.6         7.8
		0.8		 7.9         8.1         8.3
		0.7		 8.5         8.7         8.9
		0.6		 9.4         9.5         9.7
		0.5		10.7        10.8        11.0
		0.4		12.7        12.7        13.0
		0.3		16.3        16.1        16.5
		0.2		22.4        22.8        23.3
.bp
.SH RESOLUTION OF FILTERED 961 IMAGES
For images reconstructed with ramp filter and scatter-correction and then processed by gauss3d.
The resolutions were measured on a line source in water and positioned
approximately 1 cm from the center of the aperture. FWHM represents the central
25 slices of a 47-slice image. While resolution for 2-D images is constant through
all 47 slices, Resolution for 3-D images is significantly greater in the end slices
(less than slice 12 or greater than slice 37 for images with no axial smoothing).
.nf
 
.ta 0.1i 0.3i 1.3i 1.6i 2.5i 2.8i 3.7i 4.0i
			 	2-D	 	3-D
	Half-Freq	FWHM (mm)	FWHM (mm)
	---------	---------	---------
		none		 4.3         4.3
		1.0		 6.6         6.6
		0.9		 7.0         6.9
		0.8		 7.5         7.4
		0.7		 8.1         8.1
		0.65		 8.6
		0.6		 9.1         9.0
		0.5		10.4        10.3
		0.4		12.3        12.2
		0.3		15.5        15.6
		0.2		17.9        20.4

.SH EXAMPLES
.nf
gauss3d p2000ho1.img 0.2
gauss3d p2000ho1.img p2000ho1_g2.img 0.2
gauss3d p5000ho1.v 0.2
.fi

.SH SEE ALSO

gauss(1)

.SH AUTHOR

Tom O. Videen: Jan 1998
