.TH GE2IMG 1 "11-Feb-2003" "Neuroimaging Lab"
.SH NAME
ge2img - convert GE export file to ECAT 7 format

.SH SYNOPSIS
ge2img GE_filename ECAT_filename

.SH DESCRIPTION
ge2img reads a GE Export file (.ie) and creates an ECAT Matrix 7 image file.

.SH EXAMPLES
ge2img cs28-001-ho1.ie cs28-001-ho1.v

.SH RELATED PROGRAMS
gehdr, ge2if

.SH AUTHOR
Tom Videen, 2003.
