.TH GE2IF 1 "11-Feb-2003" "Neuroimaging Lab"
.SH NAME
ge2if - convert GE export file to Interfile format

.SH SYNOPSIS
ge2if GE_filename ECAT_filename

.SH DESCRIPTION
ge2if reads a GE Export file (.ie) and creates an Interfile format
image (.ifh and .img files).

.SH EXAMPLES
ge2if cs28-001-ho1.ie cs28-001-ho1.v

.SH RELATED PROGRAMS
gehdr, ge2img, ifh

.SH AUTHOR
Tom Videen, 2003.
