.TH GEHDR 1 "11-Feb-2003" "Neuroimaging Lab"
.SH NAME
gehdr - type header info in a GE export file

.SH SYNOPSIS
gehdr filename

.SH DESCRIPTION
gehdr reads the header fields from a GE export file (.ie)
and writes the contents of all fields.

.nf
GE export files store information in 6 categories:
	patient
	exam
	scan
	frame
	imageset
	image
.fi

The number, field name, and first entry of all of these fields is printed.

.SH EXAMPLE
gehdr cs28-001-ho1

.SH RELATED PROGRAMS
ge2if, ge2img

.SH AUTHOR
Tom Videen, 2003.
