.TH GETSHIFT 1 "24-Apr-2003" "Neuroimaging Lab"

.SH NAME
getshift - compute the shifts applied in a dta file

.SH SYNOPSIS
getshift pid 

.SH DESCRIPTION
This is a shell script compares bloodcurves in a dta file with those
in the corresponding dcv files. The difference in times for the
initial value in the dta file corresponds to the shift entered
when that dta file was created.

.SH EXAMPLE
getshift p6000

.SH SEE ALSO
plotshift(1), makedta(1)

.SH AUTHOR
Tom Videen, Apr 2003

