.TH HEADSTART 1 "18-Nov-98" "Neuroimaging Lab"

.SH NAME
headstart - get visual delay from 961 headcurve

.SH SYNOPSIS
plotcrv filename

.SH DESCRIPTION
This program reads a headcurve (.r) file and returns the difference
between the time of the first sample from frame 3 and the first
sample from frame 2. This gives the visual delay (time from injection
to time of arrival of bolus in the head) used by metproc with a
maximum error of the sample rate of the headcurve.

Note that this differs from the way makedta estimates the visual delay.
Makedta takes the last time in frame 3, subtracts 40 seconds, and rounds
to an integer. Since 961 headcurves stop with the end of the third
frame, the end point is not really the end of the scan and therefore
the time estimated by makedta will, in general, be shorter than estimated
by headstart.

For 961 data, headstart is the best estimate. For 953B data, makedta
is a better estimate as the 953B usually samples head counts irregularly
around the start of a scan and because (currently) no 953B data is collected
in the 3-frame mode used on the 961 (which is essential for headstart).

.SH EXAMPLE
.nf
headstart p5000ho1.r

.SH SEE ALSO
metproc(1)

.SH AUTHOR
Tom Videen, 1997.


