.TH HRTAPEDIR 1 "01-Nov-95" "Neuroimaging Lab"

.SH NAME

hrtapedir - Get list of files on an EXACT HR archive tape

.SH SYNOPSIS

.B hrtapedir <device>

.SH DESCRIPTION

This program writes a listing of all tar files on a tape from a local tape drive (/dev/rst1).  Write-protect the tape before inserting it. The tape is rewound before initiating the listing, but not upon completion (use "mt -f /dev/rst1 offline" to rewind and eject it).  A tone is sounded locally upon completion.

To save a copy of the listing in "mylisting", redirect the output to a file:

	hrtapedir > mylisting

To see the listing while saving it to "mylisting" at the same time:

	hrtapedir | tee mylisting

If the tape device is not /dev/nrst1, then include the optional device name:

	hrtapedir /dev/nrst29 | tee mylisting

Note that the archive tapes from the EXACT HR are typically done in
8505 compressed mode; hence, the tape drive on which you read them must
support this mode.  Typically, the device name for these drives will be
/dev/nrst25 or /dev/nrst29.

.nf
A typical EXACT archive tape will begin with:

>>> TAPE FILE #1
rw-r--r--111/10    356 Oct 24 12:00 1995 /tmp/label.bin
>>> TAPE FILE #2
rw-r--r--111/10    362 Oct 24 12:08 1995 /tmp/study.bin
>>> TAPE FILE #3
(files for 1st study)
...

Normal completion of hrtapedir looks like:
	>>> TAPE FILE #3
	tar: [offset 0]: I/O error
	/dev/nrst1 fsf 1 failed: I/O error
	>>> TAPE FILE #4
	tar: No input
	hrtapedir complete

.SH SEE ALSO

tapedir, hrtar

.SH AUTHOR

Tom O. Videen


