.TH IF2ANALYZE 1 "23-Oct-2008" "Neuroimaging Lab"

.SH NAME
if2analyze - creates an ANALYZE header file (hdr) from
an Interfile header file (ifh)

.SH SYNOPSIS
if2analyze rootname

The program automatically adds the extensions "ifh" and "img" to the input filenames
and "hdr" to the output filename. 

.SH DESCRIPTION
if2analyze reads an Interfile header and uses its information to create
an Analyze header. It also reads the image file and finds the minimum and
maximum values for the Analyze header.

.SH RESTRICTIONS
The program currently expects 3-dimensional images
in short integer format in radiological orientation. If it finds something
else, it creates a header but warns you that it may not behave properly in Analyze.

Standard orientation for Analyze is:
   matrix initial element [1] := right
   matrix initial element [2] := posterior
   matrix initial element [3] := inferior

.SH EXAMPLE
if2analyze atest

.SH RELATED PROGRAMS
analyze_avw (Analyze), ifh(5)

.SH AUTHOR
Tom O. Videen
