.TH IFDYN2IMG 1 "12-Apr-2005" "Neuroimaging Lab"

.SH NAME
ifdyn2img - creates an ECAT 7 file from a dynamic Interfile

.SH SYNOPSIS
if2analyze header image output

.SH DESCRIPTION
ifdyn2img reads an Interfile header and image data file and creates
an ECAT 7 image file. It was written specifically for images to be received
from MGH's PC4096 scanner and will swap bytes in the image if the header
identifies it as littleendian.

.SH RESTRICTIONS
This was written for MGH data and is likely not be generalizable to
other versions of dynamic Interfiles.

.SH EXAMPLE
ifdyn2img test_interfile.hdr test_interfile.img mgh.v

.SH RELATED PROGRAMS
interfile(5)

.SH AUTHOR
Tom Videen
