.TH IMAGE_ 1 "06-Feb-98" "Neuroimaging Lab"

.SH NAME
.nf
image_scale	- either scale an image or compute the global mean
image_subset	- create a image using a selected set of planes
image_sum	- add 2 images with arbitrary scaling factors
quickview	- quick visualization of a pair of images


.SH DESCRIPTION
These are programs intended to handle all local image formats, including:
Interfile, Analyze, CTI versions 6 and 7, and PETT VI. Where an output
file is created, it is always in Interfile format.

.SH EXAMPLES
.nf
image_scale test.img
image_scale test.img scaled.img 0.5
image_subset ct1.img 1 20 ct1_s1to20.img
image_sum mr1.img,1 mr2.img,-1 mrdif.img

.SH RELATED PROGRAMS

ifh(5)

.SH AUTHOR

Tom O. Videen


