.TH IMEAN 1 "30-Jun-1999" "Neuroimaging Lab"
.SH NAME
imean - create composite images from PETT VI or ECAT images without an atlas transformation.
.SH SYNOPSIS
.B imean prm lst filename [-z]

.SH DESCRIPTION
This program reads multiple PET images and combines them into a composite, average output image.
It will perform subtractions for difference images (if specified).  It will process PET images
as metabolic images and create an hdr file (if specified).

Output images will be in the same format as the input file. Pixel dimensions are not changed from the input images.

The following keywords are read from the prm file.  Files can be located in the local directory, a specified directory 'datapath', or /tmp.  Examples are given for each parameter, but all allowed values are given only for those parameters unique to imean.

If imean is run with the "-z" option AND there is a parameter "slices" in the parameter
file, then the output image will be zeroed for all slices outside the specified range.

Weighting factors may be appended to the end of each line in paired imagelists
(but NOT in "single" imagelists).
Without these weights, each image pair is effectively weighted as 1.
The weights may be used to, say, sum 2 pairs from one subject and 1 pair from
another while weighting each subject equally.

Creating sd and n images permits additional processing with ptimage to create t-images.
.nf

# Required parameters for defining input filenames:

species:        p
tracer:         ho
extension:      v
imgfilter:      butterworth 0.5 5

# Parameters required to find an image filename in the archive 

scanner:        953         
acquisition:    wobble      
reconstruction: filtered_backprojection
recfilter:      ramp

# Optional parameters defining the image filename:

datapath:
suffix:

# Required parameters for imean processing:

processing:       none      # cbf, cbv, oef, cmro2, odiv
smg_norm:         1000      # (any real number > 0)
smg_mode:         single    # paired, diff
smg_divisor:      global    # local, none
smg_included:     all       # sampled, n=5

# Optional parameter for imean:

slices:           6to42     # used if and only if '-z'
smg_sdimage:      yes       # default is no
smg_nimage:       yes       # default is no
.fi

If the parameter "datapath" is specified, that will be the first
location searched for all input files.  Files which are created (smg,
rec, etc.) will all appear in your local directory).

.SH Some Sample PRM Files for...

.SH ECAT 961 mean difference 3D image
.nf
species:        p
tracer:         ho
extension:      v
imgfilter:      gauss 0.3
processing:     none
smg_norm:       1000
smg_mode:       paired
smg_divisor:    global
smg_included:   all
smg_sdimage:    yes       # optional (default is no)
smg_nimage:     yes       # optional (default is no)
scanner:        961       # used only if searching archive
acquisition:    3d        # used only if searching archive
reconstruction: fbu       # used only if searching archive
recfilter:      ramp      # used only if searching archive

.SH ECAT 953B mean difference 3D image
.nf
species:        p
tracer:         ho
extension:      img
imgfilter:      butterworth 0.5 5
processing:     none
smg_norm:       1000
smg_mode:       paired
smg_divisor:    global
smg_included:   all
smg_sdimage:    yes       # optional (default is no)
smg_nimage:     yes       # optional (default is no)
scanner:        953                        # used only if searching archive
acquisition:    sta                        # used only if searching archive
reconstruction: 3d_filtered_backprojection # used only if searching archive
recfilter:      ramp                       # used only if searching archive

.SH PETT VI mean difference image
.nf
species:        p
tracer:         ho
imgfilter:      none
processing:     none
smg_norm:       1000
smg_mode:       paired
smg_divisor:    global
smg_included:   all
smg_sdimage:    yes         # optional (default is no)
smg_nimage:     yes         # optional (default is no)
scanner:        pett6                    # used only if searching archive
acquisition:    low_resolution           # used only if searching archive
reconstruction: filtered_backprojection  # used only if searching archive
recfilter:      filterg                  # used only if searching archive

.SH OEF image from realigned images
.nf
species:        rp
tracer:         oo
f-tracer:       ho
v-tracer:       oc
extension:      v
imgfilter:      gauss 0.3
processing:     oef
smg_norm:       1
smg_mode:       single
smg_divisor:    global
smg_included:   all 

# Using an imagelist file of the form
5576    1f1v1   1.0

.SH CMRO2 difference image from realigned images
.nf
species:        rp
tracer:         oo
f-tracer:       ho
v-tracer:       oc
extension:      v
imgfilter:      gauss 0.3
processing:     cmro2
smg_norm:       1
smg_mode:       paired
smg_divisor:    global
smg_included:   all 

# Using an imagelist file of the form
5576    2f2v2  1.0  1f1v1  1.0

.SH SEE ALSO
chklist(1), imgmean(1), ptimage(1), prm(5), imagelist(5)

.SH AUTHOR

Tom O. Videen: 1994-9.
