.TH IMG2SPMF 1 "02-Jul-2007" "Neuroimaging Lab"

.SH NAME
img2spmf - convert ECAT image files to ANALYZE floating-point format

.SH SYNOPSIS
img2spmf <PET filename> <ANALYZE root>

The complete PET filename must be specified, but only the rootname for the Analyze file.
The program will automatically add the extensions "img" and "hdr" to the output files.

.SH DESCRIPTION
img2spm reads any PET image handled by our library routines (PETT VI and ECAT)
reorients them to the 3D ordering expected by SPM99 and creates .img and .hdr files.

This program differs from img2analyze in that the left-right orientation is reversed.
It differs from img2spm in that the output file contains real numbers instead of
integers.

Beginning with SPM5 the standard Analyze orientation gives the correct
left/right orientation and img2spm creates images that appear reversed in SPM5.
img2spm has NOT been changed to avoid confusion with previous data sets in SPM format.

Information in the hdr file created by either img2spmf
may be viewed with spmhdr.

.SH EXAMPLE
img2spm p5000ho1.v ap5000ho1

.SH RELATED PROGRAMS
img2spm, img2spm5, img2analyze, spm2img, spmhdr, setz0, anaflip

.SH AUTHOR
Tom Videen, 2007.
