.TH IMG2SPM5 1 "24-May-2007" "Neuroimaging Lab"

.SH NAME
img2spm5 - convert ECAT image files to SPM5 format

.SH SYNOPSIS
img2spm5 <PET filename> <SPM root>

The complete PET filename must be specified, but only the rootname is necessary for the SPM file.
The program will automatically add the extensions "img" and "hdr" to the output files.

.SH DESCRIPTION
img2spm5 reads any PET image handled by our library routines (PETT VI and ECAT),
reorients them to the 3D ordering expected by SPM5 and creates .img and .hdr files.

This program differs from img2spm in that the left-right orientation is maintained.

The output hdr file will have "SPM5 orientation" written to the field aux_file.

If the PET image has the atlas z0 value set (see setz0), then img2spm5
will set the atlas z-origin for SPM (equal to number of planes + 1 - z0).
The xy-origin = [64, 65].
Information in the hdr file created by either img2spm5 or SPM
may be viewed with spmhdr or anahdr.

.SH EXAMPLE
img2spm5 p6000ho1.t88 ap6000ho1

.SH RELATED PROGRAMS
img2spm, img2spmf, chkspm5, img2analyze, spm2img, spmhdr, setz0, anaflip

.SH AUTHOR
Tom Videen, 2007.
