.TH IMG2SPM 1 "22-Jan-2007" "Neuroimaging Lab"

.SH NAME
img2spm - convert ECAT or PETT image files to ANALYZE format

.SH SYNOPSIS
img2spm <PET filename> <ANALYZE root>

The complete PET filename must be specified, but only the rootname for the Analyze file.
The program will automatically add the extensions "img" and "hdr" to the output files.

.SH DESCRIPTION
img2spm reads any PET image handled by our library routines (PETT VI and ECAT)
reorients them to the 3D ordering expected by SPM99 and creates .img and .hdr files.

This program differs from img2analyze in that the left-right orientation is reversed.

Beginning with SPM5 the standard Analyze orientation gives the correct
left/right orientation and img2spm creates images that appear reversed in SPM5.
img2spm has NOT been changed to avoid confusion with previous data sets in SPM format.

If the PET image has the atlas z0 value set (see setz0), then img2spm
will set the atlas z-origin for SPM (equal to number of planes + 1 - z0).
The xy-origin = [64, 65].
Information in the hdr file created by either img2spm or SPM
may be viewed with spmhdr.

.SH EXAMPLE
img2spm p5000ho1.v ap5000ho1

.SH RELATED PROGRAMS
img2spmf, img2analyze, spm2img, spmhdr, setz0, anaflip

.SH AUTHOR
Tom Videen, 1998.
