.TH IMG2IF 1 "04-May-2006" "Neuroimaging Lab"

.SH NAME
img2if - converts PET image files (ECAT or PETT VI format) to Interfile format (img & ifh)

.SH SYNOPSIS
img2if <PET filename> <Interfile root>

The complete PET filename must be specified, but only the rootname for the output. The program will automatically add the extensions "img" and "ifh" to the output files.

.SH DESCRIPTION
img2if reads any PET image handled by our library routines (PETT VI and ECAT)
and creates 2 output files: img and ifh. The output image will be floating point. 
While dynamic images can be converted, the Interfile keys will be non-standard.

If the input image has the extension img, the output root must differ from the input root.

.SH EXAMPLE
img2if img2if p5000ho1.v p5000ho1

.SH RELATED PROGRAMS
ifh(5)

.SH AUTHOR
Tom O. Videen
