.TH IMGAVG 1 "09-May-2003" "Neuroimaging Lab"

.SH NAME
imgavg - compute mean of 2 images

.SH SYNOPSIS
imgavg img1 img2 out

.SH DESCRIPTION
This program creates an image comprising the mean voxel value
of 2 images whereever both images have a non-zero value or
the full value of either one of the images whereever the voxel
value of the other is zero.

The program was originally intended to generate mean attenuation
images prior to forward-projecting a mean attenuation correction.

.SH EXAMPLE
imgavg rp5000tr1.v rp5000tr2.v rp5000tr.v

.SH RELATED PROGRAMS
imgsum(1), imgdiv(1), sumimg(1), sumimgplanes(1), sumimgframes(1)

.SH AUTHOR
Tom O. Videen, 2003.


