.TH IMGCNTS 1 "21-Jun-2005" "Neuroimaging Lab"

.SH NAME
imgcnts - get total counts from ECAT image files

.SH SYNOPSIS
imgcnts filename [frame]

.SH DESCRIPTION
imgcnts reads images frames from a PET file and writes a listing
of frame number and total counts. If a frame number is specified,
that single frame is read and reported. If no frame number is specified
or frame=0, all frames are read and reported.

.SH EXAMPLE 
.nf
imgcnts m1004dt1.v
------------------------------------------------------------------
Frm =  1  Total counts = 3.360746
Frm =  2  Total counts = 5.615082
Frm =  3  Total counts = 5.783625
Frm =  4  Total counts = 5.760362
         ...
Frm = 29  Total counts = 0.048281
Frm = 30  Total counts = 0.031908

.fi
For most of our 961 PET images, the first frame is non-existent and
the injection occurs at frame 2. The error simply indicates that frame 1
was not found and should be ignored.

.SH AUTHOR
Tom Videen, 2005.
