.TH IMGFLIP 1 "20-Oct-2010" "Neuroimaging Lab"

.SH NAME
imgflip - flip an ECAT image right<->left

.SH SYNOPSIS
imgflip image

.SH DESCRIPTION
This program reverses the right-left ordering of pixels in an ECAT image.

.SH NOTES
The program inserts "imgflip.c,v" plus version and date into the main header (comment field).
However, this field is overwritten by many other programs (gauss, etc) and, of course, is lost
upon coversion to Analyze.

.SH EXAMPLE
imgflip p6000ho1.v

.SH SEE ALSO
anaflip

.SH AUTHOR
Tom Videen


