.TH IMGHDR 1 "18-Jul-00" "Neuroimaging Lab"

.SH NAME
imghdr - read headers of ECAT, PETT VI, and Interfile files

.SH SYNOPSIS
imghdr filename

.SH DESCRIPTION
imghdr reads and displays a summary of relevant parameters in
the main and subheaders for both version 6 and 7
ECAT image files, for PETT VI image files, and for Interfile header files.

.SH EXAMPLE ECAT 961
.nf
imghdr p5000ho1.v
------------------------------------------------
p5133ho1.v     06/11/96, 13:41:07
File format = Matrix 7
ECAT 961
Stationary acquisition
No correction for scatter
Software (Ver 70)
Filter = Ramp          Reconstruction Cutoff = 0.500000
ECAT calibration factor = 1.000000
Decay correction factor = 1.378601
Pixel size = 0.208634 cm
Plane_separation = 0.312500 cm
Isotope =  O-15
47 slices   2 frames   Bed Position: 52.215004 cm
Right-on-Left
Created with: 
Date: 
Max = 9007.461914   Min = -6501.524902
Frame length = 40 sec
Start time = 37 sec
Archive Type: 961 3d fbu ramp

.SH EXAMPLE PETT VI
.nf
imghdr p2500ho1.img
------------------------------------------------
p2500ho1.img     11/23/94, 10:28:20
File format = Matrix 6
ECAT 953
Wobbled acquisition
Scatter-corrected
Software (Ver 64) reconstructed with old nrm (before 4/12/1993)
Filter = Ramp          Reconstruction Cutoff = 0.250026
ECAT calibration factor = 1.000000
Pixel size = 0.208621 cm
Plane_separation = 0.337500 cm
Isotope =  O-15
31 slices   1 frames   Bed Position: 601.203552 cm
Right-on-Left
Created with:  
Date:  
Max = 7717.648926   Min = 0.000000
Frame length = 40 sec
Start time = 19 sec
Archive Type: 953 wob fb ramp

.SH AUTHOR
Tom Videen, 1996.
