.TH IMGRESLICE 1 "04-Dec-98" "Neuroimaging Lab"

.SH NAME
imgreslice - reslice an image using a specified AIR file

.SH SYNOPSIS
.nf
imgreslice input_file air_file

.nf
where:
  input_file = image file to reslice
  air_file   = air file containing the reslice matrix

.SH DESCRIPTION
This script reslices an image using a specified AIR file by calling:
.nf
	setanamin input_file -1
	mv_air air_file input_file
	reslice air_file output_file -n 1 -k -o

.fi
The program requires an image file in Analyze format and an AIR file
which was created with an input file with the same matrix dimensions.
The output file will have the same name as the input file with an 'r'
added at the beginning.

.SH EXAMPLES
.nf
imgreslice p5000ct p5000ct2ho

.SH SEE ALSO
aligndyn(1)

.SH AUTHOR
Tom Videen, Oct 1998.
