.TH IMGSUB 1 "03-May-2010" "Neuroimaging Lab"

.SH NAME
imgsub - subtract a constant from an ECAT image

.SH SYNOPSIS
imgsub image constant

.SH DESCRIPTION
This program subtraces a constant from all pixels in an ECAT (Matrix 6 or 7) image.

Possible use in creating ratio images using the sequence: imgdiv, imgsub, maskimg

.SH EXAMPLE
imgsub p5000ratio.t88 1

.SH RELATED PROGRAMS
imgsum(1), sumimg(1), scaleimage(1)

.SH AUTHOR
Tom Videen, May 2010.

