.TH IMGSUM 1 "16-Jan-97" "Neuroimaging Lab"

.SH NAME
imgsum - add or subtract a pair of images

.SH SYNOPSIS
imgsum scan1,f1 scan2,f2 out

.nf
where: out = (f1 * scan1) + (f2 * scan2)

.SH DESCRIPTION
This program adds a pair of PET images with scaling factors
applied. Using negative factors permits subtraction.

.SH EXAMPLES
.nf
imgsum p5000ho1.v p5000ho2.v p5000sum.v
imgsum p5000ho1.v,2 p5000ho2.v,-0.5 p5000sum.v

.SH RELATED PROGRAMS

imgsub(1), scaleimage(1), imgdiv(1), sumimg(1), sumimgplanes(1), sumimgframes(1)

.SH AUTHOR

Tom O. Videen


