.TH IMGTOTIF 1 "02-May-2006" "Neuroimaging Lab"

.SH NAME
imgtotif - convert image files to TIF format

.SH SYNOPSIS
imgtotif image tif_root zoom scale

.SH DESCRIPTION
imgtotif reads any image that can be displayed by vidi (PET, MR, CT)
and writes each plane to a separate TIF file using the specified zoom and scale factors.
TIF filenames will have the plane number appended to the tif_root.

.SH EXAMPLE
imgtotif nv7016_flair_2.img v7016_p 2 500

.SH RELATED PROGRAMS
vidi

.SH AUTHOR
Tom Videen, 2006
