.TH ANAVOl 1 "26-Oct-2006" "Neuroimaging Lab"

.SH NAME
imgvol - compute volume of pixels between min and max

.SH SYNOPSIS
imgvol image min max

.SH DESCRIPTION
This program reads an ECAT image file and computes the total
voxels having pixel intensities >= min AND <= max.
The result is written both in number of voxels and in cc
(based on the voxel size in the image hdr).

.SH EXAMPLE
imgvol p5000clot.v 1 100

.SH RELATED PROGRAMS
anavol

.SH AUTHOR
Tom Videen, Oct 2006

