.TH ISING 1 "14-Jun-2006" "Neuroimaging Lab"
.SH NAME
ising - create single normalized PETT VI or ECAT images 

.SH SYNOPSIS
.B ising prm imagelist

.SH DESCRIPTION
This script normalizes a list of PET images or creates
single difference pairs from the list.

ising separates an imagelist into single lists (using /tmp) and then processes these lists to create a set of single images.  Processes either filtered or unfiltered images.  Deletes all temporary files on /tmp.

Imagelists and parameter lists are the same as those used by imean.
However, imagelists MUST have each field separated by a SINGLE TAB and
should not have any comment lines

Output filenames are created using the parameter and imagelist files and are
always given the extension .im.

.nf
The prm file should contain keys for the following:
smg_norm:       1000
smg_mode:       single
smg_divisor:    local
smg_included:   all
z0:             38
zmax:           65

.SH SEE ALSO
imean(1), imgmean(1), prm(5), imagelist(5)

.SH AUTHOR
Tom Videen: 1999.
