.TH NPG 1 "30-Sep-98" "Neuroimaging Lab"

.SH NAME

jane - Listing of in-house software written by Jane Dunford-Shore.

.SH DESCRIPTION

This man page is an attempt to provide a listing of in-house software written by JDS.

.SH CT IMAGE TRANSFER
.ta 1.4i 1.6i
.nf

ctdown	-	Download CT image when it comes online
ctname	-	Print list of CT images online
ctwatch	-	Watch for new CT images to come online

.SH CT IMAGE MANIPULATION
.ta 1.6i 1.8i
.nf

ctcheck	-	Check CT images for scouts and duplicates
ctdup	-	Check for duplicate CT slices
ctheader	-	Read CT headers
ct2analyze	-	Convert to Analyze/IFH format
cttable	-	Print table positions and increments
cttilt	-	Correct Analyze-format CT for gantry tilt
cttime	-	Print scantime differences between slices
cutcat	-	Cut headers from *.ima's and concatenate data
dcm_ct2analyze	-	Convert from DICOM to Analyze format
dcm_ctheader	-	Read "header" info. from DICOM files
dcm_reorder	-	Rename *.dcm files to eliminate numeric gaps
ima_reorder	-	Rename *.ima files to eliminate numeric gaps

.SH DICOM FILE ANALYSIS/MANIPULATION
.ta 1.4i 1.6i
.nf

cmp_dmpfiles	-	Compare fields present in DICOM dump files
dcm_rename	-	Rename DICOM-format CT files to 000xx.dcm
dicom_def	-	Print list of fields in DICOM file
See also "CT IMAGE MANIPULATION"

.SH IMAGE ALIGNMENT
.ta 1.4i 1.6i
.nf

airthresh	-	Align 2 images using range of thresholds
See also "MANIPULATING PET IMAGES"

.SH MANIPULATING AIR FILES
.ta 1.4i 1.6i
.nf

airshift	-	Modify AIR file by translations and rotations

.SH MANIPULATING PET IMAGES
.ta 1.4i 1.6i
.nf

alignimg	-	Align all images in imagelist to standard
setscantype	-

.SH PROCESSING PET-RELATED DATA
.ta 1.4i 1.6i
.nf

cbfhem	-	Calculate CBF for left and right hemisphere
cbfrim	-	Calculate CBF for brain "rim"

.SH MISCELLANEOUS UTILITIES
.ta 1.4i 1.6i
.nf

addpath	-	Add filepath and date to top of file
comments	-	Extract comments from C code
dec2hex	-	Enter decimal; print hexadecimal
dec2sun_float	-	Enter DEC float as hex; print float value
deg2rad	-	Convert degrees to radians
findfn	-	Search default libraries for specified function
fman	-	Find man pages containing given string
hex2dec	-	Enter hexadecimal; print decimal
histodif	-	Find difference between histograms
libfn	-	Search a given library for a function



