.TH MAKEHDR 1 "02-Mar-99" "Neuroimaging Lab"

.SH NAME
makehdr - create hdr files manually

.SH SYNOPSIS
makehdr imagename

.SH DESCRIPTION
Makehdr lets you enter conversion coefficients, pieslope and oxygen content
directly to create a hdr files.

.SH EXAMPLES
.nf
makehdr p1000ho1
makehdr p5000oo1.v

.SH SEE ALSO
metproc(1), methdr(1), hdrinfo(1), hdr(5)

.SH AUTHOR
Tom Videen
