.TH MAKE_TSC 1 "02 May 2002" "Neuroimaging Lab"

.SH Name
.nf
make_tsc - make tissue-activity file for parameter estimation

.SH SYNOPSIS
make_tsc image voidata output npoints [slices]

.SH DESCRIPTION
This perl script creates a tissue-activity data file that can
be used for parameter estimation (e.g., fdgnoflow).

image = dynamic PET image

voidata = VOI file created by vidi, vidivoi, or make_wb_voi

npoints = number of time points (extra frames are skipped)

output = sped-file with 3 columns:  frame start time(sec),
	frame duration, and total decay-corrected counts

slices = optional value that is appended to the output file.
	It has NO effect on processing.

The frame start time and duration are read from input PET image.

.SH EXAMPLE
.nf
make_tsc p5949fdg1.v whole_brain.dat p5949wb.tsc 44
make_tsc p5949fdg1.v whole_brain.dat p5949wb.tsc 44 7to25

.SH SEE ALSO
vidi(1), vstat(1), vidivoi(1), make_wb_voi(1), pvc_tsc(1), vidi_voi(5)

.SH AUTHOR
Tom Videen, May 2002
