.TH MANUALRESLICE 1 "21-Oct-2005" "Neuroimaging Lab"

.SH NAME
.nf
manualreslice - trial and error registration; creates initialization files

.SH DESCRIPTION
manualreslice is part of the AIR package (see
http://bishopw.loni.ucla.edu/AIR3.indx.html)

.SH EFFECT OF ALTERING PARAMETERS
.nf
x-shift:  positive shifts subject left
y-shift:  positive shifts forward
z-shift:  positive shifts up
roll:     positive tilts right
pitch:    positive tilts nose up
yaw:      positive rotates nose to right (clockwise)
x-scale:  > 1.0 shrinks
y-scale:  > 1.0 shrinks
z-scale:  > 1.0 shrinks


