.TH MASKSIZE 1 "13-Nov-96" "Neuroimaging Lab"

.SH NAME
masksize - compute x- and y-dimensions of a mask

.SH SYNOPSIS

masksize filename

.SH DESCRIPTION
For each slice of the image, the x- and y-dimensions of the rectangle
which INCLUDES all pixels > 0 is printed.

.SH SEE ALSO

maskpct(1), maskimg(1), maskbars(1), maskshrink(1)

.SH AUTHOR

Tom Videen, Nov 1996.
