.TH MASKAND 1 "08-Feb-99" "Neuroimaging Lab"

.SH NAME
maskand - set to spec. value all pixels >= min AND <= max

.SH SYNOPSIS
maskand input output min max setval [x y z]

.SH PARAMETERS
.nf
input  - filename of input image
output - filename of output image
min    - mask above this intensity
max    - mask below this intensity
setval - value to assign to masked pixels
x,y,z  - coordinates of one pixel within the object
.fi

.SH DESCRIPTION
This program reads an ANALYZE image and sets all pixels which have values
both >= min AND <= max to a specified value. If the optional seed pixel 
is specified, then only pixels which are connected to the it will be masked.
All other pixel values will be preserved.

The search for connected pixels starts with the plane of the pixel and
goes down (increasing plane number) until the last slice and then reverses
and goes back up through all slices searching for any connected pixels
to any of the pixels identified thus far.

This masked image is written to the output file 
in ANALYZE format.

.SH EXAMPLE
maskand p5000seg1 p5000seg2 -100 20 0 290 290 20

.SH SEE ALSO
setpixval(1), maskor(1), maskout(1), expandor(1), maskelevlines(1)

.SH AUTHOR
Tom Videen, Feb 1999.
