.TH MASKLATERAL 1 "26-Jul-99" "Neuroimaging Lab"

.SH NAME
masklateral - mask one image using another 2D-image

.SH SYNOPSIS
maskimg input mask output threshold [setvalue]

.SH PARAMETERS
.nf
input     - filename of image to be masked
mask      - filename of the mask image (2D, single-slice image)
output    - filename of output image
threshold - minimum pixel value to include
setvalue  - optional value to assign to output pixels

.SH DESCRIPTION
This program was created to mask brains using an outline
drawn on a sagittal projection (see sumlateral) with vidi.
The input and output images are full 3D matrices while the
mask is a single plane representing a 2D sagittal slice of the
input image.

The output image file will have the same format as the input file
(e.g., PETT VI or ECAT versions 6 or 7).

A typical application would be to mask a CBF image to brain
where there might be extraneous activity in the CBF image in both
the nose and basal vessels:

.nf
gauss p5000ho1.v 0.3
gauss2d p5000tr1.v 0.5
sumlateral p5000tr1_2dg5.v p5000tr1_lat.v 700 1300
scaleimage p5000tr1_lat.v 0.01
img2analyze p5000tr1_lat.v ap5000tr1_lat
vidi
   Edit
   Fill with 0 all areas outside of brain
   Save
analyze2img ap5000tr1_lat p5000tr1_lat.v
masklateral p5000ho1_g3.v p5000tr1_lat.v p5000ho1_g3msk.v 1

.fi
The resulting p5000ho1_g3msk.v may be further edited using
vidi by converting to analyze format. Note that the Save feature
in the vidi main menu will always save to Interfile format which
requires the filename extension 'img'.

.SH EXAMPLES
.nf
masklateral in.v mask.v out.v 1234
masklateral in.v mask.v out.v 1234 100

.SH SEE ALSO
maskimg(1), maskpct(1), sumlateral(1)

.SH AUTHOR
Tom Videen, July 1999.
