.TH MASKOBJ 1 "13-Nov-98" "Neuroimaging Lab"

.SH NAME
maskobj - create a masked object in an image (with pixels=1)

.SH SYNOPSIS
maskobj input output threshold x y z

.SH PARAMETERS
.nf
input     - filename of image to be masked
output    - filename of output image
threshold - minimum pixel intensity to include
x,y,z     - coordinates of one pixel within the object
.fi

.SH DESCRIPTION
This program reads any PET image and sets all pixels which have values
>= threshold value and which are connected to the
seed pixel [x,y,z] to 1. All other pixel values are set to 0.
This masked object image is written to the output file.

The output image file will have the same format as the input file
(e.g., PETT VI or ECAT versions 6 or 7).

If you wish to include 'holes' within the object, try running maskpct
first (to create objects defined by their outer boundaries rather than
by only those pixels above a threshold). Then run maskobj on this masked
image.

.SH EXAMPLE
The following would create a brain mask which excludes the nose:

.nf
maskpct p5067ho1_g3.v maskobj.v 40
maskobj maskobj.v maskobj.v 1 64 64 24

.SH SEE ALSO
maskpct(1), maskimg(1)

.SH AUTHOR
Tom Videen, Nov 1998.
