.TH MASKPCTSLICE 1 "14-Nov-96" "Neuroimaging Lab"

.SH NAME
maskpctslice - mask an image by thresholding each slice

.SH SYNOPSIS

maskpctslice input output threshold

.SH PARAMETERS

.nf
input     - input filename
output    - output filename
threshold - percent of slice maximum
.fi

.SH DESCRIPTION
This program creates a thresholded image by zeroing all pixels
beyond an external boundary for which all pixels are greater than
or equal to the threshold as applied to each individual slice.

maskpctslice differs from maskpct in two respects: First, the
absolute threshold is, in general, different for each slice with
maskpctslice (maskpct uses the same absolute threshold for all
slices).  Second, the portions of output image which are not
zero contain the pixel values of the input image with maskpctslice
(maskpct sets them all to 1).

The output image file will have the same format as the input file
(e.g., PETT VI or ECAT versions 6 or 7).

.SH SEE ALSO
maskpct(1), maskimg(1), maskbars(1), masktrans(1), maskshrink(1)

.SH AUTHOR
Tom Videen, Nov 1996.

