.TH MASKSLC 1 "03-Oct-2003" "Neuroimaging Lab"

.SH NAME
maskslc - set specified slices to zero in an ECAT image file

.SH SYNOPSIS
maskslc input output planes

.SH PARAMETERS
.nf
input     - filename of image to be masked
output    - filename of output image
planes    - range of slices to set to zero
.fi

.SH DESCRIPTION
This program reads any PET image and sets the pixel values to zero
for the specified range of slices.

The output image file will have the same format as the input file
(e.g., PETT VI or ECAT versions 6 or 7).

.SH SEE ALSO
maskslice(1), maskimg(1), maskpct(1), maskobj(1), threshpct(1), maskobj(1)

.SH AUTHOR
Tom Videen, June 1996.
