.TH MASKSHRINK 1 "13-Nov-96" "Neuroimaging Lab"

.SH NAME
maskshrink - strip pixels from the edges of a masked image

.SH SYNOPSIS

maskshrink input output #pixels

.SH PARAMETERS

.nf
input    - input filename
output   - output filename
#pixels  - number of pixels to remove
.fi

.SH DESCRIPTION
This program strips pixels from the edges of a masked image thereby
shrinking the size of the mask similar to the "Shrink Template" option
in spideram.  The number of pixels specified will be removed from all outer
edges of the image.  I.e., a 2-pixel shrink will reduce both the height
and width of the mask by 4 pixels.

The algorithm works inward from each of the 4 edges and zeroes the first
n pixels found which have values > 0.  It is not a general image dilation
function and is intended for regular, convex objects.

The output image file will have the same format as the input file
(e.g., PETT VI or ECAT versions 6 or 7).

.SH EXAMPLE
.nf
maskshrink p2000tr1msk.img p2000tr1msk2.img 2

.SH SEE ALSO

maskpct(1), maskimg(1), maskbars(1)

.SH AUTHOR

Tom Videen, Nov 1996.
