.TH MASKBARS 1 "13-Nov-96" "Neuroimaging Lab"

.SH NAME
maskbars - mask headholder bars out of a transmission image

.SH SYNOPSIS

maskbars input output #xpixels #ypixels

.SH PARAMETERS

.nf
input     - filename of image to be masked
output    - filename of output image
#xpixels  - number of columns to remove at each lower corner
#ypixels  - number of rows to remove at each lower corner
.fi

.SH DESCRIPTION
This program sets all pixel values to zero within 2 rectangles located
at the lower left and right corners. It is intended to remove the presence
of the headholder bars in 953B transmission images so that xray will
not include these in the threshold which determines the head size.

The output image file will have the same format as the input file
(e.g., PETT VI or ECAT versions 6 or 7).

.SH EXAMPLE
.nf
maskbars p2000tr1.img p2000tr1msk.img 24 38

.SH SEE ALSO

maskpct(1), maskimg(1)

.SH AUTHOR

Tom Videen, Nov 1996.
