.TH MAXANA 1 "09-Oct-2002" "Neuroimaging Lab"

.SH NAME
maxana - create image with max pixel values from all input images

.SH SYNOPSIS
maxana outfile infile1 infile2 [infile3 infile4 ...]

.SH DESCRIPTION
This program creates an image containing the maximum voxel value from a
set of input images. All input images are in Analyze format and the output
is writen to a new Analyze image file.

.SH EXAMPLE
maxana p5000mask p5000mask_a p5000mask_b p5000mask_c

.SH RELATED PROGRAMS
img2analyze(1)

.SH AUTHOR
Tom Videen, Oct 2002.

