.TH MEANTR 1 "21-Jan-2003" "Neuroimaging Lab"

.SH NAME
meantr - compute mean of 2 images

.SH SYNOPSIS
meantr img1 img2 mean

.SH DESCRIPTION
This program computes the mean of 2 images for all pixels
which are non-zero in both images. Where a pixel is 0 in either image,
the non-averaged value from the other image is used.

This program was written to create composite transmission images
from 2 coregistered images from the same subject.

.SH EXAMPLE
.nf
meantr rp5000tr1.v rp5000tr2.v rp5000tr.v

.SH RELATED PROGRAMS
imgsum, sumimg, sumimgplanes, sumimgframes

.SH AUTHOR
Tom Videen


