.TH MERGEMASKS 1 "07-Oct-98" "Neuroimaging Lab"

.SH NAME
mergemasks - combine multiple masks

.SH SYNOPSIS
mergemasks outfile infile1 infile2 [infile3 infile4 ...]

.SH DESCRIPTION
Mergemasks reads the first input file to outfile and then 
reads all additional input files setting all pixels in 
the first file to zero which are zero in any of the other files.

If all input files are masks, the output will be the combined mask.

If the first input file is not a mask, the output will be this
input file masked by the combination of all the other files.

.SH EXAMPLE 
.nf
mergemasks p5000seg_all p5000seg_skull p5000seg_vent p5000seg_ocsf

.SH AUTHOR
Tom Videen, 1998.
