.TH MERGE_DYNFRAMES_DECAYCOR 1 "04-Aug-2008" "Neuroimaging Lab"

.SH NAME
merge_dynframes_decaycor - merge single frames into a dynamic image

.SH SYNOPSIS
merge_dynframes_decaycor root frames extension output

.nf
  root      = root of input filenames
  frames    = frames to merge
  extension = extension of input files
  output    = filename of output, dynamic image

.SH DESCRIPTION
This script creates a dynamic image file by copying a series
of single-frame images in ECAT format.
The files to be copied must be sequential.

.SH EXAMPLE
.nf
merge_dynframes_decaycor rp7000fd 2to31 .i rp7000fd1.v

would copy the single-frame files:
	rp7000fd1.i
	rp7000fd1.i
	...
	rp7000fd1.i

into the file rp7000fd1.v.

.SH SEE ALSO
singleframe, analyze2img_decaycor

.SH AUTHOR
Tom Videen, Aug 2008.
