.TH MERGEFRM 1 "10-Sep-98" "Neuroimaging Lab"

.SH NAME
mergefrm - copy single image frames into a multiframe image file

.SH SYNOPSIS
mergefrm infile frm# outfile frm# [stdfile frm#]

.SH DESCRIPTION
mergefrm copies 1 frame of an image into another image file,
assigning it to the specified frame number in that file.

The optional standard file and frame number will use the
header information from that file in creating the output file.
This is useful when the merged files may have lost important
information during conversion to and from Analyze format 
(e.g., during image realignment) and the complete header information
can be recovered from the original file.

.SH EXAMPLE 
.nf
mergefrm rp5000g5.v 1 rp5000dyn.v 5
mergefrm rp5000g5.v 1 rp5000dyn.v 5 p5000cg1.v 5

.SH AUTHOR
Tom Videen, 1998.
