.TH MERGE_DYNECAT 1 "01-Jun-2005" "Neuroimaging Lab"

.SH NAME
merge_dynecat - merge individual frames into a dynamic image

.SH SYNOPSIS
merge_dynecat root suffix frames output

.nf
  root   = root of input filenames
  suffix = suffix and/or extension of input filenames
  frames = frames to merge
  output = filename of output, dynamic image

.SH DESCRIPTION
This is a variation of merge_dynframes used specifically to
merge a set of ECAT images reconstructed with increasing frame numbers
inot a single dynamic image. It differs from merge_dynframes, which
reads a set of images, all internally identified as frame 1.

The files to be copied must be sequential.

.SH EXAMPLES
.nf
merge_dynecat p6000fdg .v 2to11 p6000fdg1.v

would copy the single-frame files:
	p6000fdg2.v frm 2
	p6000fdg3.v frm 3
	...
	p6000fdg11.v frm 11

into the file p6000fdg1.v, frames 2-11.

.SH SEE ALSO
merge_dynframes(1), singlefrm_gauss(1), imgfrms(1), imghdr(1), aligndyn(1),
separate_dynfiles(1)

.SH AUTHOR
Tom Videen, Jun 2005.
