.TH MRI 1 "09-Dec-2002" "Neuroimaging Lab"

.SH NAME
mri - programs for Siemens MR files in ima format

.SH CONVERSION PROGRAMS
.nf
ima2bshort	- converts to bshort format (perfusion studies)
mri2ana		- converts continuous slices to Analyze/Interfile
mri2analyze	- same as mri2ana using a different syntax
mriseq2analyze	- converts time-sequence (multiple frames)
tse2analyze	- converts TSE acquired as offset slabs
tsei2analyze	- converts TSE acquired as interleaved slices

.SH HEADER INFORMATION
.nf
imaorder		- shows slice position of scans in a sequence
imascans		- listing of all sequences in a study
imashortlist	- abbreviated listing of all sequences in a study
mrihdr		- header information for a single scan

.SH SEE ALSO
.nf
dcm		-	programs for DICOM format
ctima	-	programs for Siemens CT files in ima format

.SH AUTHOR
Tom Videen, 2002

