.TH MRIHDR 1 "12-Mar-2002" "Neuro PET Group"

.SH NAME
mrihdr - list header info from Siemens MRI images (ima)

.SH SYNOPSIS
mrihdr <filename>

.SH DESCRIPTION
mrihdr reads headers of Siemens MRI image files (ima) and lists selected information
to your screen.

.SH RELATED PROGRAMS
mri2analyze(1)

.SH AUTHOR
Tom O. Videen

