.TH MRSCANS 1 "17-Jan-2002" "Neuroimaging Lab"

.SH NAME
mrscans - identifies MR DICOM scans by series number

.SH SYNOPSIS
mrscans <MR | .MR>

.SH DESCRIPTION
mrscans reads all DICOM files in a directory, sorts them by series number,
then writes:
.nf

1) first and last filenames in each series
2) sequence filename and sequence description
3) subject id, study date, orientation, image dimensions,
   and pixel dimensions

This information is saved in a file Scans.lst.

Input DICOM files use the naming convention:

	.MR..2.1.2001.8.21.14.30.40.203000.660978.IMA

where fields (separated by dots) represent:
	MR	= modality
	2	= series number
	1	= image number
	2001	= year of acquisition
	8	= month 
	21	= day
	14	= hour
	30	= min
	40	= sec
	203000 = time of transfer
	660978 = time of transfer
		(last 2 numbers are assigned at time of network transfer)

Input files may have the initial dot removed, e.g.,
	MR..2.1.2001.8.21.14.30.40.203000.660978.IMA

The script looks only a the initial character of the root.
Files must begin with ".MR.." or "MR..".

.SH EXAMPLES
.nf
mrscans .MR
mrscans MR

.SH RELATED PROGRAMS
pacscans(1), dcmscans(1), imascans(1), dcm2analyze(1), dcm_dump_file(1), mri2analyze(1), analyze_avw, interfile(5)

.SH AUTHOR
Tom Videen

