.TH NFRAMES 1 "10-Sep-98" "Neuroimaging Lab"

.SH NAME
nframes - set number of frames in header of all ECAT and PETT VI image files

.SH SYNOPSIS
nframes filename number

.SH DESCRIPTION
nframes sets the number-of-frames field in a file header.

.SH EXAMPLE 
.nf
nframes p5000fdg1.v 55

.SH AUTHOR
Tom Videen, 1998.
