.TH PEAKSTRIP 1 "08-Jan-97" "Neuroimaging Lab"

.SH NAME
peakstrip - identify distinct peaks in an image

.SH SYNOPSIS
peakstrip in out cutoff threshold separation radius [mask]

.SH DESCRIPTION
Peakstrip is a modification of peakid which has a simplified output
file.  Each line of the output has 4 numbers (magnitude, X, Y, Z) plus a filename.
Pixel coordinates (an no atlas coordinates) are used.
Output files from several runs might be pooled and then sorted to determine
the maxima across all files.

Peakstrip identifies distinct peaks in an image with selectable
criteria for the peaks (e.g., volume summed, amplitude,
separation, intermediate valley) using the same criteria as peakid (see).

.bp
.SH OUTPUT FILE FORMAT:
.nf
    131    65    56    26     combined.v
    114    40    59    25     combined.v
    113    38    41    22     combined.v
    100    50    71     8     combined.v
    100    59    63    16     combined.v

The numbers represent the pixel magnitude, X, Y, and Z coordinates.

.SH SEE ALSO
peakid(1)

.SH AUTHOR
Tom O. Videen
