.TH NPG 1 "20-Oct-2010" "Neuroimaging Lab"

.SH NAME
npg - Listing of in-house software.

.SH DESCRIPTION
This man page is an attempt to provide a listing of in-house software broken down by general function. Complete information on the syntax and function of each routine may be found in a man page for the individual routine. The current version of a program may be checked by typing "ident" followed by the program name (specifying its complete path). Note that there are many other routines on our system obtained from various sources (see /usr/local/bin and /usr/local/pkg).  Also,
this list does not include programs which only run on the PET console.

All programs run under SunOS 5.x (Solaris) except where indicated by "[4]".
The latter programs run only under SunOS 4.1 on petsun13 or petsun14.

.SH IMAGE DISPLAY
.ta 1.4i 1.6i
.nf
vidi	-	image display and VOI analysis
sino	-	sinogram display 
spideram	-	image display and ROI analysis
image_orientation - general comments regarding

display	-	command line call of xv_imagetool [4]
quickview	-	quick visualization of pair of images 
ram2xwd	-	convert Ramtek (saveramx) files to xwd files [4]
show_fonts	-	displays fonts in an xv_imagetool window [4]
view25d	-	image display and figure generation [4]
view25d2	-	variation of view25d using 2 images [4]
xlabel	-	figure generation [4]
xv_imagetool	-	displays ECAT files (images, sinograms) [4]
xv_colortool	-	color table tool for xv_imagetool [4]

.SH MANIPULATING PET IMAGES
.ta 1.4i 1.6i
.nf
aligndyn	-	align frames of a dynamic image using AIR
align_dynamic	-	align frames of a dynamic image using AIR (use AIR blur)
alignimg	-	coregister images in an imagelist using AIR
align_dynpet	-	script for aligning human FDOPA and NMB images
align_ha	-	script for pair of HA images images
align_ho	-	script for pair of HO images images
align_latepib	-	script for late ~30 min of PIB
align_oxygen	-	align OO and CO images to HO image
align_tr	-	align transmission images
aligning_dynamic - overview of method using aligndyn
aligning_images - overview of method using alignimg
butterworth	-	3-D Butterworth filter
dilate2d	-	2-D dilation of image
ecat2pett6	-	convert ECAT images to PETT VI format [4]
ecathdr	-	list info in ECAT version 6 image header [4]
enlarge_pix	-	enlarge pixels of an ECAT image
filterimg	-	filters all images in an imagelist
fixflip	-	set orientation to Right-on-Right in header
focus2img	-	convert FOCUS image to ECAT7 format
gauss	-	3-D Gaussian filter
gauss_dynamic	-	gauss applied to dynamic ECAT image
gauss2d	-	2-D Gaussian filter
ge2if	-	create Interfile image from a GE Export file (.ie)
ge2img	-	convert GE Export file to ECAT format
gehdr	-	display header info from GE Export files
header6	-	list information in PETT VI image header [4]
headerEdit	-	edit information in ECAT version 6 image header [4]
hdrEdit	-	edit information in ECAT version 7 image header
histoimg	-	histogram values in an image
if2analyze	-	create an Analyze hdr from an Interfile header (ifh)
ifdyn2img	-	create an ECAT 7 file from a dynamic Interfile 
imageadd	-	add matrix files (truncates negative values!) [4]
imageweld	-	combine indexed images [4]
img2analyze	-	convert PET image to Analyze/IFH format
img2if	-	convert PET image to Interfile format (dynamic reals)
img2iff	-	convert PET image to Interfile format (dynamic reals); same as above
img2spm	-	convert PET image to SPM99 format (Analyze with left/right reversed)
img2spmf	-	convert PET image to SPM99 format (floating point)
img2spm5	-	convert PET image to SPM5 format (Analyze with left/right unchanged)
imgand		-	performs logical AND on 2 images [4]
imgavg	-	compute mean of 2 images
imgcnts	-	display total counts in PET image frames
imgdiv	-	divide one image by another
imgflip	-	flip image right<-->left (ECAT format)
imgfrms	-	display frame start and durations from PETT VI or ECAT files
imghdr	-	display header info from PETT VI or ECAT files
imghisto	-	create histograms of image pixel values
imgmskthresh	-	number of pixels above threshold within a mask
imgreslice	-	reslices an image using an AIR file
imgrotate	-	rotates & reslices an image specifying angles
imgsub	-	subtract a constant from an image 
imgsum	-	add (or subtract) one image to another
imgvol	-	get volume of voxels with intensity >=min <=max
invertimg	-	invert all pixel values in an image
maskbars 	-	mask lower 2 corners (headholder bars) in a PET image
maskimg	-	mask one image using another
masklateral 	-	mask pixels in a PET image using a sagittal mask
maskobj 	-	create a masked object (all connected points >= n)
maskout 	-	create a masked object using an Analyze image
maskpct	-	create a mask from a PET image using a wholebrain threshold
maskpctslice	-	mask pixels in a PET image using slice threshold
maskshrink	-	strip pixels from the edges of a masked PET image
masksize	-	measure the x- and y-dimensions of a masked PET image
maskslc	-	set slices to zero in a PET image
masktrans	-	create a masked transmission image for xray sizing
matadd	-	add matrix files [4]
matcopy	-	copy matrix files [4]
meantr	-	averge 2 coregistered images
merge_dynframes - merge single-frame images into a single dynamic file
merge_dynecat - merge single-frame images containing sequentially numbered frms
mergefrm	-	copy single frames to multiframe image file
mergemasks	-	merge several segmented Analyze files into a combined mask
nframes	-	set number of frames in PET image file
origscanorient	-	restores original right-left scan orientation [4]
pett6cnts	-	list count statistics in a PETT VI image header [4]
plot_aligndyn	-	plot misalignment computed by aligndyn
ptimage	-	create a paired-t image [4]
remove_dynfiles - cleanup processing files from aligndyn
removespike	-	kludge to reduce an artifact in p5276-p5311
reslicedyn	-	create aligned frames using AIR files computed by aligndyn
reslice_dynpet	-	reslice for human FDOPA and NMB images using existing AIR files
reslice_S_t4	-	reslice Analyze image using 4dfp t4 matrix for sagittal orient
scaleimage	-	scale ECAT images to eliminate display overflow
scanhdr	-	get header info on any ECAT file
scancnts	-	get counts from header of a raw (sinogram) file
scantime	-	get scantime from any ECAT file
scntest	-	check trues from header against summed trues from data
separate_dynframes - separate individual frames of image
setanamin	-	set global min in Analyze hdr
setfrmlen	-	set frame duration in a PET image
setpixsize	-	set pixel size in a PET image
setz0	-	set z-origin in an ECAT image
simple_weld	-	combine indexed images [4]
singleframe - extracts one frame from a dynamic image maintaining decay_corr_fctr
singlefrm_gauss - extracts and filters frames from a dynamic image
slcmean	-	compute image mean over a specified slice range
slicemean	-	compute mean counts/pixel for each slice
smooth3d	-	filter an ECAT image using a sphere
sp3000conv	-	convert SP3000 image file to PETT VI image file [4]
spm2if	-	create Interfile header for an SPM image 
spm2img	-	convert SPM image to ECAT format
spmhdr	-	display header info from SPM files
sumfdg	-	create a composite fdg image (add last 9 frames)
sumimg	-	sum multiple, single-frame PETT VI or ECAT images
sumimgframes	-	sum frames of an image file
sumimgplanes	-	sum planes of an image file
sumlateral	-	sum lateral projection of an image
sumsino7	-	sum frames of a Matrix 7 sinogram
thinimg	-	strip pixels from the edges of a masked image [4]
threshpct	-	threshold a PET image (differs from maskpct)
utimage	-	create an unpaired-t image [4]

.SH STEREOTAXIC PET IMAGES and ACTIVATION ANALYSIS
.ta 1.4i 1.6i
.nf
af3d_par	-	get af3d points [4]
chkhdlst	-	check input list file for hd6mean	 [4]
chklist	-	check an imagelist + parameter file
convert_t	-	transform coordinates hd6 -> t88 [4]
fliptrg	-	flip a trg file to opposite hemisphere [4]
gammaz	-	compute gamma 2 from set of af3d points [4]
gammaz2i	-	convert gammaz output to file readable by view25d [4]
hd6mean	-	transform and average to hd6 atlas (.smg) [4]
hd6tot88	-	approx. transformation from hd6 -> Talairach 1988 [4]
imean	-	create composite mean images with no atlas transformation
imgmean	-	compute global means for all images in a list
imgscale	-	scale all single images in a list using global means
ising	-	create individual imean images
isum	-	create composite summed images
locates	-	convert VOI coordinates from atlas space to PET space
logan	-	create BP images using Logan graphical analysis
makebmap	-	creates a baboon map file for t88trans
makemap	-	creates a map file (matrix transformation) for t88trans
makeprmlst	-	creates an abbreviated parameter file from an image [4]
patlak	-	create K images using Patlak graphical analysis
peakid	-	find isolated peaks in an image
peakid2i	-	converts peakid points to view25d format [4]
peaksearch	-	find isolated peaks in an image 
peakstrip	-	find isolated peaks in an image (simplified output)
rapture	-	regional analysis of power of t tested using replication [4]
smginfo	-	display info on an hd6mean image [4]
spheres	-	add filled-spheres to a new or existing image
sxrscale	-	insert an x-scaling factor into an sxr file
sxrweld	-	create sxr file for welded images [4]
t88mean	-	transform and average to Talairach using sxr files
t88sing	-	create individual t88mean images
t88trans	-	transform and average to Talairach using map files
t88trsing	-	create individual t88trans images
voi2img	-	convert a VOI (vidi format) to an image
voihisto	-	plot histogram of pixel intensities of a VOI 
voimean	-	compute regional means for a set of VOIs and images [4]
wgtlst	-	apply weighting factors to files in an imagelist [4]
xray	-	create skull x-ray files (.sxr) [4]
xscale	-	compute x-scaling factor and add it to an sxr file

.SH PROCESSING PET-RELATED DATA
.ta 1.4i 1.6i
.nf
betadcv	-	deconvolve crv files (to dcv files)
betadta	-	convert crv files to dta files [4]
betawel	-	calibration file for blood sampler (betadta, betadcv)
blood	-	manual entry of dta files
chklist	-	check existence of all files in an imagelist
cmrglu	-	compute CMRGlucose from fdg image (IDL)
cmrglucose	-	compute CMRGlucose from fdg image (script)
combine_striatum - combine striatum object images (fdopa)
crt2crv	-	convert crt + plt files to crv file
dcvpeak	-	show takeoff, rise time, peak and width of a blood curve
dynreg	-	tissue activity curve generation [4]
dyntac	-	time-activity curve from VOI on dynamic image
fastdta	-	fast creation of dta file [4]
fastflow	-	combined fastdta and fastproc [4]
fastproc	-	fast creation of hdr files [4]
fdopa	-	man page of scripts for dynamic FDOPA processing
fdgcalc	-	compute CMRfdg from counts
fdgnoflow	-	parameter estimation of FDG uptake
flowdata	-	fast creation of dta files [4]
gammaz2i	-	converts af3d points to view25d format [4]
getshift	-	compute the shifts applied in a dta file
headstart	-	get visual delay from 3-frame 961 headcurve
hdrinfo	-	list information in (metproc or petproc) hdr file
makedta	-	create dta file from dcv and r files
makehdr	-	create an hdr file by entering values
make_wb_voi	-	create whole-brain VOI for vstat processing
make_tsc	-	create tissue-activity file for parameter estimation
meanrgt	-	creates mean rgt files for JSP parameter estimation
metcalc	-	compute metabolic values from counts + hdr files
metcalc_pvc	-	partial volume corrected metabolic values 
metcalc_pvc_hemi - special case for pvc-metabolic values
metproc	-	metabolic processing (creates hdr files)
methdr	-	create hdr file using meteval info from img files
nmb	-	man page of scripts for dynamic NMB processing
dcvpeak	-	
petproc	-	tissue activity processing (creates hdr files)
piecreate	-	create pie files (.pie)
piedata	-	create pie data files (.pdf) [4]
plotcrv	-	plots crv files
plotdcv	-	plots dcv files
plotdta	-	plots dta files
plotglu	-	plots glucose/fdg data and fit curve
plothcrv	-	plots 961 headcurve (.r) files
plotpair	-	plots pixel values for pairs of ECAT images
plotplt	-	plots 953B headcurve (.plt) files
plotshift	-	plot shifted blood (dta) and headcurves (r)
plotsped	-	plots sped-format data files
plotstart	-	plot pairs of ECAT (ver 7) headcurve files (.r)
pvc_tsc	-	create partial-volume-corrected tissue-activity file
spidreg	-	compute mean regional values with spideram .reg file
sumdyn40	-	creates 40-sec image from 2-sec dynamic
sumdynact	-	modification of sumdyn40
vidivoi	-	interactive VOI file creation
voidat	-	compute mean regional values with vidi vois on multiple images
voimake	-	VOI file creation (voistat format) from an image
voiproc	-	compute mean regional values on dynamic images (time-activity curves)
voistat	-	compute mean regional values
vstat	-	compute mean regional values with vidi vois on single image

.SH ATLAS FIDUCIAL PROCESSING
.ta 1.4i 1.6i
.nf
rncheck	-	compare subject RN location to atlas

.SH MANIPULATING MRI IMAGES
.ta 1.4i 1.6i
.nf
dcm	-	commands for DICOM format images
mri	-	commands for Siemens ima format images
ana	-	commands for Analyze format images

also:
IMAtoima	-	convert old VAX names (i.e., 00001.IMA;1)
align_slab_tse2mpr - coregister thin slab TSE image to MPRAGE
change_mr_vaxnames - convert VAX names (i.e., 00001.ima)
cpimas	-	retrieve MR files from scanner disks [4]
dicom	-	DICOM routines and file naming convention
dupifh	-	duplicate an Interfile header for a new image file
gauss3d	-	3-D Gaussian filter (using IDL)
if2analyze	-	create an Analyze hdr from an Interfile header (ifh)
mrscans	-	MR DICOM routines and file naming convention
mricv	-	convert to Analyze format (old) [4]
mricvns	-	convert to Analyze format (old without byte-swapping [4]
mritot88	-	transform MR images to Talairach space
pacscans	-	show summary of PACS DICOM files

.fi
There are a number of undocumented routines for MR images in
/data/petsun4/data1/solaris

.SH MANIPULATING CT IMAGES
.ta 1.4i 1.6i
.nf
dcm	-	commands for DICOM format images
ctima	-	commands for Siemens ima (VAX) format images
ana	-	commands for Analyze format images
ctpts_to_mai	-	convert coordinates of contacts to Mai space
contact_dist	-	compute distance between contacts in Mai space

also:
ct_segmentation - segment CT images for partial volume correction
cttilt	-	correct CT images for gantry tilt 
decup	-	remove cup-shaped beam-hardening artifact
slicenrm	-	normalize CT images across slices

.SH MANIPULATING ANALYZE and INTERFILE IMAGES
.ta 1.4i 1.6i
.nf
ana	-	man page containing all commands for Analyze images
mriconvert_fix - swap bytes and fix headers from MRIConversion (Win)
reorient_ifh	- reorient Interfile images to standard Analyze axial

.SH MANIPULATING IMAGES
These are programs intended to handle all local image formats, including
Interfile, Analyze, CTI versions 6 and 7, and PETT VI. Where an output
file is created, it is always in Interfile format. All require an
IDL runtime license.

.nf
gauss3d	-	3-D Gaussian filter
image_scale	- either scale an image or compute the global mean
image_subset	- create a image using a selected set of planes
image_sum	- add 2 images with arbitrary scaling factors

.SH PARTIAL VOLUME CORRECTION
.nf
imgconvol	-	convolve a tissue image
pvc	-	correct a PET image using a convolved tissue image

.SH MANIPULATING AIR FILES
.ta 1.4i 1.6i
.nf
airdif	-	compares difference between 2 AIR files
airdif1	-	compares difference between 2 AIR files (ECAT mask)
airdifana	-	compares difference between 2 AIR files (Analyze mask)
airerr	-	compares error between AIR alignment and fiducials
airmatrix	-	reads AIR files (alternative to scanair)
airslices	-	changes number of slices in AIR file
airxfid	-	multiplies AIR matrix times fiducial points
dumpair	-	write AIR file contents 
newairpix	-	alters pixel sizes of an AIR file

.SH PET IMAGE RECONSTRUCTION 
.ta 1.4i 1.6i
.nf
fix_header	-	fix headers of mlempetv7 reconstructed images
mappettrans	-	MAP TR reconstruction of ECAT transmission
mlempetv7	-	ML reconstruction of ECAT emission
recon6	-	PETT VI
recon953	-	ECAT 953B
reconhr	-	ECAT HR (961)

.SH MISCELLANEOUS UTILITIES
.ta 1.4i 1.6i
.nf
arcfind	-	locate and transfer files from archive
archive	-	move or identify files in optical archive
check_absent_files	- check for non-existence of a set of files
checkfiles	-	check for existence of a set of files
chkpett6files	-	check for missing raw PETT VI scan files
decoder	-	decodes old PETT VI files encoded with encode1
fitlog2plt	-	simplifies log file created by align_dynpet
ftplist	-	copy all files in a list from a remote machine
hrtapedir	-	get directory of 961 archive tape (see tapedir)
iozone	-	runs I/O speed test on disks
lowercase	-	change filename from upper to lowercase
petcm	-	view PET calendar from Solaris 2 machines
petdat	-	PET data base
plotsped	-	plots sped-format data files
plotting	-	shows list of plot routines
remove_dot	-	change filenames to remove trailing dot
sped	-	statistical package editor
tapedir	-	get directory of entire tar-created tape (see hrtapedir)
tapedup	-	duplicate a tape
tpbytes	-	estimate MBytes from a tapedir listing
xcreturn	-	remove carriage return from LEX-created files
xwdcolor	-	rescales xwd file and send to HP color printer

.SH FILE and LIST DEFINITIONS
.ta 1.4i 1.6i
.nf
atl	-	atlas files
dta	-	blood curve data file
filetypes	-	brief summary of in-house file types
hdr	-	format of hdr files
ifh	-	Interfile format header
imagelist	-	format for image list files
imagespace	-	definitions of various array spaces
pet	-	this listing of local software
piefile	-	information about pie files
prm	-	format of parameter files
rec	-	format of rec files
reg	-	region-of-interest for spideram
rgt	-	output from ROI processing
sxr	-	skull xray file
voi	-	volumes-of-interest for voistat

.SH USEFUL PUBLIC SOFTWARE
.ta 1.4i 1.6i
.nf
air	-	Automatic Image Registration package
acroread	-	read pdf files
analyze_avw	-	Analyze run on petsun23 or petsun24
analyze_avw_private	-	Analyze run from an xterm on a pc
ghostview	-	read ps files
matlab	- Matlab 5.x (runs SPM99)
matlab7	- Matlab 7.x (runs SPM5); requires SunOS 5.8 or above
pbmplus	-	image manipulation (pnm, xwd, ps, ras)
psutils	-	manipulation of PostScript files
snapshot	-	Solaris screen capture
spm	-	called from matlab	
xkeycaps	-	display and alter keyboard mappings
xv	-	manipulates a variety of images

.SH AUTHOR
Tom O .Videen
