.TH PLOTHCRV 1 "06-Sep-2002" "Neuroimaging Lab"

.SH NAME
plothcrv - plot ECAT (ver 7) headcurve files (.r)

.SH SYNOPSIS
plothcrv PID

.SH DESCRIPTION
This is an IDL program which plots headcurves for dynamic scans (2 or more frames).
It plots trues/sec vs. time
and shows the start of frame 2  and the total number of frames.

It will pause after plotting each headcurve found with the specified PID and
continue when you enter Return.

Sometimes there are spikes (either high or low) in the headcurves at the time of a frame
change. These may be eliminated manually by editing the file and deleting the
line on which these appear.

.SH EXAMPLE
plothcrv p6000

.SH SEE ALSO
plotcrv(1), plotdta(1), gnuplot(1)

.SH AUTHOR
Tom Videen, Sept 2002

