.TH PLOTGLU "21-Mar-2002" "Neuroimaging Lab"

.SH NAME
plotglu - plot glucose tissue curve plus fit

.SH SYNOPSIS
plotglu

.SH DESCRIPTION
This program reads an output file from one of several of Joanne's
parameter estimation routines and plots the results. The file should
be in sped format with the first column containing the mid-interval times,
the second column containing the raw activity, and the third column
containing the fit activity.

The program uses IDL and requires an IDL license (full or runtime).

.SH SEE ALSO
fdgnoflow

.SH AUTHOR
Tom O. Videen

