.TH PLOTSTART 1 "28-Apr-2003" "Neuroimaging Lab"

.SH NAME
plotstart - plot pairs of ECAT (ver 7) headcurve files (.r)

.SH SYNOPSIS
plotstart pid refscan

.SH DESCRIPTION
This is an IDL program which plots headcurves for multiple dynamic scans.
All scan ids and start times are read from the dta file (pid.dta).
This may be a standard dta file created by makedta (see man dta) or
it can be a file created with an editor containing only scanids and
frame starttimes with the following format:

.nf
	startframes
	8
	ho1   9
	ho2   8
	ho3   9
	ho4   9
	ho5   8
	ho6   9
	ho7   9
	ho8   8
.fi

If the latter format is used, the headcurves are assumed to comprise
2-sec frames with the scan beginning with frame 2.

Headcurves are read from the appropriate .r file.
Each headcurve is normalized using its peak activity.

The reference scan is plotted in white with its start time indicated
by a horizontal line.

All other scans in the dta file are plotted in red with their curves
shifted so that their start times match that of the reference scan.

The plots pause after each headcurve and continues when you enter Return.
There is an option to print all curves superimposed.

The intent is to permit easy visualization of pairs of curves
from a set of activation images in order to check their start times
for consistency.

.SH EXAMPLE
plotstart p6000 ho1

.SH SEE ALSO
plotshift(1), getshift(1), makedta(1)

.SH AUTHOR
Tom Videen, Apr 2003

