.TH PLOTTING 1 "04-Apr-2007" "Neuroimaging Lab"

.SH NAME
plotting routines

.SH BLOODCURVES (crv,dcv,dta)
.nf
plotcrv	- plot raw bloodcurves using gnuplot (.crv); has print option
plotbcrv	- plot raw bloodcurves using IDL (.crv)
plotdcv	- plot deconvolved bloodcurves (.dcv)
plotdta	- plot shifted, deconvolved bloodcurves (.dta)
plotshift	- plot shifted, deconvolved bloodcurves (.dta) with headcurves (.r)
plotstart	- compare bloodcurves (.dta) matching start times to a reference scan

.SH HEADCURVES (r)
.nf
plothcrv	- plot headcurves of dynamic files (.r)
plotr	- quick headcurve plot to check dose (.r)
plotshift	- plot shifted, deconvolved bloodcurves (.dta) with headcurves (.r)

.SH DYNAMIC IMAGES (v)
.nf
plotdyn40	- define 40-sec scan period for HO or OO (.v)

.SH DYNAMIC TISSUE CURVES
.nf
plot_aligndyn	- plot log files created by aligndyn
plot_aligndyn2	- plot log files created by aligndyn with additional options
plotglu	- plot glucose tissue curve plus fit
plotglu2	- 
plotglucose	- 

.SH IMAGE PIXEL CORRELATIONS (v)
.nf
plotpair	- scatter plot comparing 2 images (.v)

.SH GENERAL ROUTINES
.nf
plotcol	- plot a single column of a data file
plotsped	- plot a SPED file (graphical interface)

.SH AUTHOR
Tom Videen, Apr 2007

