.TH PLOTSPED 1 "21-Aug-2002" "Neuroimaging Lab"
.SH NAME
plotsped - plot a SPED file

.SH SYNOPSIS
plotsped 

.SH DESCRIPTION
This is a widget-based IDL program that will plot any 2 columns (x vs. y) from SPED files.
Ranges of both scales are set by default to min and max from the sped file values
but may be overridden by entering new values after each file is read.

A "Scaler" may be set to scale the values of either axis.

X- and Y-axis labels and a title may be entered. Remember that all text fields
require you to type "Return" before a new entry is recognized by IDL.

Additional selection buttons permit changing the plot symbols, plotting symbols
plus lines, adding a reference line, and sending the plot to your default printer.

.SH EXAMPLE
plotsped

.SH AUTHOR
Tom Videen, 2002


