.TH PLOTSHIFT 1 "24-Apr-2003" "Neuroimaging Lab"

.SH NAME
plotshift - plot shifted blood (dta) and headcurves (r)

.SH SYNOPSIS
plotshift pid 

.SH DESCRIPTION
This is an IDL program which plots headcurves with their shifted bloodcurves.
All scan ids and bloodcurves are read from the dta file (pid.dta).
Headcurves are read from the appropriate .r file.
Each headcurve is normalized to the blood curve using the time of the
bloodcurve peak activity.

The headcurves are plotted in white with the start time indicated by a horizontal line.
The shifted blood curves are plotted in red.

Both curves have the activity present in the time bin 1 frame
prior to the starttime subtracted from them. Graphically, this
means that both curves will intersect the horizontal origin
1 frame prior to the start of the scan.

The plots pause after each headcurve and continue when you enter Return.

The intent is to permit easy visualization of the shifts set in makedta.

.SH EXAMPLE
plotshift p6000

.SH SEE ALSO
plotstart(1), getshift(1), makedta(1)

.SH AUTHOR
Tom Videen, Apr 2003

