.TH PLOTDTA 1 "18-Oct-93" "Neuroimaging Lab"

.SH NAME
plotdta - plot a blood curve file

.SH SYNOPSIS
.B plotdta filename

.SH DESCRIPTION
This is a script whick calls gnuplot to plot the points in a decay-corrected, shifted, blood curve file (.dta).  The axes of the plot are autoscaled to the data set.  Each curve in the dta file may be plotted.

The plot may either be displayed on your terminal or sent to a printer, an option which you are prompted for after the script has read the file.


.SH EXAMPLE
.nf
plotdta p2000.dta

Do you wish to: (1)  Plot curves on screen or
                (2)  Print them on your default printer?
1
hit return to continue

.SH SEE ALSO
plotcrv(1), gnuplot(1)

.SH AUTHOR
Dave Carpenter (documentation Tom Videen)


