.TH PLOTCRV 1 "13-Nov-97" "Neuroimaging Lab"

.SH NAME
plotcrv - plot a blood curve file

.SH SYNOPSIS
plotcrv filename

.SH DESCRIPTION
This is a script which calls gnuplot to plot the points in a blood curve file (.crv).  The axes of the plot are autoscaled to the data set.

The plot may either be displayed on your terminal or sent to a printer, an option which you are prompted for after the script has read the file.

.SH EXAMPLE
.nf
plotcrv p2000ho1.crv

Do you wish to: (1)  Plot curves on screen or
                (2)  Print them on your default printer?
1
hit return to continue

Note that while plotcrv will take a wild card in for input, i.e.,
"plotcrv p5000*crt", be sure to include the extension! If you simply
enter "plotcrv p5000*" it will attempt use all files (including image
files).

.SH SEE ALSO
plotdta(1), gnuplot(1)

.SH AUTHOR
Dave Carpenter (documentation Tom O. Videen)


