.TH PLOT_ALIGNDYN 1 "21-Oct-98" "Neuroimaging Lab"

.SH NAME

plot_aligndyn - plot log files created by aligndyn

.SH SYNOPSIS

.B plot_aligndyn

.SH DESCRIPTION

This is an IDL program which plots the mean pixel misalignment as
estimated by aligndyn.
It plots mm displacement vs. frame number for the Mean and X, Y and Z displacements.

Call the program with "plot_aligndyn".  At the prompt
.nf
	Alignment log filename:

.fi
enter the full name of the file, i.e., p2788mb_th3_g3.log.

at the prompt:
.nf
	First (reference) frame: 

.fi
enter the number of the first frame specified when running aligndyn.
Entering an incorrect number will merely shift the curve on the x-axis.

The program computes the maximum and minimum mean shifts, which it displays as:
.nf
	First (reference) frame: 3
	      2.63100     -1.63700
	Maximum for plot: 

.fi
At this prompt you can pick the range for the y axes (in this case, 4
would be an appropriate response).

.nf
At the prompt:
	print, continue or exit [p,c,x]: 

.fi
Typing 'p' will send a postscript file to your default printer (lpr, which
should be a postscript printer). Typing 'c' will permit plotting a different
file or the same file using a different range. Typing 'x' exits the program.

The program requires a runtime IDL license.

.SH SEE ALSO

aligndyn(1)

.SH AUTHOR

Tom Videen, October 1998.


