.TH ptimage 1 "24-Jul-97" "Neuro PET Group"

.SH NAME

ptimage - create a paired-t image

.SH SYNOPSIS

.B ptimage difimage sedimage nimage timage
.nf
where:
	difimage - a mean difference image (meandiff)
	sedimage - the corresponding image of pixel standard error of the difference (sed)
	nimage   - number of subjects contributing to each pixel (n)
	timage   - paired t image (t)
.fi

.SH DESCRIPTION

ptimage reads 3 image files and combines them to create an image of pixel t-values.  All output t-values are scaled by 1000 (i.e., divide by 1000 to get actual t).  A rec file is created with the output file.

Complete filenames should be specified for all 4 files.
Unlike the older version of ptimage, there are no restrictions on the
names of the 4 files.

.SH ALGORITHM

	t = 1000 * meandiff / (sed / sqrt(n))

where the files are defined as above.  Computations are done pixel-by-pixel.  If n <= 0 or sed <= 0, then t is set to 0.

.SH RELATED PROGRAMS

t88mean(1), utimage(1)

.SH AUTHOR

Tom O. Videen


