.TH PVC 1 "10-Mar-98" "Neuroimaging Lab"

.SH NAME
pvc	-	apply partial volume correction to a PET image

.SH SYNOPSIS
pvc infile tissue mask cutoff

.SH DESCRIPTION
This program computes a partial volume corrected image by dividing
the input file (PET image) by a suitable tissue image (see imgconvol)
at all points within a mask specified by the mask image and cutoff.
All points not in the mask will be zero in the output image.

All 3 input images must be in Analyze format
and the output image will be in Analyze format.

This program reads all images into working memory
(for large images, use a workstation with suffient RAM).

The accuracy of the resulting pvc-corrected image requires
properly coregistered PET and tissue images.
The accuracy also depends critically upon the
PET and tissue images being the same resolution!
See man page for gauss to determine
the resolution of PET images. (And don't even think of applying
this to Butterworth-filtered images).

.SH EXAMPLES
.nf
pvc ap5000ho1_g3.img rp5000tis16.img rp5000mask.img 1000

will create pvcap5000ho1_g3.img and pvcap5000ho1_g3.hdr

.SH RELATED PROGRAMS

imgconvol(1), gauss(1)

.SH AUTHOR

Tom O. Videen, March 1998.
