.TH recon953 1 "09-Dec-2002" "Neuroimaging Lab"
.SH NAME
recon953 - Reconstructing ECAT 953B images

.SH DESCRIPTION
There are a set of programs which will reconstruct 953B
images on any of the Suns (running Solaris 2).

953B data sets should comprise: stationary and wobbled normalization,
blank and processed blank scan, at least 1 transmission scan
with processed log-transmission and attenuation files, and
1 or more emission scans:
.nf
	normalsta_020202.nrm
	normalwob_020202.nrm
	020202bl1.scn
	020202bl1.smo
	p3000tr1.atn
	p3000tr1.scn
	p3000tr1l.scn
	p3000ho1.scn
	p3000fdg1.scn

.fi
The blank scans are used only for creating the attenuation and log-transmission
files (which must be done on the ECAT console, petsun11).

A transmission image may be reconstructed from the log-transmission file with:
.nf
	recon_2dtr p3000tr1 p3000tr1l 1 0.5 1.875

.fi
If the emission scans were acquired with gantry wobble, a wobble attenuation
file must be created from the stationary attenuation file:
.nf
	makeWobbleAttn p3000tr1.atn p3000tr1_wob.atn

.fi
If a transmission image is forward-projected to create an attenuation file
(fpattn6), always forward-project to create a stationary attenuation and then
use makeWobbleAttn to create the wobble attenuation.

Emission scans are either stationary or wobbled and acquired with randoms
subtracted or saved separately. Each variation requires a unique set of
processing steps. If prompts plus delayeds were acquired (for reduced noise
estimates of randoms), the scan files are first corrected for randoms using
rnwproc:
.nf
	rnwproc -r -p . p3000ho1.scn

.fi
If multiple scan frames are to be summed prior to reconstruction, use sum_dframes:
.nf
	sum_dframes p3000ho1.scn p3000ho1_sum.scn 1 2

.fi
Commands for reconstructing stationary or wobbled, single-frame or dynamic
files are:
.nf
	recon_2dsta p3000ho1 p3000ho1 p3000tr1 normalsta_020202 1 0.5 2.0
	recon_2dwob p3000ho1 p3000ho1_rn p3000tr1_wob normalwob_020202 1 0.5 2.0
	recon_2dstadyn p3000fdg1 p3000fdg1 p3000tr1 normalsta_020202 1 .5 2.0 7
	recon_2dwobdyn p3000fdg1 p3000fdg1 p3000tr1_wob normalwob_020202 1 .5 2.0 7

.fi
All 2D reconstruction scripts cal bkproj_sun.

.SH 3D RECONSTRUCTION
3D reconstruction is done using recon3d (which is a wrapper for recon3d_scat).
.nf
	recon3d p3000fdg1 p3000tr1 020202bl1 020202 2.086 1 44

.fi
If no 3d normalization file exists, it can be created using makenorm_f3d.

These scripts call the following binaries (John Ollinger):
.nf
	arc_corr
	bkproj
	cti_getparam
	extract_summed_planes
	floatmath
	fproj_volume
	import_3dscan_nonorm
	list_sinograms
	makenorm_cti953b
	make_eff_tr_cti953b
	scatcor_cti953b
	sino_2d_extract_cti953b
	which_geo


.SH 953B RECONSTRUCTION PROGRAMS
.ta 1.4i 1.6i
.nf
recon953	-	summary of reconstruction routines
filtercode	-	sets filter code in ECAT files (not necessary)
fpattn6	-	forward project attenuation correction for 953B
makeWobbleAttn	-	create a wobbled atn file from a stationary atn file
oneframe	-	sets number of frames to 1 (ECAT files)
read_archive_tape	-	read all ACS-archived files for a subject
rec2d	-	reconstruct all one subject's 2-D sinograms
rec2dhr	-	reconstruct 961 HR 2-D sinograms
rec3d	-	reconstruct all one subject's 3-D sinograms
recon3d	-	reconstruct a single 3-D sinogram
recon3df2	-	reconstruct frame 2 of a single 3-D sinogram
recon_2dsta	-	reconstruct a 2-D stationary sinogram
recon_2dstadyn	-	reconstruct a 2-D stationary dynamic sino
recon_2dtr	-	reconstruct a 2-D log transmission sinogram
recon_2dwob	-	reconstruct a 2-D wobbled sinogram
recon_2dwobdyn	-	reconstruct a 2-D wobbled dynanmic sino
renameframe	-	copy a frame of an ECAT file (set frames=1)
rnwproc	-	reduced-noise processing of randoms
scanhdr	-	get header info on any ECAT file [4]
scantest	-	compare sino counts with header total
sinocnts	-	get total counts from a sinogram
sumattn6	-	sum (or average) ECAT 6 attenuation files
sumattn6planes	-	average all planes of an ECAT 6 attenuation file

.SH AUTHORS
.nf
2D backprojection by Paul Luk (CTI).
3D reconstruction by John Ollinger.
Wrapper scripts by Tom Videen.
