.TH reconhr 1 "09-Dec-2002" "Neuroimaging Lab"
.SH NAME
reconhr - Reconstructing ECAT HR (961) images

.SH DESCRIPTION
EXACT HR images must be reconstructed on the scanner console (exacthr).
This can be done remotely using submitReconJob.

.nf
Usage:submitReconJob
	-s scanFileName  (-S database#)
	-n normFileName  (-N database#)
	-a attenFileName  (-A database#)
	-i imageFileName  (-I database#)
	
	-g xOffset,yOffset,imgRotation,imgSize,zoomFactor [0,0,0,128,1.0]
	-c decayCorFlg,scatCorFlg,arcCorFlg,singleElFlg,debug [1,0,1,0,0](for 2D) 
	-f filterCode,cutoffFreq,filtReso,butrwFiltOrder [1,0.5,11.0,0]
	-F filterCodeR,cutoffFreqR,filterCodeZ,cutoffFreqZ, [3,0.5,1,0.5]
	-m frame,plane,gate,data,bed [*]
	-p priority [0]

set scn = /home/data/work/p6000ho1.S
set nrm = /home/data/work/p6000.N
set atn = /home/data/work/p6000tr1.a
set img = /home/data/work/p6000ho1.v
set siz = '0,0,0,128,2.076'
set cor = '1,1,1,0'
set fil = '1,0.5'
set Fil = '1,0.5,1,0.5'
set pri = 1

submitReconJob -s $scn -n $nrm -a $atn -i $img -g $siz -c $cor -f $fil -F $Fil -m '3-,*,*,*,*' -p $pri



.SH PROGRAMS FOR MANIPULATING ATTENUATION FILES
.ta 1.4i 1.6i
.nf
fpattn7	-	forward project attenuation correction for EXACT HR
sumattn7	-	sum (or average) ECAT 7 attenuation files

.SH AUTHORS
.nf
2D backprojection by Paul Luk (CTI).
3D reconstruction by John Ollinger.
Wrapper scripts by Tom Videen.
