.TH recon6 1 "09-Dec-2002" "Neuroimaging Lab"
.SH NAME
recon6 - Reconstructing PETT VI images

.SH DESCRIPTION
There are a set of programs which will reconstruct PETT VI
images on any of the Suns. For a typical triple pack, the data set should include:
.nf
	r555nrm
	r555trn
	r555ho1
	r555oo1
	r555oc1

These would be processed using the commands:
	pronorm6 r555nrm tov
	protran6 r555trn p555tr1 filterg tov
	recon6   r555ho1 p555ho1 filterg tov
	recon6   r555oo1 p555oo1 filterg tov
	recon6   r555oc1 p555oc1 filterg tov
	cleanid6 tov

.SH PETT VI RECONSTRUCTION PROGRAMS
.ta 1.4i 1.6i
.nf
pronorm6	-	process norm files
protran6	-	process transmission files
recon6		-	process emission scans
cleanid6	-	remove temporary processing files

atenprof	-	create attenuation profiles
atensize	-	estimate diameter of object in atten image
backproj	-	filtered backprojection
binprof	-	convert raw date to profiles (angle/bin)
coratten	-	correct atten profiles prior to backproj
corscan	-	correct emission profiles prior to backproj
detnorm	-	create detector normalization file
mask6a	-	mask points outside ring and format image
normave	-	compute normal average
recdyn	-	extract single frame from dynamic raw file
slicesep	-	separate raw data by slices

.SH AUTHOR
Tom Videen
