.TH RESLICE_S_T4 1 "01-May-2009" "Neuroimaging Lab"

.SH NAME
reslice_S_t4 - reslice an image using a t4 transform file

.SH SYNOPSIS
.nf
reslice_S_t4 input_file S_t4_transform

.nf
where:
  input_file = image file to reslice (Analyze format)
  S_t4_transform = file containing the reslice matrix

.SH DESCRIPTION
This script reslices an Analyze image file in standard Analyze orientation
(array order: Right->Left, Post->Ant, Inf->Sup)
and reslices it to 711-2B atlas with 2-mm voxels using an existing t4 transformation matrix.
It assumes the original transform was based on a sagittally oriented MRI.

The script calls 4 programs that manipulate 4dfp files:
analyzeto4dfp, T2S_4dfp, t4img_4dfp, 4dfptoanalyze

The resliced file will be have standard Analyze orientation with the same name as the input
file with an "r" prefix.

The script permits using standard tools for manipulating Analyze files (such as segmentation)
and converting the results into the same atlas space that was used for some other processing.

4dfp files incorporate an undocumented, bastardized version of Interfile format.

.SH EXAMPLES
.nf
reslice_S_t4 p7000_tis p7000_mprage1_to_711

.SH SEE ALSO
imgreslice

.SH AUTHOR
Tom Videen, 2009.
