.TH RNCHECK 1 "25-Nov-2009" "Neuroimaging Lab"
.SH NAME
rncheck - compare RN locations to atlas
.SH SYNOPSIS
.B rncheck dbid

.SH DESCRIPTION
Rncheck reads an atlas fiducial location file created by fidpts_to_mai and
computes the vector distance of the centers of the right and left red nuclei
to those of the Mai atlas. The output includes the DB#, fiducial name, x, y, z, and vector distance (mm).

.SH EXAMPLE
.nf
rncheck db250 [a]

.fi
reads the file db250_fid.atl, compares fiducials 10 and 11 to Mai atlas values, and writes:

.nf
db250  RNL    4.50 -22.75  -5.14   1.90
db250  RNR   -5.00 -22.75  -5.14   2.04

.fi
Adding a parameter will display this information plus the error in each dimension along
with column headers:

.nf
DBID   fid      x      y      z    dist     dx     dy     dz
db250  RNL    4.50 -22.75  -5.14   1.90   0.30  -1.05   1.56
db250  RNR   -5.00 -22.75  -5.14   2.04  -0.80  -1.05   1.56


The true Mai Atlas locations are (best estimate):
       RNL    4.2  -21.7   -6.7 
       RNR   -4.2  -21.7   -6.7 

.fi.
The final number is the 3D distance from the identified RN to the Atlas RN. It is typically less than
2.0 mm. Anything greater than this should be checked for errors (but is not necessarily incorrect).

.SH RELATED PROGRAMS
fidpts_to_mai

.SH AUTHOR
Tom Videen: 2009
