.TH RNWPROC 1 "13-Jan-95" "Neuro PET Group"

.SH NAME

rnwproc -compute reduced-noise estimate of randoms.

.SH SYNOPSIS

.B rnwproc -rtd -f framenumber inputfile.scn

.SH DESCRIPTION

Reads an ECAT sinogram file with prompts and delayeds stored separately and creates various output files:

.nf
	-r	corrected trues = prompts - reduced-noise delayeds
	-t	CTI trues = prompts - delayeds
	-d	prompts and reduced-noised delayeds
		(e.g., input for ML reconstruction)
	-f	process specified frame and store data in frame 1
		(without -f, all frames are processed)
.fi

The algorithm is from "Quantitation in Positron Emission Computed Tomography:
A Technique to Reduce Noise in Accidental Coincidence
Measurements and Coincidence Efficiency Calibration"
Michael E. Casey and Edward J. Hoffman (1986)
Journal of Computer Assisted Tomography 10(5):845-850.

Versions of the program run before Feb 3, 1994, were incorrect.

NOTE:  with the current version, you must use "-rt" if you want "-t".

.SH AUTHORS

John Ollinger, Gerald Johns


