.TH SAMPLE_PTS 1 "05-Jan-96" "Neuroimaging Lab"

.SH NAME

sample_pts - reads an Analyze image and writes and plots all coordinates
which contain non-zero values

.SH SYNOPSIS

sample_pts

.SH DESCRIPTION

The program prompts for a filename of an Analyze image (with extension .img).
It then reads the file, gets the coordinates of all voxels which are non-zero
and writes them to the screen. Finally, it prompts for 2 dimensions and plots
all coordinates on these 2 axes.

It was intended to use with segmented fiducials to identify outliers or
errors in the segmentation.

.SH RELATED PROGRAMS

fit_fiducials(1), fit_triangle_1n(1)

.SH AUTHOR

Tom O. Videen
