.TH SCALEIMAGE 1 "20-Dec-95" "Neuroimaging Lab"
.SH NAME
scaleimage - scales pixel values in an ECAT image file

.SH SYNOPSIS
scaleimage filename factor

.SH DESCRIPTION
scaleimage applies the specified factor to all planes of an ECAT image file.
This adjust the pixel magnitude to produce values more suitable for programs
which work with short integers (i.e., values from -32768 to 32767).  This can
either eliminate annoying black holes (from values outside this range) or
increase the dynamic range (for images with small integer values).
The scaling factor applied is written to the study_description field of the
main header in the output file, where it may be checked with imghdr.

The scaled image can be restored to the original image by scaling a second
time with the reciprocal of the original factor.

A recfile is created.

.SH PARAMETERS
.nf
filename - input image filename
factor   - real scaler applied to the image
.fi

.SH EXAMPLE 
scaleimage p3000ho1.v. 0.1

.SH SEE ALSO

spideram(1)

.SH AUTHOR

Tom Videen: Dec 1995
