.TH SCANCNTS 1 "29-Aug-2005" "Neuroimaging Lab"
.SH NAME
scancnts - test 961 sinogram files for errors

.SH SYNOPSIS
scancnts sinogram_filename [firstfrm lastfrm]

.SH DESCRIPTION
Scancnts reads prompts, delayed and trues from the header of raw scan files.

By specifying 2 frames, only the range spanning these frames is listed and the
total time and total trues are displaned.

.SH EXAMPLE
.nf
scancnts p6514ho1.S

Frm     Start  Duration    Prompts    Delayed  Net Trues
  1         0     42550      23987      21437       2550
  2     42550      2000       1742       1499        243
  3     44550      2000       1591       1336        255
  4     46550      2000       1540       1365        175
  5     48550      2000       2084       1716        368
 ...

scancnts p6514ho1.S 12 31


.SH RELATED PROGRAMS
scntest - gives same information but also sums the trues from the raw data

.SH AUTHOR
Tom Videen Aug 2005
