.TH SCANTEST 1 "30-Aug-99" "Neuroimaging Lab"
.SH NAME
scantest - test 953B sinogram files for errors

.SH SYNOPSIS
scantest sinogram_filename

.SH DESCRIPTION
Scantest compares the actual total counts in each matrix of an unprocessed sinogram
file with the total stored in the matrix subheader at the time of the data acquisition.
The output gives, among other things, "Trues" and "Actual Int".  "Trues" is the number
recorded by the scanner at acquisition; "Actual Int" is the number currently in the
matrix.  If these 2 values differ, then the difference is displayed at the end of
the row inside of *'s (see example below).  This is equivalent to a checksum test
and any discrepancies reflect data corruption. 

Some of these discrepancies can be fixed with the program fixsino.
In particular, an erratic transient in the Mizar on the 953B caused occasional
bad elements in data acquired between 1/21/94 (<=p2376) and 1/12/95 (>=p2524)
These typically were 1 or 2 bad locations in an entire sinogram file.

Other, more widespread discrepancies cannot be fixed.  In particular, memory
board #4 of the 953B was defective from about 11/18/94 (p2496) to 1/4/95 (p2524).
This appears as entire frames of errors, typically beginning with matrix 7,19,1,1,0
in 2-D dynamic acquistions.  

By using the Unix pipe and tee for the output, you need not watch the entire
listing from a dynamic file scroll past the screen since grep will identify
any errors, as in the following example:

.SH EXAMPLE
.nf
scantest p2498ho8.scn | tee test.log
grep \\* test.log

 F    P   G   D  B     Prompts      Delays    Multiples       Trues  Actual Int
___  ___ ___  _ ___    _______      ______    _________       _____  __________
  1    1   1  0   0        613         256            3         357         357
  1    2   1  0   0        598         231            2         367         367
  1    3   1  0   0        666         168            3         498         498
...
  2  220   1  0   0      53812       11604         1190       42208       42208
  2  221   1  0   0      58780       12044         1226       46736       48534  * 1798 *
  2  222   1  0   0      54976       10728         1208       44248       44248
...

.SH NOTES
Differences between "Trues" and "Actual Int" are only meaningful in unprocessed
sinogram files!

.SH RELATED PROGRAMS
fixsino(1) - runs only under SunOS 4.1.3

.SH AUTHOR
.nf
Copyright 1989-1992 CTI PET Systems, Inc.
Solaris version: Tom Videen Aug 1999.
