.TH SCANHDR 1 "21-Sep-93" "Neuroimaging Lab"
.SH NAME
scanhdr - read the header of any ECAT file and write a summary of information  
.SH SYNOPSIS
.B scanhdr filename

.SH DESCRIPTION
Scanhdr reads the main header of any ECAT file and writes a summary.  As it only reads the main header, it can read all ECAT files including emission, transmission, blank, and normalization files. (ecathdr works only with image files).

The information displayed includes:  scan date, filetype, data type, acquisition type, wobble/stationary acquisition, isotope, frames, planes, and horizontal bed position.

.nf
File types:
	1 = sinogram
	2 = image
	3 = attenuation
	4 = normalization
	5 = smo

Data types:
	2 = I*2 VAX
	3 = I*4 VAX
	4 = R*4 VAX
	5 = R*4 Sun
	6 = I*2 Sun
	7 = I*4 Sun

Acquisition types:
	0 = blank or normalization
	2 = transmission
	3 = emission
.fi

If you attempt to run scanhdr on a non-ECAT file, you will get a core dump :-(

	Segmentation fault (core dumped)

.SH SEE ALSO
ecathdr(1)

.SH AUTHOR

Tom O. Videen: 1993.
