.TH SCNTEST 1 "29-Aug-2005" "Neuroimaging Lab"
.SH NAME
scntest - test 961 sinogram files for errors

.SH SYNOPSIS
scntest sinogram_filename

.SH DESCRIPTION
Scntest compares the total trues summed from the raw data in a sinogram
file with the total stored in the subheader at the time of the data acquisition.
This is equivalent to a checksum test
and any discrepancies between the last 2 columns reflect data corruption. 


.SH EXAMPLE
.nf
scntest p6514ho1.S

Frm     Start  Duration    Prompts    Delayed  Net Trues  Summed Trues
  1        16     50250      26432      24010       2422       2422
  2     50266      2000       1651       1573         78         78
  3     52266      2000       1502       1375        127        127
  4     54266      2000       1340       1222        118        118
  5     56266      2000       1523       1434         89         89
  6     58266      2000       2560       2303        257        257
  7     60266      2000       3298       3021        277        277
  8     62266      2000       3508       3308        200        200
  9     64266      2000       3886       3145        741        741
 10     66266      2000       6862       3437       3425       3425
 11     68266      2000      15279       4194      11085      11085
 12     70266      2000      50962      10181      40781      40781
 ...
Total            143900                          3104003    3104003

.SH RELATED PROGRAMS
scancnts - gives information from header but without Summed Trues

.SH AUTHOR
Tom Videen Aug 2005
