.TH SETANAMIN 1 "13-Oct-98" "Neuro PET Group"

.SH NAME

setanamin - sets global min and max in an ANALYZE hdr

.SH SYNOPSIS

setanamin ANALYZE_root minimum [maximum]

.SH DESCRIPTION

setanamin is useful for forcing the global minimum in an Analyze image
to 0, thus avoiding a "feature" in the AIR package which automatically
scales 16-bit data to unsigned integers.  The processing is usually not
what you wish unless the negative values are zeroed first.

Likewise, is it useful for restoring the global minimum in the header
prior to running reslice16, which shifts 0 to -32768 with
16-bit data if the input minimum is not < 0.

You may also set the maximum in the header. The maximum influences the
behavior of some programs, notably Image Edit within Analyze and
alignlinear.

Note that setanamin does NOT change the values in the image,
but only in the hdr file.  This is sufficient for AIR and preserves
the data for other programs.

.SH EXAMPLES
.nf
setanamin p2000ho1 0
setanamin p2000ho1 -115
setanamin p2000ho1 0 1000

.SH RELATED PROGRAMS
img2analyze(1), air(1), ANALYZE

.SH AUTHOR
Tom Videen, 1995-8.
