.TH SETFRMLEN 1 "10-Apr-2008" "Neuroimaging Lab"

.SH NAME
setfrmlen - set to the frame length in an ECAT image

.SH SYNOPSIS
setfrmlen filename framelen

.SH PARAMETERS
.nf
filename  - image filename (single frame image)
framelen  - frame length in seconds (integer)
.fi

.SH DESCRIPTION
This program changes the frame duration in the subheader of frame 1 of an image file.

.SH EXAMPLE
.nf
% imghdr cp6840fdg1.v | grep length
Frame length = 0.001 sec

% setfrmlen cp6840fdg1.v 1800

% imghdr cp6840fdg1.v | grep length
Frame length = 1800.000 sec

.SH AUTHOR
Tom Videen, Apr 2008.
