.TH SINGLEFRAME 1 "04-Aug-2008" "Neuroimaging Lab"

.SH NAME
singleframe - extract single-frame of an ECAT image

.SH SYNOPSIS
singleframe infile outfile frame

.nf
  infile  = filename of dynamic image (ECAT 7 format)
  outfile = filename of output image file
  frame   = frame to isolate

.SH DESCRIPTION
This reads a single frame of a dynamic ECAT 7 image file and
writes it to new file. The output image will contain the same
subheader values as the input file, in particular, the start time 
and decay-correction factor.

This routine should be used when co-registering images that will
later be used for quantitative processing (where the decay-correction
factor must be retained until the final sumimgframes_decay is
executed).

.SH EXAMPLE
.nf
singleframe p7000fdg1.v p7000fdg1_f10.v 10

.SH AUTHOR
Tom Videen, Aug 2008.
