.TH SINGLEFRM_GAUSS 1 "21-Oct-98" "Neuroimaging Lab"

.SH NAME
singlefrm_gauss - create filtered, single-frame images in Analyze format from dynamic image

.SH SYNOPSIS
singlefrm_gauss image frames planes cutoff tracer extension

.nf
  image     = full path and filename of dynamic image
  frames    = frames to isolate; specified as "1to44"
  planes    = planes to isolate; specified as "1to31"
  cutoff    = cutoff (cycles/cm) for Gaussian filter
  tracer    = tracer name for output files
  extension = file extension to use for output files

.SH DESCRIPTION
This command script creates filtered, single-frame images in Analyze format
from a dynamic image file.
This is a necessary step prior to running aligndyn.

The specified planes of the original dynamic
image are copied to a separate file for each frame (separate_dynframes).
Each of these images is filtered (gauss) using the specified filter cutoff.
The filtered images are converted to Analyze format (img2analyze)
and the header minimum is set to 0 (setanamin).

If a file already exists, the processing steps for that image are skipped.

.SH EXAMPLE
.nf
singlefrm_gauss /data/m500nmb1.img 1to44 8to20 0.3 mb i

.SH SEE ALSO
separate_dynframes(1), imgfrms(1), imghdr(1), gauss(1), img2analyze(1), setanamin(1),
aligndyn(1)

.SH AUTHOR
Tom Videen, Oct 1998.
