.TH SLCMEAN 1 "12-Oct-2000" "Neuroimaging Lab"
.SH NAME
slcmean - compute mean within a mask over specified slices

.SH SYNOPSIS
slcmean img mask firstpln lastpln

.SH DESCRIPTION
This program reads a primary and masking image.
It returns the number of voxels, mean intensity, standard
deviation, standard error, and t 
for all voxels > 0 in the mask for slices >= firstpln and <= lastpln.

.SH EXAMPLE
slcmean v1069mpr1.img v1069_brain.img 1 151

.SH SEE ALSO
maskimg(1), maskpct(1)

.SH AUTHOR
Tom Videen, 2000.
