.TH SLICENRM 1 "08-Feb-99" "Neuroimaging Lab"

.SH NAME
slicenrm - normalize an Analyze image slice-by-slice

.SH SYNOPSIS
slicenrm input output min max norm

.SH PARAMETERS
.nf
input   - filename of input image
output  - filename of output image
min,max - intensity range of pixels to normalize
norm    - normalization value (additive)
.fi

.SH DESCRIPTION
This program reads an ANALYZE image and identifies all pixels within
each slice which are >= min and <= max. It computes the mean of these
pixels and compare it with the norm value. If these differ, the
program ADDs the difference to each pixel in that slice.

This masked image is written to the output file 
in ANALYZE format.

The original intent of this program was to eliminate the beam hardening
effect from CT images of the brain sufficiently to perform semi-automatic
segmentation.

.SH EXAMPLE
slicenrm p5000seg1 p5000seg2 10 75 35

.SH SEE ALSO
maskor(1), maskand(1), maskout(1), expandor(1), maskelevlines(1)

.SH AUTHOR
Tom Videen, Feb 1999.
