.TH SMOOTH3d 1 "12-Jan-2011" "Neuroimaging Lab"

.SH NAME
smooth3d - 3D spherical filter

.SH SYNOPSIS
.nf
smooth3d infile outfile radius sampled

radius is specified in mm.
sampled = 0 or 1
	0 will include all pixels in the smoothed output image
	1 will exclude any pixels which are not fully-sampled with the sphere

.SH DESCRIPTION
smooth3d filters ECAT images by computing the mean of all pixels within
the specified radius at every pixel. This is a similar averaging technique
to that used in af3d and is equivalent to placing a spherical VOI at
each pixel in the original image.

Unlike af3d, when part of the sphere is not sampled the mean will be reduced.
I.e., all sums of the smoothing VOI are divided by the same number (the volume
of the sphere) regardless of how many pixels may have contributed to the
sum for any particular pixel.
This causes edges of the image array to have lower values and has 2 advantages:
1) noise does not increase at edges; 2) it is possible to assess which pixels
were fully sampled by applying the same filter to a mask image (in which
all brain pixels are set to a constant).

.SH EXAMPLE
.nf
smooth3d p5000ho1.v p5000ho1_s.v 10.7 0
smooth3d p5000mask.v p5000mask_s.v 10.7 1

.SH VOI Volume for ECAT 961 Images
For standard EXACT HR images (2.144x2.144x3.275 mm voxels) the following
radii produce VOIs with these volumes:

.nf
     Radius      Volume
      mm      pixels   cc 
     -----    ------  ----
      3          5     0.1
      4         19     0.3
      5         39     0.6
      6.4       69     1.0
      7        105     1.5
      7.7      137     2.0
      9.1      209     3.0
      9.8      275     4.0
     10.7      347     5.0
     13.4      705    10.1

.SH SEE ALSO
gauss(1), butterworth(1), gauss3d(1), box2d(1), gauss2d(1)

.SH AUTHOR
Tom Videen: Jan 2011
