.TH SORTPTS 1 "16-Sep-2002" "Neuroimaging Lab"
.SH NAME
sortpts - sort a vidi points file by ascending Z-value

.SH SYNOPSIS
sortpts file 

.SH DESCRIPTION
This will sort points list created by vidi. The input and output
files are SPED-format. The first 2 lines are copied and the rest of the
lines (each comprised of 3 integers) are sorted in ascending order of the
third integer (z-coordinate).

.SH EXAMPLE
sortpts p5000mpr1.pts

.SH AUTHOR
Tom Videen, 2002

