.TH SPHERES 1 "03-Jul-2001" "Neuroimaging Lab"
.SH NAME
spheres - add filled-spheres to a new or existing image

.SH SYNOPSIS
spheres image_in image_out x y z radius <add/new>

.SH DESCRIPTION
This program adds spheres with pixel intensity=1000 to an image file.

An existing image is read to get dimensions and format. Then, the
sphere is either added to it or inserted in a clean image depending
upon the specification of the final parameter (add or new).

The sphere's location is specified in image coordinates (x,y,z).
The radius is specified in mm.

This program was created to define an image masked comprising
multiplem, distinct VOIs.

.SH EXAMPLES
.nf
spheres meanmr.t88 voimask.t88 64 64 31 10 new
spheres voimask.t88 voimask.t88 50 85 20 20 add

.SH AUTHOR
Tom Videen, 2002
