.TH SPIDREG 1 "20-Dec-2000" "Neuroimaging Lab"

.SH NAME
spidreg - compute mean regional activity using spideram .reg

.SH SYNOPSIS
.nf
spidreg regionfile outfile imgfile1 [imgfile2 ...]

.SH DESCRIPTION
spidreg computes the mean regional activity for spideram ROIs
defined in an .reg file (man 5 reg) for all images named on the
input line (up to 12). Both rectangular and irregular ROIs
may be used.

The output file is similar to the one created by spideram using
the print option in the Analysis of Regions menu. It differs in
that it includes the number of pixels of each region.
The first column of the output file contains each region name,
the second column has the number of pixels, and each additional
column contains the mean counts for the region for the images, e.g.,

.nf
Region      Pixels rp5007ho1msk rp5007oc1msk rp5007oo1msk rp5007tis04m
sl18clot        65        0.000        0.000        0.000        0.000
sl18peri       146      420.815        0.630      144.678      284.507
sl19clot        84        0.000        0.000        0.000        0.000
sl19peri       166      721.211       38.590      133.277      285.645
sl20clot        95        0.000        0.000        0.000        0.000
sl20peri       214     1029.033       63.696      132.215      387.439

.SH SEE ALSO
reg(5), spideram(1), spidregcnts.

.SH AUTHOR
Tom O. Videen, 2000.
