.TH SPM2IF 1 "30-Nov-2001" "Neuroimaging Lab"
.SH NAME
spm2if - create Interfile header for an SPM image 

.SH SYNOPSIS
spm2if SPM_file

.SH DESCRIPTION
Creates an .ifh file in Interfile format for an SPM image in 
Analyze format. The reason for doing this is to add the atlas origin
to the header, thereby permitting vidi to display SPM T-images with
atlas tracings superimposed.

.nf
The program makes the following assumptions:

1) the atlas origin lies at the center of the image matrix;

2) the pixel order is:
	matrix initial element [1] := left
	matrix initial element [2] := posterior
	matrix initial element [3] := inferior

.fi
If either of these assumptions is wrong, you must edit the .ifh
file to correct the error.

.SH EXAMPLE
.nf
spm2if spmT_0002

.SH RELATED PROGRAMS
spm2img(1)

.SH AUTHOR
Tom Videen, 2001
