.TH SPMHDR 1 "21-Dec-2001" "Neuroimaging Lab"
.SH NAME
spmhdr - dump contents of an SPM hdr file
.SH SYNOPSIS
spmhdr filename

.SH DESCRIPTION
Spmhdr reads an SPM header and writes the contents of all fields.

.nf
Most fields are self explanatory. Datatypes are:
	 0	= unknown
	 1	=  1 bit/pixel
	 2	=  8 bits/pixel
	 4	= 16 bits/pixel (short int)
	 8	= 32 bits/pixel (signed int)
	16	= 32 bits/pixel (float)
	32	= 64 bits/pixel (2 floats)
	64	= 64 bits/pixel (double)

.SH EXAMPLE
spmhdr spmT_0002.hdr

.SH AUTHOR
Tom Videen, 2001.
