.TH SUMATTN7 1 "25-Oct-2001" "Neuroimaging Lab"

.SH NAME
sumattn7 - add or subtract ECAT7 attenuation files

.SH SYNOPSIS
sumattn7 file1,f1 file2,f2 outfile

.nf
where: out = (f1 * file1) + (f2 * file2)

.SH DESCRIPTION
This program adds a pair of ECAT7 attenuation files with scaling factors
applied. Using negative factors permits subtraction; 0.5 for both
scaling factors creates an averaged attenuation.

.SH EXAMPLE
.nf
sumattn7 p5000tr1.a,.5 p5000tr2.a,.5 p5000tr3.a

.SH RELATED PROGRAMS
fpattn7, sino

.SH AUTHOR
Tom O. Videen

