.TH SUMATTN6 1 "26-Feb-2002" "Neuroimaging Lab"

.SH NAME
sumattn6 - add or subtract ECAT6 attenuation files

.SH SYNOPSIS
sumattn6 file1,f1 file2,f2 outfile

.nf
where: out = (f1 * file1) + (f2 * file2)

.SH DESCRIPTION
This program adds a pair of ECAT6 attenuation files with scaling factors
applied. Using negative factors permits subtraction; 0.5 for both
scaling factors creates an averaged attenuation.

.SH EXAMPLE
.nf
sumattn6 p3000tr1.atn,.5 p3000tr2.atn,.5 p3000tr3.atn

.SH RELATED PROGRAMS
sumattn6planes, sumattn7, fpattn6, fpattn7, sino

.SH AUTHOR
Tom O. Videen

