.TH SUMANA 1 "19-Feb-2003" "Neuroimaging Lab"

.SH NAME
sumana - sum multiple Analyze images

.SH SYNOPSIS
sumana outfile infile1 infile2 infile3 ...

.SH DESCRIPTION
This program adds 2 or more Analyze images.

Note that data in our typical Analyze images is saved
as short integers (16-bit) which have a maximum value
of 32767. If your sum exceeds this, your summed image
will appear to have black holes where peaks should be.
You can prevent this by scaling images before summing (anamult).

.SH EXAMPLES
.nf
sumana p6000mprsum p6000mpr1 p6000mpr2 p6000mpr3

.SH RELATED PROGRAMS
ana, anamult, anasum

.SH AUTHOR
Tom O. Videen

