.TH SUMATTN6PLANES 1 "28-Feb-2002" "Neuroimaging Lab"

.SH NAME
sumattn6planes - computes mean attenuation across all planes

.SH SYNOPSIS
sumattn6planes atn_file

.SH DESCRIPTION
This program computes the mean of all 31 planes of ECAT6 attenuation files.
The input file has the extension .atn and the output file will be given
the suffix _sum.atn.

The program was developed for tests of fpattn6 and is undoubtedly
useful only with uniform phantoms.

.SH EXAMPLE
.nf
sumattn6planes p3000tr1

.SH RELATED PROGRAMS
sumattn6, sumattn7, fpattn6, fpattn7, sino

.SH AUTHOR
Tom O. Videen, 2002

