.TH SUMDYNACT 1 "25-Apr-2003" "Neuroimaging Lab"

.SH NAME
sumdynact - sum dynamic image to create 40-sec image

.SH SYNOPSIS
.nf
sumdynact path prefix subject tracer scan ext X Y Z

.SH DESCRIPTION
sumdynact reads a dynamic PET image and uses the specified
center-of-brain to create a time-activity curve.

Unlike sumdyn40, sumdynact uses the default zero time of frame 2
without prompting and does not filter the summed image.

.nf
Note the number of the first frame with counts > background.
Enter "P" to print the curve or Return to continue.
Then enter the rirst frame number for 40-sec integration.

.SH FILES CREATED
.nf
p5000ho1_f10to29.v - 40-sec image 
p5000ho1.r    - headcurve format for makedta
p5000ho1.cnt  - single column of mean count rate/frame

.SH EXAMPLE
sumdynact .. p 5000 ho 1 v 62 66 24

.SH SEE ALSO
sumdyn40(1)

.SH AUTHOR
Tom Videen, 2003
