.TH SUMFDG 1 "08-May-96" "Neuroimaging Lab"
.SH NAME
sumfdg - creates a composite fdg image  
.SH SYNOPSIS
.B sumfdg filename

.SH DESCRIPTION
Sumfdg adds the last 9 frames of a dynamic fdg image.
It assumes the input file name is of the form "p2000fdg1.img"
and creates a file without the "1", i.e., "p2000fdg.img".

The input file must have at least 9 frames (the current standard
acquisitions produce fdg images of either 9 frames (using scanFDGnondyn)
or 43 frames (using scanFDG)).

The output image will have 1 frame, which is renumbered as frame 1.
The output image is scaled by 0.1.

The frame duration is summed for all input frames.

.SH RELATED PROGRAMS
 
sumimg(1), scaleimage(1)

.SH AUTHOR

Tom O. Videen: 1996.
