.TH SUMIMGFRAMES_DECAYCOR 1 "04-Aug-2008" "Neuroimaging Lab"
.SH NAME
sumimgframes_decaycor - creates a composite image  
.SH SYNOPSIS
.B sumimgframes_decaycor infile outfile firstframe lastframe starttime

.SH DESCRIPTION
Sumimgframes adds consecutive frames of a dynamic image.
The output image will have 1 frame, which is renumbered as frame 1.
The frame duration is summed for all input frames.
Currently supports only ECAT 7 format.

Each frame is decay-corrected using the correction factor in the header where:
.nf
factor = exp(lambda*starttime)
lambda = decay constant 
	F-18 = 0.00010529
	C-11 = 0.0005668
	O-15 = 0.005668
starttime = delay - frame time
	delay = time of first summed frame (passed parameter)
	frame time = time of first summed frame (from subheader)

.fi
This differs from sumimgframes which decay corrects using only
the decay-correction factor in the subheader, which typically
decay corrects to the beginning of frame 1 (regardless of whether
or not frame 1 was synchronous with injection).

The output summed image will show a decay-correction factor of 1.

.SH RELATED PROGRAMS
sumimgframes, sumimg, sumimgplanes, sumfdg, scaleimage

.SH AUTHOR
Tom Videen: 2008.
