.TH SUMSINO7 1 "23-Apr-2003" "Neuroimaging Lab"
.SH NAME
sumsino7 - creates a composite sinogram
.SH SYNOPSIS
sumsino7 input_sinogram firstframe lastframe

.SH DESCRIPTION
sumsino7 adds consecutive frames of a dynamic sinogram in
Matrix 7 format (EXACT HR).

The output sinogram will have 1 frame with prompts, delayed,
multiples, net trues and frame duration summed.
Total average corrected singles, total average uncorrected singles,
total coincidence rate, and block uncorrected singles are
averaged over all frames.

.SH NOTE
The resulting sinogram will be identical to one summed using the
CTI interactive sumframes program (on the scanner console) except
CTI's program does not average the coincidence rate (it uses the
rate from the last frame summed).

.SH RELATED PROGRAMS
sino(1), sumimgframes(1)

.SH AUTHOR
Tom Videen, 2003.
