.TH T88PRMLST 1 "30-Aug-96" "Neuroimaging Lab"
.SH NAME
t88prmlst - create prm and lst files from an image and sxr file

.SH SYNOPSIS
t88prmlst imgfile prm lst [sxrfile]

.SH DESCRIPTION
This program creates parameter and imagelist files for a given
image and sxr file.  In particular, these permit t88mean to be
run on a single image to derive an x-scaling factor (see xscale(1)).

.SH EXAMPLES 
.nf
t88prmlst p1700ho1 prm lst
t88prmlst p2000ho1_g2.img prm lst p2000top.sxr
t88prmlst p5000ho1_5b5.v prm lst

.SH SEE ALSO

xscale(1), prm(5), imagelist(5)
.SH AUTHOR

Tom Videen: Aug 1996.
