.TH T88TRSING 1 "13-Nov-96" "Neuroimaging Lab"
.SH NAME
t88trsing - transform single PETT VI or ECAT images into Talairach 1988 atlas space  
using t88trans.
.SH SYNOPSIS
.B t88trsing prm imagelist

.SH DESCRIPTION
This script converts single PET images into single atlas images using
t88trans.

t88sing separates an imagelist into single lists (using /tmp) and then processes
these lists to create a set of single images.  Processes either filtered or
unfiltered images.  Deletes all temporary files on /tmp.

Imagelists and parameter lists are the same as those used by t88trans
but additional format requirements must be met.
Imagelists MUST have each field separated by a SINGLE TAB.
Parameter files must not have additional commented text on the lines
following the parameters: species, tracer, imgfilter, or smg_mode.

Output filenames are created using the parameter and imagelist files and are
always given the extension .t88.

.SH UNFRIENDLINESS
Whereas nearly all other programs do not care what kind of "white space" you use
in the imagelist (spaces or tabs), t88trsing requires a single tab separating each
field.  If you do not have this, you will see the error "set: Syntax error." with
no other explanation.

Avoid blank lines in your imagelist file (such as at the end of the list).

.SH SEE ALSO
t88trans(1), makemap(1), imgmean(1), prm(5), imagelist(5), t88sing(1)

.SH AUTHOR

Tom O. Videen: 1995.
