.TH TAPEDUP 1 "04-Nov-92" "Neuroimaging Lab"

.SH NAME

tapedup - Copy a complete exatape from a local drive to a remote drive.

.SH SYNOPSIS

.B tapedup <remote_host>

.SH DESCRIPTION

This program copies a tape from a local tape drive (/dev/rst1) to one on another Sun (/dev/rst1 on that machine).  Write-protect the tape in the local drive before inserting the tape to be copied, and be sure the the tape in the remote drive is not write-protected.  Also, be sure that you have the correct id of the remote host so that you don't write over someone else's tape.

Both tapes are rewound before initiating the copy, and both tapes are rewound and ejected upon completion of the copy.  

Normal output is (assuming petsun3 is the remote):
.br
	petsun3 is alive
.br
	rewinding local tape
.br
	rewinding tape in petsun3
.br
	copying local tape to petsun3 tape at 
.br
		Fri Jun 26 08:00:00 CDT 1992
.br
	[copytape: can't read input: I/O error]
.br
	rewinding local tape
.br
	rewinding tape in petsun3
.br
	tapedup complete at Fri Jun 26 08:30:10 CDT 1992

A tone is sounded locally upon completion.

Note that tapedup may end with the error message: "copytape: can't read input: I/O error".  This is not unusual and does not mean the copy did not run successfully.  To verify the copy you should always use tapedir (see manual page).

.SH EXAMPLES

tapedup petsun3

.SH SEE ALSO

tapedir(1), copytape, mt, rsh

.SH AUTHOR

Tom O. Videen


