.TH TAPEDIR 1 "24-Jul-96" "Neuroimaging Lab"

.SH NAME

tapedir - Get list of all tar files on a tape.

.SH SYNOPSIS

.B tapedir <device>

.SH DESCRIPTION

This program writes a listing of all tar files on a tape from a local tape drive.  Write-protect the tape before inserting it. The tape is rewound before initiating the listing and rewound and ejected upon completion.

To save a copy of the listing in "mylisting", redirect the output to a file:

	tapedir >& mylisting

To see the listing while saving it to "mylisting" at the same time:

	tapedir | tee mylisting

The default tape device is /dev/nrst1 on SunOS 4.1.3 and /dev/rmt/0hn on SunOS 5.5.
If your tape device is something else, then include the optional device name:

	tapedir /dev/nrst29 | tee mylisting

This program is useful for verifying a tapedup or for checking an archive tape from the PET scanner.  If there are multiple tar files on a tape, a maker such as ">>> TAPE
FILE #2" will separate them.

.nf
Note that the normal completion of tapedir looks like:
	>>> TAPE FILE #3
	tar: [offset 0]: I/O error
	/dev/nrst1 fsf 1 failed: I/O error
	>>> TAPE FILE #4
	tar: No input
	tapedir complete

.fi
Note that tapes made on exacthr (the EXACT HR console) use a different
version of tar (installed here as /usr/local/npg/hrtar).  To get a listing
of these files, use hrtapedir.

.SH SEE ALSO

hrtapedir(1), tapedup(1), copytape, mt, tar

.SH AUTHOR

Tom O. Videen


