.TH TBYTES 1 "18-Jan-95" "Neuro PET Group"

.SH NAME

tbytes - total bytes in an tape archive listing.

.SH SYNOPSIS

tbytes <filename>

.SH DESCRIPTION

This script reads a "tarchive" report file, searches for all lines containing
the word "Archived", and computes a running sum of the bytes in those files.
The total in Megabytes is written along with an estimate of how much space
is left on the tape.  This estimate assumes that the
8505 tape drive will hold approximately 10 GB of data.

The total bytes is only accurate for files which were created using
the output of arcverify (or tarchive, which calls arcverify).

.SH EXAMPLE
.nf
tbytes patient70

	
.SH RELATED PROGRAMS

tarchive

.SH AUTHOR

Tom O. Videen


