.TH utimage 1 "05-Oct-94" "Neuro PET Group"

.SH NAME

utimage - create an unpaired-t image from 6 input images

.SH SYNOPSIS

.B utimage test_mean control_mean

.SH DESCRIPTION

utimage reads 6 files created by t88mean and combines them to create an image of pixel t-values.  A rec file is created with the output file.

.nf
The 6 input files are:
	test.t88     - mean of group 1 (mean1)
	test.sd      - pixel standard deviation for group 1 (sd1)
	test.n       - number of subjects contributing to each pixel for group 1 (n1)
	control.t88  - mean of group 2 (mean2)
	control.sd   - pixel standard deviation for group 2 (sd2)
	control.n    - number of subjects contributing to each pixel for group 2 (n2)

The output files are:
	test-control.t      - unpaired t image (t)
	test-control.t.rec  - rec file summarizing processing
.fi

The complete input filenames should be specified for test and control mean images.  All other filenames are created by stripping of any extension (all characters following the first ".") and appending the extensions indicated (either sd or n).

.SH ALGORITHM

t = 1000 * (mean1-mean2) / sqrt[(sd1*sd1/n1) + (sd2*sd2/n2)]

where the files are defined as above.  Computations are done pixel-by-pixel.  If n1 <= 0, n2 <= 0, sd1 <= 0 or sd2 <= 0, then t is set to 0.

Note:  The pixel t-values are all multipled by 1000 to avoid truncation by software
which handles image arrays as integers for display (e.g., spideram).

.SH RELATED PROGRAMS

t88mean(1), t88sing(1), ptimage(1)

.SH AUTHOR

Tom O. Videen

