.TH VOI2IMG 1 "20-Jul-2009" "Neuroimaging Lab"

.SH NAME
voi2img - create an image from a VOI

.SH SYNOPSIS
voi2img in_image voifile voiname out_image val

.SH DESCRIPTION
This program reads an image plus a VOI defined on that image
and creates a new image in which all pixels are 0 except those 
in the voi, which will be set to 'val.'

The program was created to reductions in extent of an existing
VOI by thresholding the VOI image with some other image.

VOI file must be of the format used by vidi (man vidi_voi).
Input image may be any standard format (ECAT, Analyze, Interfile).
Output image will be in Interfile format.

The input image must have corresponding dimensions and pixel sizes
to the VOI.

.SH EXAMPLE
voi2img atlas.t88 left_putamen.voi left_putamen putamen 1000

.SH SEE ALSO
vidi_voi, vidi

.SH NOTES
The program requires an IDL license.

.SH AUTHOR
Tom Videen
