.TH VOIDAT 1 "27-May-2003" "Neuroimaging Lab"

.SH NAME
voidat - compute mean regional activity for 3D VOIs

.SH SYNOPSIS
.nf
voidat lst voi name out [path]

lst  = list of image files
voi  = voi file created by vidi
name = single region name (must be in voi)
out  = output file 
path = location of image files (optional)

.SH DESCRIPTION
voidat computes the mean regional activity for volumes-of-interest (VOI)
for all images named in the input list. It always reads a single frame (frame 1)
from each input image.

voidat differs from voistat:

Image names are listed rather than created from parameter and imagelists.

VOIs are created by vidi rather than defined by central coordinate and regular shapes.

.SH EXAMPLES
.nf
voidat scan.lst brain.voi left_thalamus left_thalamus.dat
voidat scan.lst brain.voi left_thalamus left_thalamus.dat /tmp/data

.SH EXAMPLE INPUT FILE
.nf
p6139glu1.t88
p6163glu1.t88
p6165glu1.t88
p6166glu1.t88

.SH EXAMPLE OUTPUT FILE
.nf
voidat 2003:05:23  /data/wjp/data5/np558/Composite_9_Unfiltered  Tue May 27 09:58:34 2003
    thalamus   2767 voxels  (brain_g3.voi)
    3198.359   p6139glu1.t88
    2779.816   p6163glu1.t88
    2284.726   p6165glu1.t88
    2633.568   p6166glu1.t88

.SH VOI FILE
See man vidi_voi for a definition of the voi file structure used by voidat.
In practice, these would always be created using vidi.

.SH SEE ALSO
voistat, vstat, vidi, vidi_voi(5)

.SH AUTHOR
Tom O. Videen, 2003.
