.TH VOIHISTOS 1 "09-Dec-2002" "Neuroimaging Lab"

.SH NAME
voihistos - plot histograms of vois in an image

.SH SYNOPSIS
voihistos imagefile voifile

.SH DESCRIPTION
This program plots pixel intensity histograms of csf, white matter,
gray-matter, and blood clot and determine the boundaries of these
4 tissue types.

It requires CT image of brain in Analyze format and a voi file with
5 defined vois with the names: 'csf', 'white', 'gray', 'clot', 'brain'.
Each VOI should contain at least 1000 pixels (more is better).
VOIs are defined using vidi and may contain multiple regions from
multiple slices.

VOI histograms are normalized to a peak of 1000 and plotted in color.
In addition, the program identifies (where 'cnts' = counts per bin
normalized to peak bin counts):

.nf
Brain Min (5%) Threshold = first bin with <= 5% peak cnts
Brain Max (5%) Threshold = last bin +1 with >= 5% peak cnts
Brain/CSF Boundary       = first bin where white cnts >= CSF cnts
Brain/Clot Boundary      = first bin where clot cnts >= gray cnts
.fi

which are used in CT segmentation programs. 

The VOI file must be in the format used by vidi (man vidi_voi).

.SH EXAMPLE
voihistos p5067seg4.img p5067brain.voi

.SH NOTES
The program requires an IDL license.

.SH SEE ALSO
vidi, vidi_voi, voihisto

.SH AUTHOR
Tom Videen, Feb, 1999.
