.TH VOIHISTO 1 "09-Dec-2002" "Neuroimaging Lab"

.SH NAME
voihisto - plot histogram of a voi in an image

.SH SYNOPSIS
voihisto imagefile voifile voiname

.SH DESCRIPTION
This program plots pixel intensity histograms of any single
VOI on a particular histogram. It also computes the midpoint
of the distribution using the midpoint at half-maximum.

The program was originally compiled to estimate mean
CSF intensity from a liberally thresholded VOI on the ventricles
of an MPRAGE image.

The VOI file must be of the format used by vidi (man vidi_voi).

.SH EXAMPLE
voihisto p5067mpr2.img p5067mpr2.voi csf

.SH SEE ALSO
voihistos, vidi_voi, vidi

.SH NOTES
The program requires an IDL license.

.SH AUTHOR
Tom Videen
