.TH VOIMAKE 1 "22-Sep-2000" "Neuroimaging Lab"

.SH NAME
voimake - create VOI file using thresholded objects

.SH SYNOPSIS
.nf
voimake imgfile voifile voi_name low_thresh high_thresh
	imgfile  = image filename
	voifile  = voi filename
	voiname  = name of voi
	low_thresh = minimum
	high_thresh = maximum

.SH DESCRIPTION
Voimake reads an image and creates a VOI file (in vidi_voi format).
All pixels with low_thresh <= value <= high_threshold will be
included in the VOI.

This voi file can be used by either vidi or vstat for further processing.
It expedites the creation of voi files from objects created
using vidivoi.

.SH EXAMPLE
.nf
voimake putamen.img left_putamen.voi left_putamen 4 4

.SH SEE ALSO
vidi(1), vstat(1), vidivoi(1), vidi_voi(5)

.SH AUTHOR
Tom Videen, 2000.
