#!/bin/csh

set libraries = `ls -d [a-z]* | grep "\/" | grep "^lib" | cut -f1 -d/`
foreach i ($libraries)
	cd ~/src/$i
	if (-e Makefile) then
		echo "Makefile exists: $i"
		echo "------------------------------"
		set data = "$<"
	else
		echo $i
		echo "------------------------------"
		ls
		echo "Build?"
		set data = "$<"
		if ($data == '') then
			cout
			make
			echo "Release?"
			set data = "$<"
			if ($data == '') make release
			echo "Clean?"
			set data = "$<"
			if ($data == '') clean
		endif
	endif
	cd ..
end

