VER = 1.2
HEADERS = Array.h	\
		Displacement.h	\
		DistanceMeasure.h	\
		Image.h	\
		Log.h	\
		Makefile	\
		Optimizer.h	\
		Smoother.h	\
		Solver.h	\
		Solver.old.h	\
		StopRule.h	\
		UpdateRule.h	\
		arrays.h	\
		bspline.h	\
		curvature.h	\
		defs.h	\
		diffusive.h	\
		elastic.h	\
		flirt++.h	\
		flirt.h	\
		imagetools.h	\
		io.h	\
		io3d.h	\
		tools.h

checkout:
	co ${HEADERS}

checkin:
	ci ${HEADERS}

lock:
	co -l ${HEADERS}

sync:
	ci -f -r${VER} ${HEADERS}

