C$Header: /home/npggw/tom/src/betadta/RCS/bldsecs.f,v 1.1 1993/12/02 22:22:34 tom Exp $
C$Log: bldsecs.f,v $
c Revision 1.1  1993/12/02  22:22:34  tom
c Initial revision
c
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C  MODULE:       BLDSECS.FTN
C  Functions:    SECS
C                MINUTES
C
C  Author:       Tom O. Videen
C  Date:         22-Jun-86
C  Written For:  BLOOD
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C  Function:     SECS
C
C  Intent:
C     Converts DTIME from the form "MIN.SEC" to seconds.
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
      FUNCTION SECS(DTIME)
C
      REAL      SECS,DTIME,TIME,MIN,SEC
			CHARACTER*256	RCSHEADER
			RCSHEADER = "$Id"
C
      TIME = ABS(DTIME)
      MIN = FLOAT(INT(TIME))
      SEC = 100.*(TIME-FLOAT(INT(TIME)))
      SECS = 60.*MIN + SEC
C
      RETURN
      END
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C  Function:     MINUTES
C
C  Intent:
C     Converts DTIME from seconds to the form "MIN.SEC"
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
      FUNCTION MINUTES(DTIME)
C
      REAL      MINUTES,DTIME,MIN,SEC
C
      MIN = FLOAT(INT(DTIME/60.))
      SEC = AMOD(DTIME,60.)
      MINUTES = MIN + 0.01*SEC
C
      RETURN
      END
