#!/bin/csh
#   Name:   makedta
#   Date:   Dec-95
#   Author: Tom Videen
#   Use:    Create dta files for metproc or petproc.
 
setenv LM_LICENSE_FILE /usr/local/pkg/idl/license.dat
setenv IDL_DEVICE X
setenv IDL_DIR /usr/local/pkg/idl
#setenv IDL_PATH +/usr/local/lib/idl:+/usr/local/pkg/idl/lib:+/usr/local/npg/idl
setenv IDL_PATH +/usr/local/lib/idl:+/usr/local/pkg/idl/lib:+/data/npggw/idl/npg/makedta
#setenv IDL_STARTUP /usr/local/npg/idl/MAKEDTA
/usr/bin/X11/xrdb -load $IDL_DIR/Idl
$IDL_DIR/bin/idl
