#!/bin/csh
#	Name:	betadcv
#	Date:	Dec-95
#	Author:	Tom Videen
#	Intent:	Deconvolve, decay-correct and calibrate a blood curve (crt)

set BINPATH = /home/petsun19/tom/src/betadcv
if ($#argv != 1) then
	echo " usage: betadcv scanname"
	echo "  i.e.: betadcv p5000ho1"
	exit 1
endif

set crt = $1.crt
set dcv = $1.dcv
if (! -e ${crt}) then
	echo "Input file $crt does not exist"
	exit 1
endif

${BINPATH}/betadcv.bin ${crt} ${dcv}
