#!/usr/bin/ksh 

#-------------------------------
#checks if a cpu is reachable
# $1 = hostname
#returns 1 if alive, 0 if not
#-------------------------------

#--------------------------------
#set environment variables
#--------------------------------
. $HOME/.idlspm/.global.ksh

timeout=5
ping_os=$OS
host=$1

cmd=`echo /usr/sbin/ping $host $timeout`
grepstring=`echo "is alive"`
if test $ping_os = Linux 
	then cmd=`echo /bin/ping $host -q -w $timeout`
	#grepstring=`echo 100% packet loss`
	#grepstring=`echo "round-trip"`
	grepstring=`echo "min/avg/max/mdev"`
fi

response=0
reply=`$cmd 2>>/dev/null | grep "$grepstring" `

if (test ${#reply} -gt 0) then 
	response=1
fi

echo $response

exit
