.TH FILETYPES 5 "27-May-94" "Neuroimaging Lab"
.SH NAME
filetypes \- brief summary of in-house file types

.SH DESCRIPTION

This man page contains a list of filetypes created and used by in-house software.
Additional information on some of the filetypes can be found in other man pages.

.SH KEY
.nf
<output from or created by>
[input to or used by]

.SH IMAGE FILES
.ta 1.0i 1.2i 1.4i
.nf
PETT VI	-	( , c, mcp, fcp, fip, ...)
ECAT	-	(img)
MRI	-	(ima)
ANALYZE	-	(img, hdr)
Atlas	-	(smg, hd6, t88, dif, sd, n)
			<hd6mean, t88mean>

.SH OTHER FILES
.ta 0.5i 0.7i 0.9i
.nf
sped	-	Statistical Package EDitor (rows & cols of numbers)
			<sped>
hdr	-	suppl HeaDeR file for PET images (metab conversion factors)
			<metproc, petproc>
			[spideram, voimean]
reg	-	REGion of interest file
			<spideram, locate>
trg	-	T-ReGion file
			<rapture>
sxr	-	Skull X-Ray file
			<xray (sarplocs)>
			[locate, t88mean, hd6mean]
ras	-	RASter file
pic	-	PIC file
			<MAC digitizer>
ras	-	Sun RASter file (xv)
rgt	-	ReGion sTatistics
			<spideram, voimean>
pk*	-	PeaK listing
			<peakid	-	>
3sp	-	af3d Sorted Positive peaks
3sn	-	af3d Sorted Negative peaks
			<af3d>
			[gammaz, petdat]
gam	-	GAMmaz output	-	
			<gammaz>
atl	-	ATLas region file
			[locate]
ats	-	ATlaS region file (old version)
wel	-	WELl counter counts (calibration file)
			<ed>
plt	-	headcurve PLoT data file
			<headCurve>
			[crt2crv]
crt	-	raw blood sucker CuRve file
			<automated blood sampler PC>
			[crt2crv]
crv	-	blood + head CuRVe file
			<crt2crv (PETT VI automated blood sampler)>
			[betadta]
dta	-	blood curve DaTA file
			<blood, betadta>
			[metproc, petproc]
pdf	-	Pie Data File
			[piecreate]
pie	-	PIE file
			<piecreate>
tis	-	TISsue activity curve
prm	-	PaRaMeter file
			<ed>
lst	-	SUBject LiST
			<ed>
sub	-	SUBject LiST
			<ed>
rec	-	RECord of image processing
			<all programs which create image files>
dat	-	DATa file (e.g., 953b scan log; pre-1988 blood curves)
			<ed>
log	-	LOG files (e.g., individual scans)
			<ed>
gba	-	GloBal Averages
gbe	-	GloBal averages for Em-reconstructed images
			<globavg>
fln	-	FiLe iNfo
			<sarpfln>
			[headman]
3dp	-	af3D Positive peaks
3dn	-	af3D Negative peaks
            <af3d>
grp	-	GRouP of scans on which to compute a mat file
			<ed>
			[matrms]
mat	-	MATrix file containing realignment parameters
			<matrms>
wrp	-	file of WaRP parameters
			<wrpgen>

.SH AUTHOR
Tom O. Videen
