.TH HDR 5 "25-May-2001" "Neuroimaging Lab"
.SH NAME
HDR files are created by metproc and petproc and used by spideram, hd6mean, and other programs requiring PET counts to be converted to either metabolic or tissue activity values.

.SH FILE DESCRIPTION
HDR files are 256-bytes containing the following information:

.nf
 Byte  Information               Variable Name  Format
----- -----------                -------------  ------
 1     Scanner Name                 (SCANNER)     [A14]
 8     Image File Name              (SCANNAME)    [A8]
12     Scan Date                    (SCANDATE)    [A8]
16     Number of Slices             (SLICES)      [I*2]
17     Scan Time (seconds)          (SCANTIME)    [I*2]
18     Compound                     (COMPOUND)    [A10]
23     Reconstruction Filter        (FILTER)      [A12]
29     Reconstruction Type          (RCONTYPE)    [I*2]
30     Resolution (0=LO; 1=HI)      (RESOLUTION)  [I*2]
31     Date Processed               (PROCDATE)    [A8]
35     Processed by (Initials)      (INITIALS)    [A4]
37     Type of File                 (NTYPE)       [I*2]
38     [unused]                                   [I*2]
39     PIE File Name                (PIENAME)     [A8]
43     Blood Counts from Injection  (TOTALCNTS)   [REAL]
45     Blood Counts from Scan Start (SCANCNTS)    [REAL]
47     Start Time of Scan (sec)     (SCANST)      [REAL]
49     Length of Scan (sec)         (SCANLEN)     [REAL]
51     Inter-Slice Time             (FRAMELEN)    [REAL]
53     Decay Constant (1/sec)       (TAU)         [REAL]

7-Slice Images 
--------------------------------------------------------
55     PETT Conversion Factor       (PETTCONV)    [REAL]
57     Flow Coefficient             (AFLOW)       [REAL]
59     Flow Coefficient             (BFLOW)       [REAL]
61     Volume Factor                (BVFACTOR)    [REAL]
63     Oxygen Coefficient           (AOXYGEN)     [REAL]
65     Oxygen Coefficient           (BOXYGEN)     [REAL]
67     Oxygen Coefficient           (AWATER)      [REAL]
69     Oxygen Coefficient           (BWATER)      [REAL]
71     Total Oxygen Counts          (O2CNTS)      [REAL]
73     Oxygen Content of Blood      (OXYCONT)     [REAL]
75     Decay-Corrected PETT Conversion Factor     [REAL]

Odd Slices of 14-Slice Images:    (second array element)
--------------------------------------------------------
77     PETT Conversion Factor       (PETTCONV)    [REAL]
79     Flow Coefficient             (AFLOW)       [REAL]
81     Flow Coefficient             (BFLOW)       [REAL]
83     Volume Factor                (BVFACTOR)    [REAL]
85     Oxygen Coefficient           (AOXYGEN)     [REAL]
87     Oxygen Coefficient           (BOXYGEN)     [REAL]
89     Oxygen Coefficient           (AWATER)      [REAL]
91     Oxygen Coefficient           (BWATER)      [REAL]
93     Total Oxygen Counts          (O2CNTS)      [REAL]
95     Oxygen Content of Blood      (OXYCONT)     [REAL]
97     Decay-Corrected PETT Conversion Factor     [REAL]
99     Pie Slope                    (PIESLOPE)    [REAL]
101    PETT Efficiency Factor       (EFACTOR)     [REAL]
103-128   Unused

.SH RELATED PROGRAMS
metproc(1), petproc(1), spideram(1), hd6mean(1)

.SH AUTHOR
Tom O. Videen
