.TH RGT 5 "04-Feb-94" "Neuroimaging Lab"
.SH NAME
reg \- regional values file

.SH DESCRIPTION
An rgt file contains a list mean values from applying a set of ROIs to a set of PET images. 

The file begins with 3 header lines that are followed by the list of points.

.nf
\fILine 1\fP:

    integer string

where:
    integer = file type
        20     = created by voimean 
    string  = type of processing
        none
        cbf
        cbv
        oef
        cmro2
        corrected_tissue_activity
        uncorrected_tissue_activity

\fILine 2\fP:

    strings

where this will typically be:
    string = program that created this file
    real   = version number of that program
    string = run date
    string = user id
    string = short reg filename used in creating this file
    string = short image filename used in creating this file

\fILine 3\fP:

    integer integer

where:
    integer = number of rows
    integer = number of columns

\fILines 4+\fP:

    real [real ...]

where:
    real  = mean ROI values

\fIEnd of File\fP:
    prm
    [contents of parameter file used to create this file]
    endprm

.SH EXAMPLE

.nf
20   hd6
voimean  1.1  tom  p2000.reg  p2000ho1.img
3
left_prefrontal_cx   4.78   51.16   47.68
globus_pallidus      4.86   67.83   56.74
md_thalamus          4.03   61.56   66.68    

.SH SEE ALSO
locate, voimean, reg

.SH AUTHORS
Tom Videen, Tom Yang
