.TH VIDI_VOI 1 "26-Apr-2005" "Neuroimaging Lab"

.SH NAME
vidi_voi - volume-of-interest file for vidi

.SH DESCRIPTION
A voi file contains the definitions of volumes-of-interest in image space.
Four types of VOI definitions are used: circle, rectangle, trace and threshold.

Planes and frames are indexed from 1 while pixel x, y-coordinates are indexed from 0.
Hence, for a 128x128 image with multiple planes and frames, the exact center of
the first plane of the first frame will be defined by:
.nf
	frame = 1
	plane = 1
	x = 63.5
	y = 63.5
.fi
 
The location in brain-space of plane=1 and x,y=(0,0) will be
at the left, anterior, superior corner of the image volume.

Note that for VOIs drawn as outlines (circle, rectangle and trace), the thin
line drawn on the image appears at the lower or right side of a pixel when the image
is zoomed. This can cause VOIs to appear misplaced on zoomed images. If in doubt,
create a single pixel VOI and note how it is positioned using statistics on a
clear peak.
For VOIs defined by thresholds, the entire pixel is filled in.

Within each VOI file, all VOIs with the same name MUST be grouped together
and ordered sequentially by slice number. Files created by vidi are sorted as they
are created.

.SH SEE ALSO
VOI files with this format may be used with vstat,
voi_enlarge, voihisto, and voihistos. 
For a description of other VOI file formats, see 'man voi'.

.SH EXAMPLE
.ta 0.1i 2.0i 2.5i 2.8i 3.7i 4.0i
.nf
VOI		file id
9802		file version
0		0
0		0
0.000000		0
4		number of vois (which may comprise a single VOI)
0 0 0		0
circle_10_10_5pix		name of first VOI
0		type: 0=circle
0		orient: 0=transverse
1		plane
5.000000		radius (pixels)
1		number of points
1 2 3 		size: dimensions=1, size=2x1 (1 2D-coordinate), (3=type long)
9 9		coordinates
rectangle_10_10_15_15	name of second VOI
1		type: 1=rectangle
0		orient: 0=transverse
1		plane
0.000000		radius 
2		number of points
2 2 2 		size: dimensions=2, size=2x2 (2 2D-coordinates)
9 9		coordinates
14 14
trace_10_10_15_15		name of third VOI
2		type: 2=trace
0		orient: 0=transverse
1		plane
0.000000		radius
25		number of points
2 2 100 		size: dimensions=2, size=2x100 (100 2D-coordinates)
9 9		coordinates
9 10
9 11
9 12
9 13
9 14
10 14
11 14
12 14
13 14
14 14
14 13
14 12
14 11
14 10
14 9
13 9
12 9
11 9
10 9
9 9
0 0
 . . .
0 0
threshold_64_64		name of fourth VOI
3		type: 3=threshold
0		orient: 0=transverse
24		plane
0.000000		radius
4		number of points
2 2 100 		size: dimensions=2, size=2x100 (100 2D-coordinates)
63 63
63 64
64 63
64 64
0 0
 . . .
0 0
			name (blank indicating the end of file)
0		type (last selected)
0		0
0		0
0.000000		0
0		0
0 0 0 		0
ENDFILE
