#!/bin/csh
set PID = $1
set X   = $2
set Y   = $3
set Z   = $4
set THR = 800

unalias rm
while ($THR > 300)
	echo ------------------------------------------
	echo Threshold $THR
	volseg ma${PID}_ratio_1.img b${PID}_s$THR.img $X $Y $Z $THR 20000
	voimake b${PID}_s$THR.img infarct_s$THR.voi infarct $THR  20000
	rm b${PID}_s$THR.*
	set THR = `echo $THR - 50 | bc`
end
exit

set PID = v7992
set THR = 800
while ($THR > 300)
	echo ------------------------------------------
	echo Threshold $THR
	contrahisto ma${PID}_ratio_1.img infarct_s$THR.voi infarct 2000
	set THR = `echo $THR - 50 | bc`
end

