#!/bin/csh
set PID = $1
set THRESH = $2
set SEED = "$3 $4 $5"
set SEED2 = "$6 $7 $8"
cd ~/Vectors/$PID
rm ${PID}_vol.i??
volsegcond ma${PID}_ratio_1.img ma${PID}_ratio_2.img ${PID}_vol.img $THRESH $SEED $SEED2

