/*$Id: ecatRts_xdr.c,v 1.3 1996/09/25 16:28:32 tom Exp $*/
/*$Log: ecatRts_xdr.c,v $
 *Revision 1.3  1996/09/25 16:28:32  tom
 *build in Solaris 2
 *
 * Revision 1.2  1994/03/03  17:24:51  ty7777
 * Change from if to header.
 **/

/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <rpc/rpc.h>
#include "ecatRts.h"
/* @(#)ecatRts.x	2.2 9/20/91 */

#ifndef lint
static char     rcsid[] = "$Header: /home/npggw/tom/src/libcti/RCS/ecatRts_xdr.c,v 1.3 1996/09/25 16:28:32 tom Exp $";
#endif

bool_t
xdr_RTS_FUNCTIONS (xdrs, objp)
	XDR            *xdrs;

	RTS_FUNCTIONS  *objp;
{
	if (!xdr_enum (xdrs, (enum_t *) objp)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_RTS_INFO_FUNCTIONS (xdrs, objp)
	XDR            *xdrs;

	RTS_INFO_FUNCTIONS *objp;
{
	if (!xdr_enum (xdrs, (enum_t *) objp)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_XMAIN_HEAD (xdrs, objp)
	XDR            *xdrs;

	XMAIN_HEAD     *objp;
{
	if (!xdr_opaque (xdrs, objp->original_file_name, 20)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->sw_version)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->data_type)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->system_type)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->file_type)) {
		return (FALSE);
	}
	if (!xdr_opaque (xdrs, objp->node_id, 10)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->scan_start_day)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->scan_start_month)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->scan_start_year)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->scan_start_hour)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->scan_start_minute)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->scan_start_second)) {
		return (FALSE);
	}
	if (!xdr_opaque (xdrs, objp->isotope_code, 8)) {
		return (FALSE);
	}
	if (!xdr_float (xdrs, &objp->isotope_halflife)) {
		return (FALSE);
	}
	if (!xdr_opaque (xdrs, objp->radiopharmaceutical, 32)) {
		return (FALSE);
	}
	if (!xdr_float (xdrs, &objp->gantry_tilt)) {
		return (FALSE);
	}
	if (!xdr_float (xdrs, &objp->gantry_rotation)) {
		return (FALSE);
	}
	if (!xdr_float (xdrs, &objp->bed_elevation)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->rot_source_speed)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->wobble_speed)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->transm_source_type)) {
		return (FALSE);
	}
	if (!xdr_float (xdrs, &objp->axial_fov)) {
		return (FALSE);
	}
	if (!xdr_float (xdrs, &objp->transaxial_fov)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->transaxial_samp_mode)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->coin_samp_mode)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->axial_samp_mode)) {
		return (FALSE);
	}
	if (!xdr_float (xdrs, &objp->calibration_factor)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->calibration_units)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->compression_code)) {
		return (FALSE);
	}
	if (!xdr_opaque (xdrs, objp->study_name, 12)) {
		return (FALSE);
	}
	if (!xdr_opaque (xdrs, objp->patient_id, 16)) {
		return (FALSE);
	}
	if (!xdr_opaque (xdrs, objp->patient_name, 32)) {
		return (FALSE);
	}
	if (!xdr_opaque (xdrs, objp->patient_sex, 1)) {
		return (FALSE);
	}
	if (!xdr_opaque (xdrs, objp->patient_age, 10)) {
		return (FALSE);
	}
	if (!xdr_opaque (xdrs, objp->patient_height, 10)) {
		return (FALSE);
	}
	if (!xdr_opaque (xdrs, objp->patient_weight, 10)) {
		return (FALSE);
	}
	if (!xdr_opaque (xdrs, objp->patient_dexterity, 1)) {
		return (FALSE);
	}
	if (!xdr_opaque (xdrs, objp->physician_name, 32)) {
		return (FALSE);
	}
	if (!xdr_opaque (xdrs, objp->operator_name, 32)) {
		return (FALSE);
	}
	if (!xdr_opaque (xdrs, objp->study_description, 32)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->acquisition_type)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->bed_type)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->septa_type)) {
		return (FALSE);
	}
	if (!xdr_opaque (xdrs, objp->facility_name, 20)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->num_planes)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->num_frames)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->num_gates)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->num_bed_pos)) {
		return (FALSE);
	}
	if (!xdr_float (xdrs, &objp->init_bed_position)) {
		return (FALSE);
	}
	if (!xdr_vector (xdrs, (char *) objp->bed_offset, 15, sizeof (float), xdr_float)) {
		return (FALSE);
	}
	if (!xdr_float (xdrs, &objp->plane_separation)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->lwr_sctr_thres)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->lwr_true_thres)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->upr_true_thres)) {
		return (FALSE);
	}
	if (!xdr_float (xdrs, &objp->collimator)) {
		return (FALSE);
	}
	if (!xdr_opaque (xdrs, objp->user_process_code, 10)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->acquisition_mode)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_XSCAN_SUB (xdrs, objp)
	XDR            *xdrs;

	XSCAN_SUB      *objp;
{
	if (!xdr_short (xdrs, &objp->data_type)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->dimension_1)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->dimension_2)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->smoothing)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->processing_code)) {
		return (FALSE);
	}
	if (!xdr_float (xdrs, &objp->sample_distance)) {
		return (FALSE);
	}
	if (!xdr_float (xdrs, &objp->isotope_halflife)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->frame_duration_sec)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->gate_duration)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->r_wave_offset)) {
		return (FALSE);
	}
	if (!xdr_float (xdrs, &objp->scale_factor)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->scan_min)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->scan_max)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->prompts)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->delayed)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->multiples)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->net_trues)) {
		return (FALSE);
	}
	if (!xdr_vector (xdrs, (char *) objp->cor_singles, 16, sizeof (float), xdr_float)) {
		return (FALSE);
	}
	if (!xdr_vector (xdrs, (char *) objp->uncor_singles, 16, sizeof (float), xdr_float)) {
		return (FALSE);
	}
	if (!xdr_float (xdrs, &objp->tot_avg_cor)) {
		return (FALSE);
	}
	if (!xdr_float (xdrs, &objp->tot_avg_uncor)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->total_coin_rate)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->frame_start_time)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->frame_duration)) {
		return (FALSE);
	}
	if (!xdr_float (xdrs, &objp->loss_correction_fctr)) {
		return (FALSE);
	}
	if (!xdr_vector (xdrs, (char *) objp->phy_planes, 8, sizeof (int), xdr_int)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_XIMAGE_SUB (xdrs, objp)
	XDR            *xdrs;

	XIMAGE_SUB     *objp;
{
	if (!xdr_short (xdrs, &objp->data_type)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->num_dimensions)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->dimension_1)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->dimension_2)) {
		return (FALSE);
	}
	if (!xdr_float (xdrs, &objp->x_origin)) {
		return (FALSE);
	}
	if (!xdr_float (xdrs, &objp->y_origin)) {
		return (FALSE);
	}
	if (!xdr_float (xdrs, &objp->recon_scale)) {
		return (FALSE);
	}
	if (!xdr_float (xdrs, &objp->quant_scale)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->image_min)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->image_max)) {
		return (FALSE);
	}
	if (!xdr_float (xdrs, &objp->pixel_size)) {
		return (FALSE);
	}
	if (!xdr_float (xdrs, &objp->slice_width)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->frame_duration)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->frame_start_time)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->slice_location)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->recon_start_hour)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->recon_start_minute)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->recon_start_sec)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->recon_duration)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->filter_code)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->scan_matrix_num)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->norm_matrix_num)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->atten_cor_matrix_num)) {
		return (FALSE);
	}
	if (!xdr_float (xdrs, &objp->image_rotation)) {
		return (FALSE);
	}
	if (!xdr_float (xdrs, &objp->plane_eff_corr_fctr)) {
		return (FALSE);
	}
	if (!xdr_float (xdrs, &objp->decay_corr_fctr)) {
		return (FALSE);
	}
	if (!xdr_float (xdrs, &objp->loss_corr_fctr)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->processing_code)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->quant_units)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->recon_start_day)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->recon_start_month)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->recon_start_year)) {
		return (FALSE);
	}
	if (!xdr_float (xdrs, &objp->ecat_calibration_fctr)) {
		return (FALSE);
	}
	if (!xdr_float (xdrs, &objp->well_counter_cal_fctr)) {
		return (FALSE);
	}
	if (!xdr_vector (xdrs, (char *) objp->filter_params, 6, sizeof (float), xdr_float)) {
		return (FALSE);
	}
	if (!xdr_opaque (xdrs, objp->annotation, 40)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_XNORM_SUB (xdrs, objp)
	XDR            *xdrs;

	XNORM_SUB      *objp;
{
	if (!xdr_short (xdrs, &objp->data_type)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->dimension_1)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->dimension_2)) {
		return (FALSE);
	}
	if (!xdr_float (xdrs, &objp->scale_factor)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->norm_hour)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->norm_minute)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->norm_second)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->norm_day)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->norm_month)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->norm_year)) {
		return (FALSE);
	}
	if (!xdr_float (xdrs, &objp->fov_source_width)) {
		return (FALSE);
	}
	if (!xdr_float (xdrs, &objp->ecat_calib_factor)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_XATTEN_SUB (xdrs, objp)
	XDR            *xdrs;

	XATTEN_SUB     *objp;
{
	if (!xdr_short (xdrs, &objp->data_type)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->attenuation_type)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->dimension_1)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->dimension_2)) {
		return (FALSE);
	}
	if (!xdr_float (xdrs, &objp->scale_factor)) {
		return (FALSE);
	}
	if (!xdr_float (xdrs, &objp->x_origin)) {
		return (FALSE);
	}
	if (!xdr_float (xdrs, &objp->y_origin)) {
		return (FALSE);
	}
	if (!xdr_float (xdrs, &objp->x_radius)) {
		return (FALSE);
	}
	if (!xdr_float (xdrs, &objp->y_radius)) {
		return (FALSE);
	}
	if (!xdr_float (xdrs, &objp->tilt_angle)) {
		return (FALSE);
	}
	if (!xdr_float (xdrs, &objp->attenuation_coeff)) {
		return (FALSE);
	}
	if (!xdr_float (xdrs, &objp->sample_distance)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_CREF_args (xdrs, objp)
	XDR            *xdrs;

	CREF_args      *objp;
{
	if (!xdr_string (xdrs, &objp->file_name, 64)) {
		return (FALSE);
	}
	if (!xdr_XMAIN_HEAD (xdrs, &objp->mhead)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->data_size)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_DPLN_args (xdrs, objp)
	XDR            *xdrs;

	DPLN_args      *objp;
{
	if (!xdr_int (xdrs, &objp->log_plane)) {
		return (FALSE);
	}
	if (!xdr_vector (xdrs, (char *) objp->phy_plane, 6, sizeof (int), xdr_int)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_DFRM_args (xdrs, objp)
	XDR            *xdrs;

	DFRM_args      *objp;
{
	if (!xdr_int (xdrs, &objp->nframes)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->delay)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->duration)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->nsegs)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_MODL_args (xdrs, objp)
	XDR            *xdrs;

	MODL_args      *objp;
{
	if (!xdr_int (xdrs, &objp->model)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->number_of_rings)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_CFRM_args (xdrs, objp)
	XDR            *xdrs;

	CFRM_args      *objp;
{
	if (!xdr_int (xdrs, &objp->frame)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->delay)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->duration)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_CONF_args (xdrs, objp)
	XDR            *xdrs;

	CONF_args      *objp;
{
	if (!xdr_int (xdrs, &objp->config)) {
		return (FALSE);
	}
	if (!xdr_float (xdrs, &objp->pile_up_factor)) {
		return (FALSE);
	}
	if (!xdr_float (xdrs, &objp->plane_factor)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_STRT_args (xdrs, objp)
	XDR            *xdrs;

	STRT_args      *objp;
{
	if (!xdr_int (xdrs, &objp->numberFrames)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->acqType)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_RECT_args (xdrs, objp)
	XDR            *xdrs;

	RECT_args      *objp;
{
	if (!xdr_int (xdrs, &objp->frame)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->plane)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->segment)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->data)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->startView)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->endView)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_STOR_args (xdrs, objp)
	XDR            *xdrs;

	STOR_args      *objp;
{
	if (!xdr_string (xdrs, &objp->filename, ~0)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->frame)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->matframe)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->bed)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_ASTR_args (xdrs, objp)
	XDR            *xdrs;

	ASTR_args      *objp;
{
	if (!xdr_string (xdrs, &objp->file_name, 64)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->auto_store)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_GLOG_args (xdrs, objp)
	XDR            *xdrs;

	GLOG_args      *objp;
{
	if (!xdr_string (xdrs, &objp->filename, ~0)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->frame)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->plane)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->segment)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->data)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->bed)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_GIMI_args (xdrs, objp)
	XDR            *xdrs;

	GIMI_args      *objp;
{
	if (!xdr_int (xdrs, &objp->frame)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->plane)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->segment)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->data)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->bed)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_SNGL_args (xdrs, objp)
	XDR            *xdrs;

	SNGL_args      *objp;
{
	if (!xdr_int (xdrs, &objp->start_bucket)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->end_bucket)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->frequency)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->timeout)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->num_ipcs)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_RBLK_args (xdrs, objp)
	XDR            *xdrs;

	RBLK_args      *objp;
{
	if (!xdr_string (xdrs, &objp->filename, ~0)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->block_number)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_WBLK_args (xdrs, objp)
	XDR            *xdrs;

	WBLK_args      *objp;
{
	if (!xdr_string (xdrs, &objp->filename, ~0)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->block_number)) {
		return (FALSE);
	}
	if (!xdr_opaque (xdrs, objp->wblk, 512)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_GIMI_resp (xdrs, objp)
	XDR            *xdrs;

	GIMI_resp      *objp;
{
	if (!xdr_int (xdrs, &objp->time)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->start_time)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->nproj)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->nview)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->minval)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->maxval)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->prompts)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->delayeds)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->multiples)) {
		return (FALSE);
	}
	if (!xdr_vector (xdrs, (char *) objp->corrected_sing, 64, sizeof (int), xdr_int)) {
		return (FALSE);
	}
	if (!xdr_vector (xdrs, (char *) objp->uncorrected_sing, 64, sizeof (int), xdr_int)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->total_ipc_prompts)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->total_ipc_delayeds)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->total_ipc_multiples)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->status)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_GLOG_resp (xdrs, objp)
	XDR            *xdrs;

	GLOG_resp      *objp;
{
	if (!xdr_int (xdrs, &objp->time)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->start_time)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->minval)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->maxval)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->prompts)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->delayeds)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->multiples)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->net_trues)) {
		return (FALSE);
	}
	if (!xdr_float (xdrs, &objp->dtcor)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->status)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_INFO_resp (xdrs, objp)
	XDR            *xdrs;

	INFO_resp      *objp;
{
	if (!xdr_int (xdrs, &objp->acq_status)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->total_time)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->prompt_events)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->delayed_events)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->multiple_events)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->current_frame)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->total_frames)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->frame_time)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->frame_end_time)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->scan_end_time)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->singles_Kcps_corrected)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->singles_Kcps_uncorrected)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->total_ipc_prompt_rate)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->total_ipc_delayed_rate)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->total_ipc_multiple_rate)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->contig_disk_space)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_RBLK_resp (xdrs, objp)
	XDR            *xdrs;

	RBLK_resp      *objp;
{
	if (!xdr_int (xdrs, &objp->status)) {
		return (FALSE);
	}
	if (!xdr_opaque (xdrs, objp->rblk, 512)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_RMHD_resp (xdrs, objp)
	XDR            *xdrs;

	RMHD_resp      *objp;
{
	if (!xdr_int (xdrs, &objp->status)) {
		return (FALSE);
	}
	if (!xdr_XMAIN_HEAD (xdrs, &objp->xmain_head)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_WMHD_args (xdrs, objp)
	XDR            *xdrs;

	WMHD_args      *objp;
{
	if (!xdr_string (xdrs, &objp->file_name, ~0)) {
		return (FALSE);
	}
	if (!xdr_XMAIN_HEAD (xdrs, &objp->xmain_head)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_RSHD_args (xdrs, objp)
	XDR            *xdrs;

	RSHD_args      *objp;
{
	if (!xdr_string (xdrs, &objp->file_name, ~0)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->matnum)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_RSHD_resp (xdrs, objp)
	XDR            *xdrs;

	RSHD_resp      *objp;
{
	if (!xdr_int (xdrs, &objp->status)) {
		return (FALSE);
	}
	if (!xdr_opaque (xdrs, objp->rhdat, 512)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_WSHD_args (xdrs, objp)
	XDR            *xdrs;

	WSHD_args      *objp;
{
	if (!xdr_string (xdrs, &objp->file_name, ~0)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->matnum)) {
		return (FALSE);
	}
	if (!xdr_opaque (xdrs, objp->whdat, 512)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_RDAT_args (xdrs, objp)
	XDR            *xdrs;

	RDAT_args      *objp;
{
	if (!xdr_string (xdrs, &objp->file_name, ~0)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->matnum)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_RDAT_resp (xdrs, objp)
	XDR            *xdrs;

	RDAT_resp      *objp;
{
	if (!xdr_int (xdrs, &objp->status)) {
		return (FALSE);
	}
	if (!xdr_bytes (xdrs, (char **) &objp->rdat.rdat_val, (u_int *) & objp->rdat.rdat_len, ~0)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_WDAT_args (xdrs, objp)
	XDR            *xdrs;

	WDAT_args      *objp;
{
	if (!xdr_string (xdrs, &objp->file_name, ~0)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->matnum)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->data_type)) {
		return (FALSE);
	}
	if (!xdr_bytes (xdrs, (char **) &objp->wdat.wdat_val, (u_int *) & objp->wdat.wdat_len, ~0)) {
		return (FALSE);
	}
	return (TRUE);
}
