/*$Id: ecatMcs_xdr.c,v 1.3 1996/09/25 16:28:32 tom Exp $*/
/*$Log: ecatMcs_xdr.c,v $
 *Revision 1.3  1996/09/25 16:28:32  tom
 *build in Solaris 2
 *
 * Revision 1.2  1994/03/03  17:22:37  ty7777
 * Change from id to header.
 **/

/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <rpc/rpc.h>
#include "ecatMcs.h"

#ifndef lint
static char     rcsid[] = "$Header: /home/npggw/tom/src/libcti/RCS/ecatMcs_xdr.c,v 1.3 1996/09/25 16:28:32 tom Exp $";
#endif

bool_t
xdr_MCS_FUNCTIONS (xdrs, objp)
	XDR            *xdrs;

	MCS_FUNCTIONS  *objp;
{
	if (!xdr_enum (xdrs, (enum_t *) objp)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_MCS_MOTIONS (xdrs, objp)
	XDR            *xdrs;

	MCS_MOTIONS    *objp;
{
	if (!xdr_enum (xdrs, (enum_t *) objp)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_MCS_STATUS (xdrs, objp)
	XDR            *xdrs;

	MCS_STATUS     *objp;
{
	if (!xdr_int (xdrs, &objp->ps_status)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->rs_status)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->wob_status)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->bed_status)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->tilt_status)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->rot_status)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->ps_encoder)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->wob_encoder)) {
		return (FALSE);
	}
	if (!xdr_float (xdrs, &objp->hb_encoder)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->vb_encoder)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->tilt_encoder)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->rot_encoder)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->mcs_inp)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->ps_speed)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->wob_speed)) {
		return (FALSE);
	}
	if (!xdr_float (xdrs, &objp->bed_ref_encoder)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->septa_status)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_MCS_ZEROES (xdrs, objp)
	XDR            *xdrs;

	MCS_ZEROES     *objp;
{
	if (!xdr_int (xdrs, &objp->axis)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->value)) {
		return (FALSE);
	}
	return (TRUE);
}
