/*$Id: ecatRfa_xdr.c,v 1.3 1996/09/25 16:28:32 tom Exp $*/
/*$Log: ecatRfa_xdr.c,v $
 *Revision 1.3  1996/09/25 16:28:32  tom
 *build in Solaris 2
 *
 * Revision 1.2  1994/03/03  17:23:49  ty7777
 * Change from if to header.
 **/

/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <rpc/rpc.h>
#include "ecatRfa.h"

#ifndef lint
static char     rcsid[] = "$Header: /home/npggw/tom/src/libcti/RCS/ecatRfa_xdr.c,v 1.3 1996/09/25 16:28:32 tom Exp $";
#endif

bool_t
xdr_RFA_FUNCTIONS (xdrs, objp)
	XDR            *xdrs;

	RFA_FUNCTIONS  *objp;
{
	if (!xdr_enum (xdrs, (enum_t *) objp)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_RREN_args (xdrs, objp)
	XDR            *xdrs;

	RREN_args      *objp;
{
	if (!xdr_string (xdrs, &objp->oldName, 80)) {
		return (FALSE);
	}
	if (!xdr_string (xdrs, &objp->newName, 80)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_RCPY_args (xdrs, objp)
	XDR            *xdrs;

	RCPY_args      *objp;
{
	if (!xdr_string (xdrs, &objp->oldName, 80)) {
		return (FALSE);
	}
	if (!xdr_string (xdrs, &objp->newName, 80)) {
		return (FALSE);
	}
	if (!xdr_long (xdrs, &objp->fileSize)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_RDIR_args (xdrs, objp)
	XDR            *xdrs;

	RDIR_args      *objp;
{
	if (!xdr_string (xdrs, &objp->dirPath, 80)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->currDirNo)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_RDIR_resp (xdrs, objp)
	XDR            *xdrs;

	RDIR_resp      *objp;
{
	if (!xdr_string (xdrs, &objp->dirEntry, 80)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->nextDirNo)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->freeChunk)) {
		return (FALSE);
	}
	return (TRUE);
}
