/*$Id: ecatRecon.h,v 1.4 1999/12/13 22:02:19 tom Exp $*/
/*$Log: ecatRecon.h,v $
 *Revision 1.4  1999/12/13 22:02:19  tom
 *partially cleaned up with lint
 *
 * Revision 1.3  1996/09/25  16:28:32  tom
 * build in Solaris 2
 *
 * Revision 1.2  1994/03/11  20:06:24  ty7777
 * Change : to ;
 *
 * Revision 1.1  1994/03/11  19:40:02  ty7777
 * Initial revision
 **/

#ifndef ECATRECON_INCLUDED
#define ECATRECON_INCLUDED

/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <rpc/types.h>

#define RECON_SERVER 0x24000000
#define RECON_SERVER_VERSION 0
#define QUEMGR 0x24000000
#define QUEMGR_VERS 0

#ifndef lint
static char     rcsid_ecatRecon[] = "$Header: /home/npggw/tom/src/libcti/RCS/ecatRecon.h,v 1.4 1999/12/13 22:02:19 tom Exp $";
#endif

enum QUEMGR_CMDS {
	ADD_JOB = 1,
	QUE_STATUS = 2,
	DEL_JOB = 3,
	GET_JOB = 4
};

typedef enum QUEMGR_CMDS QUEMGR_CMDS;

bool_t          xdr_QUEMGR_CMDS ();

struct QUE_JOB_DATA {
	char           *scan_spec;
	char           *norm_spec;
	char           *attn_spec;
	char           *imag_spec;
	char           *zoom_spec;
	char           *offs_spec;
	char           *filt_spec;
	int             priority;
};

typedef struct QUE_JOB_DATA QUE_JOB_DATA;

bool_t          xdr_QUE_JOB_DATA ();

struct GET_JOB_DATA {
	QUE_JOB_DATA    job_data;
	int             job_id;
};

typedef struct GET_JOB_DATA GET_JOB_DATA;

bool_t          xdr_GET_JOB_DATA ();

struct QUE_STATUS_DATA {
	int             num_jobs;
};

typedef struct QUE_STATUS_DATA QUE_STATUS_DATA;

bool_t          xdr_QUE_STATUS_DATA ();

#endif						 /* ECATRECON_INCLUDED */
