/*$Id: ecatAcs_xdr.c,v 1.3 1996/09/25 16:28:32 tom Exp $*/
/*$Log: ecatAcs_xdr.c,v $
 *Revision 1.3  1996/09/25 16:28:32  tom
 *build in Solaris 2
 *
 * Revision 1.2  1994/03/03  17:21:39  ty7777
 * Change from if to header.
 **/

/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <rpc/rpc.h>
#include "ecatAcs.h"
/* @(#)ecatAcs.x	2.4 12/2/91 */

#ifndef lint
static char     rcsid[] = "$Header: /home/npggw/tom/src/libcti/RCS/ecatAcs_xdr.c,v 1.3 1996/09/25 16:28:32 tom Exp $";
#endif

bool_t          xdr_ECAT_ACS_FUNCTIONS (xdrs, objp)
	XDR            *xdrs;

	ECAT_ACS_FUNCTIONS *objp;
{
	if (!xdr_enum (xdrs, (enum_t *) objp)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_ButtonId (xdrs, objp)
	XDR            *xdrs;

	ButtonId       *objp;
{
	if (!xdr_int (xdrs, &objp->requestorPid)) {
		return (FALSE);
	}
	if (!xdr_string (xdrs, &objp->requestedNode, 32)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_TIMEX_resp (xdrs, objp)
	XDR            *xdrs;

	TIMEX_resp     *objp;
{
	if (!xdr_int (xdrs, &objp->seconds)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->minute)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->hour)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->day)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->month)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->year)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_TELL_ME_args (xdrs, objp)
	XDR            *xdrs;

	TELL_ME_args   *objp;
{
	if (!xdr_string (xdrs, &objp->whoIam, 32)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->tellMeAboutFrames)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->frameServerProg)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->frameServerVers)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->tellMeAboutImages)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->imageServerProg)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->imageServerVers)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->tellMeAboutArchives)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->archiveServerProg)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->archiveServerVers)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_TELL_ME_resp (xdrs, objp)
	XDR            *xdrs;

	TELL_ME_resp   *objp;
{
	if (!xdr_int (xdrs, &objp->frameServerProg)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->frameServerVers)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->tellMeAboutImages)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->imageServerProg)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->imageServerVers)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->archiveServerProg)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->archiveServerVers)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_STOP_TELLING_ME_args (xdrs, objp)
	XDR            *xdrs;

	STOP_TELLING_ME_args *objp;
{
	if (!xdr_string (xdrs, &objp->whoIam, 32)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->tellMeAboutFrames)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->frameServerProg)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->frameServerVers)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->tellMeAboutImages)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->imageServerProg)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->imageServerVers)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->tellMeAboutArchives)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->archiveServerProg)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->archiveServerVers)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_GEN_LOG_FILE_args (xdrs, objp)
	XDR            *xdrs;

	GEN_LOG_FILE_args *objp;
{
	if (!xdr_string (xdrs, &objp->file, 32)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->frame)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->matframe)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->bed)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->append)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_DELETE_LOG_ENTRY_args (xdrs, objp)
	XDR            *xdrs;

	DELETE_LOG_ENTRY_args *objp;
{
	if (!xdr_string (xdrs, &objp->file, 32)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->frame)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->matframe)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->bed)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_ARC_JOB_NOTIFY_args (xdrs, objp)
	XDR            *xdrs;

	ARC_JOB_NOTIFY_args *objp;
{
	if (!xdr_int (xdrs, &objp->status)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->jobtype)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->error_code)) {
		return (FALSE);
	}
	if (!xdr_string (xdrs, &objp->study, ~0)) {
		return (FALSE);
	}
	if (!xdr_string (xdrs, &objp->vol_name, ~0)) {
		return (FALSE);
	}
	if (!xdr_string (xdrs, &objp->filespec, ~0)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_ARC_GET_FILE_STAT_args (xdrs, objp)
	XDR            *xdrs;

	ARC_GET_FILE_STAT_args *objp;
{
	if (!xdr_short (xdrs, &objp->st_dev)) {
		return (FALSE);
	}
	if (!xdr_u_long (xdrs, &objp->st_ino)) {
		return (FALSE);
	}
	if (!xdr_u_short (xdrs, &objp->st_mode)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->st_nlink)) {
		return (FALSE);
	}
	if (!xdr_u_short (xdrs, &objp->st_uid)) {
		return (FALSE);
	}
	if (!xdr_u_short (xdrs, &objp->st_gid)) {
		return (FALSE);
	}
	if (!xdr_short (xdrs, &objp->st_rdev)) {
		return (FALSE);
	}
	if (!xdr_long (xdrs, &objp->st_size)) {
		return (FALSE);
	}
	if (!xdr_u_long (xdrs, &objp->st_atime0)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->st_spare1)) {
		return (FALSE);
	}
	if (!xdr_u_long (xdrs, &objp->st_mtime0)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->st_spare2)) {
		return (FALSE);
	}
	if (!xdr_u_long (xdrs, &objp->st_ctime0)) {
		return (FALSE);
	}
	if (!xdr_int (xdrs, &objp->st_spare3)) {
		return (FALSE);
	}
	if (!xdr_long (xdrs, &objp->st_blksize)) {
		return (FALSE);
	}
	if (!xdr_long (xdrs, &objp->st_blocks)) {
		return (FALSE);
	}
	if (!xdr_vector (xdrs, (char *) objp->st_spare4, 2, sizeof (long), xdr_long)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_ARC_SET_FILE_MTIME_args (xdrs, objp)
	XDR            *xdrs;

	ARC_SET_FILE_MTIME_args *objp;
{
	if (!xdr_string (xdrs, &objp->filename, ~0)) {
		return (FALSE);
	}
	if (!xdr_u_long (xdrs, &objp->mtime)) {
		return (FALSE);
	}
	return (TRUE);
}
