/*$Id: reconRpc.h,v 1.3 1999/12/13 22:02:19 tom Exp $*/
/*$Log: reconRpc.h,v $
 *Revision 1.3  1999/12/13 22:02:19  tom
 *partially cleaned up with lint
 *
 * Revision 1.2  1996/09/25  16:28:32  tom
 * build in Solaris 2
 *
 * Revision 1.1  1994/03/11  19:53:25  ty7777
 * Initial revision
 **/

#ifndef RECONRPC_INCLUDED
#define RECONRPC_INCLUDED

/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <rpc/types.h>

#ifndef lint
static char     rcsid_reconrpc[] = "$Header: /home/npggw/tom/src/libcti/RCS/reconRpc.h,v 1.3 1999/12/13 22:02:19 tom Exp $";
#endif

struct reconTypeData {
	char           *reconFile;
	int             reconFrame;
	int             reconGate;
	int             reconPlane;
	int             reconData;
	int             reconBed;
	int             reconMatnum;
};

typedef struct reconTypeData reconTypeData;

bool_t          xdr_reconTypeData ();

#define RECON_PROGRAM ((u_long)600000002)
#define RECON_VERSION ((u_long)1)
#define RECONPROC_NULL ((u_long)0)
extern void    *reconproc_null_1 ();

#define RECONPROC_COMPLETE ((u_long)1)
extern void    *reconproc_complete_1 ();

#endif						 /* RECONRPC_INCLUDED */
