#!/bin/csh
#   Name:   jpg2if
#   Date:   Jan 2008
#   Author: Tom Videen

if ($#argv != 7) then
	echo "Usage:  jpg2if inroot ext first last outfile xdim ydim"
	echo " e.g.,  jpg2if DSC00 tif 140 200 brain1 2848 2136"
	exit 1
endif

setenv ROOT    $1
setenv EXT    .$2
setenv FIRST   $3
setenv LAST    $4
setenv OUTNAME $5
setenv XDIM    $6
setenv YDIM    $7
set infile  = $ROOT$FIRST$EXT

if (! -e $infile) then
	echo "ERROR [jpg2if]: $infile does not exist"
	exit 1
endif

setenv IDL_NAME jpg2if
run_idl
