#!/bin/csh
#	Module:	metproc
#	Date:	Dec-95
#	Author:	Tom Videen
#	Use:	Create an HDR file allowing display and analysis of a PET image
#			as a metabolic image.
#			Requires a PET image, a blood curve (.dta), and a calibration file (.pie)

set BINPATH = /usr/local/npg/bin

if ($#argv != 1) then
	echo "Usage: metproc <subject_id>"
	exit
endif
/home/npggw/tom/src/metproc/metproc.bin $1
