/*$Id: rfa_xdr.c,v 1.2 1995/10/31 14:51:32 tom Exp $*/
/*$Log: rfa_xdr.c,v $
 * Revision 1.2  1995/10/31  14:51:32  tom
 * *** empty log message ***
 *
 * Revision 1.1  1995/10/16  18:53:48  ty7777
 * Initial revision
 **/

/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rfa_xdr.h"

static char rcsid [] = "$Header: /export/home/npggw/tom/src/libecat7/RCS/rfa_xdr.c,v 1.2 1995/10/31 14:51:32 tom Exp $";

bool_t xdr_RFA_FUNCTIONS(xdrs, objp)
XDR *xdrs;
RFA_FUNCTIONS *objp;
{
	if (!xdr_enum(xdrs, (char *)objp)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t xdr_RREN_args(xdrs, objp)
XDR *xdrs;
RREN_args *objp;
{
	if (!xdr_string(xdrs, &objp->oldName, 80)) {
		return (FALSE);
	}
	if (!xdr_string(xdrs, &objp->newName, 80)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t xdr_RCPY_args(xdrs, objp)
XDR *xdrs;
RCPY_args *objp;
{
	if (!xdr_string(xdrs, &objp->oldName, 80)) {
		return (FALSE);
	}
	if (!xdr_string(xdrs, &objp->newName, 80)) {
		return (FALSE);
	}
	if (!xdr_long(xdrs, (char*)&objp->fileSize)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t xdr_RDIR_args(xdrs, objp)
XDR *xdrs;
RDIR_args *objp;
{
	if (!xdr_string(xdrs, &objp->dirPath, 80)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, (char*)&objp->currDirNo)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t xdr_RDIR_resp(xdrs, objp)
XDR *xdrs;
RDIR_resp *objp;
{
	if (!xdr_string(xdrs, &objp->dirEntry, 80)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, (char*)&objp->nextDirNo)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, (char*)&objp->freeChunk)) {
		return (FALSE);
	}
	return (TRUE);
}
